// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var DimDates = Table[
	dimDateColumns,
	dimDateIndexes,
	dimDateForeignKeys,
	dimDateUniques,
	dimDateChecks,
]{
	Schema: "",
	Name:   "dim_date",
	Columns: dimDateColumns{
		Date: column{
			Name:      "date",
			DBType:    "date",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Month: column{
			Name:      "month",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Year: column{
			Name:      "year",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Quarter: column{
			Name:      "quarter",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DayOfWeek: column{
			Name:      "day_of_week",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DayOfMonth: column{
			Name:      "day_of_month",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DayOfYear: column{
			Name:      "day_of_year",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		WeekOfYear: column{
			Name:      "week_of_year",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		WeekOfMonth: column{
			Name:      "week_of_month",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: dimDateIndexes{
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "date",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"date"},
		Comment: "",
	},

	Comment: "",
}

type dimDateColumns struct {
	Date        column
	Month       column
	Year        column
	Quarter     column
	DayOfWeek   column
	DayOfMonth  column
	DayOfYear   column
	WeekOfYear  column
	WeekOfMonth column
}

func (c dimDateColumns) AsSlice() []column {
	return []column{
		c.Date, c.Month, c.Year, c.Quarter, c.DayOfWeek, c.DayOfMonth, c.DayOfYear, c.WeekOfYear, c.WeekOfMonth,
	}
}

type dimDateIndexes struct {
	PRIMARY index
}

func (i dimDateIndexes) AsSlice() []index {
	return []index{
		i.PRIMARY,
	}
}

type dimDateForeignKeys struct{}

func (f dimDateForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type dimDateUniques struct{}

func (u dimDateUniques) AsSlice() []constraint {
	return []constraint{}
}

type dimDateChecks struct{}

func (c dimDateChecks) AsSlice() []check {
	return []check{}
}
