// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Discounts = Table[
	discountColumns,
	discountIndexes,
	discountForeignKeys,
	discountUniques,
	discountChecks,
]{
	Schema: "",
	Name:   "discounts",
	Columns: discountColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		Name: column{
			Name:      "name",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Category: column{
			Name:      "category",
			DBType:    "varchar(32)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DiscountType: column{
			Name:      "discount_type",
			DBType:    "varchar(12)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Discount: column{
			Name:      "discount",
			DBType:    "decimal(10,4)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: discountIndexes{
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type discountColumns struct {
	ID           column
	Name         column
	Category     column
	DiscountType column
	Discount     column
	CreatedAt    column
	UpdatedAt    column
}

func (c discountColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.Category, c.DiscountType, c.Discount, c.CreatedAt, c.UpdatedAt,
	}
}

type discountIndexes struct {
	PRIMARY index
}

func (i discountIndexes) AsSlice() []index {
	return []index{
		i.PRIMARY,
	}
}

type discountForeignKeys struct{}

func (f discountForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type discountUniques struct{}

func (u discountUniques) AsSlice() []constraint {
	return []constraint{}
}

type discountChecks struct{}

func (c discountChecks) AsSlice() []check {
	return []check{}
}
