// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var OrderPayments = Table[
	orderPaymentColumns,
	orderPaymentIndexes,
	orderPaymentForeignKeys,
	orderPaymentUniques,
	orderPaymentChecks,
]{
	Schema: "",
	Name:   "order_payments",
	Columns: orderPaymentColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		OrderID: column{
			Name:      "order_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PaymentType: column{
			Name:      "payment_type",
			DBType:    "varchar(12)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Amount: column{
			Name:      "amount",
			DBType:    "decimal(10,2)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PaymentInfo: column{
			Name:      "payment_info",
			DBType:    "json",
			Default:   "",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: orderPaymentIndexes{
		OrderID: index{
			Type: "BTREE",
			Name: "order_id",
			Columns: []indexColumn{
				{
					Name:         "order_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: orderPaymentForeignKeys{
		OrderPaymentsIbfk1: foreignKey{
			constraint: constraint{
				Name:    "order_payments_ibfk_1",
				Columns: []string{"order_id"},
				Comment: "",
			},
			ForeignTable:   "orders",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type orderPaymentColumns struct {
	ID          column
	OrderID     column
	PaymentType column
	Amount      column
	PaymentInfo column
	CreatedAt   column
	UpdatedAt   column
}

func (c orderPaymentColumns) AsSlice() []column {
	return []column{
		c.ID, c.OrderID, c.PaymentType, c.Amount, c.PaymentInfo, c.CreatedAt, c.UpdatedAt,
	}
}

type orderPaymentIndexes struct {
	OrderID index
	PRIMARY index
}

func (i orderPaymentIndexes) AsSlice() []index {
	return []index{
		i.OrderID, i.PRIMARY,
	}
}

type orderPaymentForeignKeys struct {
	OrderPaymentsIbfk1 foreignKey
}

func (f orderPaymentForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.OrderPaymentsIbfk1,
	}
}

type orderPaymentUniques struct{}

func (u orderPaymentUniques) AsSlice() []constraint {
	return []constraint{}
}

type orderPaymentChecks struct{}

func (c orderPaymentChecks) AsSlice() []check {
	return []check{}
}
