// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Orders = Table[
	orderColumns,
	orderIndexes,
	orderForeignKeys,
	orderUniques,
	orderChecks,
]{
	Schema: "",
	Name:   "orders",
	Columns: orderColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		OrderDate: column{
			Name:      "order_date",
			DBType:    "date",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CustomerID: column{
			Name:      "customer_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		DiscountID: column{
			Name:      "discount_id",
			DBType:    "bigint",
			Default:   "",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		OrderType: column{
			Name:      "order_type",
			DBType:    "varchar(12)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Subtotal: column{
			Name:      "subtotal",
			DBType:    "decimal(10,2)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		DiscountAmount: column{
			Name:      "discount_amount",
			DBType:    "decimal(10,2)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TaxAmount: column{
			Name:      "tax_amount",
			DBType:    "decimal(10,2)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Total: column{
			Name:      "total",
			DBType:    "decimal(10,2)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: orderIndexes{
		CustomerID: index{
			Type: "BTREE",
			Name: "customer_id",
			Columns: []indexColumn{
				{
					Name:         "customer_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		DiscountID: index{
			Type: "BTREE",
			Name: "discount_id",
			Columns: []indexColumn{
				{
					Name:         "discount_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  false,
			Comment: "",
		},
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: orderForeignKeys{
		OrdersIbfk1: foreignKey{
			constraint: constraint{
				Name:    "orders_ibfk_1",
				Columns: []string{"customer_id"},
				Comment: "",
			},
			ForeignTable:   "customers",
			ForeignColumns: []string{"id"},
		},
		OrdersIbfk2: foreignKey{
			constraint: constraint{
				Name:    "orders_ibfk_2",
				Columns: []string{"discount_id"},
				Comment: "",
			},
			ForeignTable:   "discounts",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type orderColumns struct {
	ID             column
	OrderDate      column
	CustomerID     column
	DiscountID     column
	OrderType      column
	Subtotal       column
	DiscountAmount column
	TaxAmount      column
	Total          column
	CreatedAt      column
	UpdatedAt      column
}

func (c orderColumns) AsSlice() []column {
	return []column{
		c.ID, c.OrderDate, c.CustomerID, c.DiscountID, c.OrderType, c.Subtotal, c.DiscountAmount, c.TaxAmount, c.Total, c.CreatedAt, c.UpdatedAt,
	}
}

type orderIndexes struct {
	CustomerID index
	DiscountID index
	PRIMARY    index
}

func (i orderIndexes) AsSlice() []index {
	return []index{
		i.CustomerID, i.DiscountID, i.PRIMARY,
	}
}

type orderForeignKeys struct {
	OrdersIbfk1 foreignKey
	OrdersIbfk2 foreignKey
}

func (f orderForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.OrdersIbfk1, f.OrdersIbfk2,
	}
}

type orderUniques struct{}

func (u orderUniques) AsSlice() []constraint {
	return []constraint{}
}

type orderChecks struct{}

func (c orderChecks) AsSlice() []check {
	return []check{}
}
