// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var PaymentNames = Table[
	paymentNameColumns,
	paymentNameIndexes,
	paymentNameForeignKeys,
	paymentNameUniques,
	paymentNameChecks,
]{
	Schema: "",
	Name:   "payment_names",
	Columns: paymentNameColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		PaymentType: column{
			Name:      "payment_type",
			DBType:    "varchar(12)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Name: column{
			Name:      "name",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: paymentNameIndexes{
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type paymentNameColumns struct {
	ID          column
	PaymentType column
	Name        column
	CreatedAt   column
	UpdatedAt   column
}

func (c paymentNameColumns) AsSlice() []column {
	return []column{
		c.ID, c.PaymentType, c.Name, c.CreatedAt, c.UpdatedAt,
	}
}

type paymentNameIndexes struct {
	PRIMARY index
}

func (i paymentNameIndexes) AsSlice() []index {
	return []index{
		i.PRIMARY,
	}
}

type paymentNameForeignKeys struct{}

func (f paymentNameForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type paymentNameUniques struct{}

func (u paymentNameUniques) AsSlice() []constraint {
	return []constraint{}
}

type paymentNameChecks struct{}

func (c paymentNameChecks) AsSlice() []check {
	return []check{}
}
