// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Products = Table[
	productColumns,
	productIndexes,
	productForeignKeys,
	productUniques,
	productChecks,
]{
	Schema: "",
	Name:   "products",
	Columns: productColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		Name: column{
			Name:      "name",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Category: column{
			Name:      "category",
			DBType:    "varchar(32)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Price: column{
			Name:      "price",
			DBType:    "decimal(10,2)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: productIndexes{
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type productColumns struct {
	ID        column
	Name      column
	Category  column
	Price     column
	CreatedAt column
	UpdatedAt column
}

func (c productColumns) AsSlice() []column {
	return []column{
		c.ID, c.Name, c.Category, c.Price, c.CreatedAt, c.UpdatedAt,
	}
}

type productIndexes struct {
	PRIMARY index
}

func (i productIndexes) AsSlice() []index {
	return []index{
		i.PRIMARY,
	}
}

type productForeignKeys struct{}

func (f productForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type productUniques struct{}

func (u productUniques) AsSlice() []constraint {
	return []constraint{}
}

type productChecks struct{}

func (c productChecks) AsSlice() []check {
	return []check{}
}
