// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var ReportingOrders = Table[
	reportingOrderColumns,
	reportingOrderIndexes,
	reportingOrderForeignKeys,
	reportingOrderUniques,
	reportingOrderChecks,
]{
	Schema: "",
	Name:   "reporting_order",
	Columns: reportingOrderColumns{
		ID: column{
			Name:      "id",
			DBType:    "bigint",
			Default:   "AUTO_INCREMENT",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  true,
		},
		Category: column{
			Name:      "category",
			DBType:    "varchar(32)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		OrderType: column{
			Name:      "order_type",
			DBType:    "varchar(12)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ReportOrder: column{
			Name:      "report_order",
			DBType:    "int",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Title: column{
			Name:      "title",
			DBType:    "varchar(255)",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp",
			Default:   "CURRENT_TIMESTAMP",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: reportingOrderIndexes{
		PRIMARY: index{
			Type: "BTREE",
			Name: "PRIMARY",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:  true,
			Comment: "",
		},
	},
	PrimaryKey: &constraint{
		Name:    "PRIMARY",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type reportingOrderColumns struct {
	ID          column
	Category    column
	OrderType   column
	ReportOrder column
	Title       column
	CreatedAt   column
	UpdatedAt   column
}

func (c reportingOrderColumns) AsSlice() []column {
	return []column{
		c.ID, c.Category, c.OrderType, c.ReportOrder, c.Title, c.CreatedAt, c.UpdatedAt,
	}
}

type reportingOrderIndexes struct {
	PRIMARY index
}

func (i reportingOrderIndexes) AsSlice() []index {
	return []index{
		i.PRIMARY,
	}
}

type reportingOrderForeignKeys struct{}

func (f reportingOrderForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type reportingOrderUniques struct{}

func (u reportingOrderUniques) AsSlice() []constraint {
	return []constraint{}
}

type reportingOrderChecks struct{}

func (c reportingOrderChecks) AsSlice() []check {
	return []check{}
}
