-- Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
-- This file is meant to be re-generated in place and/or deleted at any time.

-- DailyRevenue
SELECT `order_type`, `order_date`, SUM(`total`) AS `total_revenue`
FROM `orders`
WHERE `order_date` >= ?  AND `order_date` <= ? 
GROUP BY `order_type`, `order_date`
ORDER BY `order_date`, `order_type`;

-- CustomerSales
SELECT `c`.`id`, `c`.`name`, SUM(`o`.`total`) AS `total_sales`, COUNT(`o`.`id`) AS `total_orders`
FROM `customers` `c`
INNER JOIN `orders` `o` ON `o`.`customer_id` = `c`.`id`
WHERE `o`.`order_date` >= ?  AND `o`.`order_date` <= ? 
GROUP BY `c`.`id`, `c`.`name`
ORDER BY `total_sales` DESC;

-- DailySoldItems
SELECT `id`, name, `category`, 
SUM(`total_quantity`) AS `total_quantity`, 
SUM(`total_sales`) AS `total_sales`
FROM `item_summaries`
WHERE DATE(`order_date`) = ?
GROUP BY `id`, name, `category`
ORDER BY `category`, name;

-- GeneralSales
SELECT `ro`.`title`, `ro`.`report_order`, `t`.`name`, 
SUM(`t`.`order_count`) AS `order_count`,
SUM(`t`.`total_quantity`) AS `quantity`,
SUM(`t`.`total_sales`) AS `total_sales`
FROM `item_summaries` `t` 
INNER JOIN `reporting_order` `ro` ON `ro`.`order_type` = 'general' AND `ro`.`category` = `t`.`category`
WHERE `t`.`order_date` >= ?  AND `t`.`order_date` <= ? 
GROUP BY `ro`.`title`, `ro`.`report_order`, `t`.`name` 
ORDER BY `ro`.`report_order`, `t`.`name`;

-- WeeklyTypedSales
SELECT `dim_date`.`year`, `dim_date`.`WEEK_OF_YEAR` , 
`ro`.`title`, `ro`.`report_order`, `t`.`name`, 
SUM(`t`.`total_quantity`) AS `quantity`,
SUM(`t`.`total_sales`) AS `total_sales`
FROM `item_summaries` `t` 
INNER JOIN `reporting_order` `ro` ON `ro`.`order_type` = `t`.`order_type` AND `ro`.`category` = `t`.`category`
INNER JOIN `dim_date` ON `dim_date`.`date` = `t`.`order_date`
WHERE `t`.`order_date` >= ?  AND `t`.`order_date` <= ? 
GROUP BY `dim_date`.`year`, `dim_date`.`WEEK_OF_YEAR`,`ro`.`title`, `ro`.`report_order`, `t`.`name` 
ORDER BY `dim_date`.`year`, `dim_date`.`WEEK_OF_YEAR`, `ro`.`report_order`, `t`.`name`;
