// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package queries

import (
	"context"
	_ "embed"
	"io"
	"iter"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/scan"
)

//go:embed queries.bob.sql
var formattedQueries_queries string

var dailyRevenueSQL = formattedQueries_queries[151:351]

type DailyRevenueQuery = orm.ModQuery[*dialect.SelectQuery, dailyRevenue, DailyRevenueRow, []DailyRevenueRow, dailyRevenueTransformer]

func DailyRevenue(StartDate time.Time, EndDate time.Time) *DailyRevenueQuery {
	var expressionTypArgs dailyRevenue

	expressionTypArgs.StartDate = mysql.Arg(StartDate)
	expressionTypArgs.EndDate = mysql.Arg(EndDate)

	return &DailyRevenueQuery{
		Query: orm.Query[dailyRevenue, DailyRevenueRow, []DailyRevenueRow, dailyRevenueTransformer]{
			ExecQuery: orm.ExecQuery[dailyRevenue]{
				BaseQuery: bob.BaseQuery[dailyRevenue]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (DailyRevenueRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t DailyRevenueRow
						row.ScheduleScanByIndex(0, &t.OrderType)
						row.ScheduleScanByIndex(1, &t.OrderDate)
						row.ScheduleScanByIndex(2, &t.TotalRevenue)
						return &t, nil
					}, func(v any) (DailyRevenueRow, error) {
						return *(v.(*DailyRevenueRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(7, 66))
			q.SetTable(expressionTypArgs.subExpr(72, 80))
			q.AppendWhere(expressionTypArgs.subExpr(87, 127))
			q.AppendGroup(expressionTypArgs.subExpr(137, 164))
			q.CombinedOrder.AppendOrder(expressionTypArgs.subExpr(173, 200))
		}),
	}
}

type DailyRevenueRow = struct {
	OrderType    string    `db:"order_type"`
	OrderDate    time.Time `db:"order_date"`
	TotalRevenue string    `db:"total_revenue"`
}

type dailyRevenueTransformer = bob.SliceTransformer[DailyRevenueRow, []DailyRevenueRow]

type dailyRevenue struct {
	StartDate bob.Expression
	EndDate   bob.Expression
}

func (o dailyRevenue) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "startDate",
			Start:      103,
			Stop:       104,
			Expression: o.StartDate,
		}) {
			return
		}

		if !yield(orm.ArgWithPosition{
			Name:       "endDate",
			Start:      126,
			Stop:       127,
			Expression: o.EndDate,
		}) {
			return
		}
	}
}

func (o dailyRevenue) raw(from, to int) string {
	return dailyRevenueSQL[from:to]
}

func (o dailyRevenue) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(dailyRevenueSQL, from, to, o.args())
}

func (o dailyRevenue) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(dailyRevenueSQL)).WriteSQL(ctx, w, d, start)
}

var customerSalesSQL = formattedQueries_queries[371:659]

type CustomerSalesQuery = orm.ModQuery[*dialect.SelectQuery, customerSales, CustomerSalesRow, []CustomerSalesRow, customerSalesTransformer]

func CustomerSales(StartDate time.Time, EndDate time.Time) *CustomerSalesQuery {
	var expressionTypArgs customerSales

	expressionTypArgs.StartDate = mysql.Arg(StartDate)
	expressionTypArgs.EndDate = mysql.Arg(EndDate)

	return &CustomerSalesQuery{
		Query: orm.Query[customerSales, CustomerSalesRow, []CustomerSalesRow, customerSalesTransformer]{
			ExecQuery: orm.ExecQuery[customerSales]{
				BaseQuery: bob.BaseQuery[customerSales]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (CustomerSalesRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t CustomerSalesRow
						row.ScheduleScanByIndex(0, &t.ID)
						row.ScheduleScanByIndex(1, &t.Name)
						row.ScheduleScanByIndex(2, &t.TotalSales)
						row.ScheduleScanByIndex(3, &t.TotalOrders)
						return &t, nil
					}, func(v any) (CustomerSalesRow, error) {
						return *(v.(*CustomerSalesRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(7, 97))
			q.SetTable(expressionTypArgs.subExpr(103, 174))
			q.AppendWhere(expressionTypArgs.subExpr(181, 229))
			q.AppendGroup(expressionTypArgs.subExpr(239, 260))
			q.CombinedOrder.AppendOrder(expressionTypArgs.subExpr(269, 288))
		}),
	}
}

type CustomerSalesRow = struct {
	ID          int64  `db:"id"`
	Name        string `db:"name"`
	TotalSales  string `db:"total_sales"`
	TotalOrders string `db:"total_orders"`
}

type customerSalesTransformer = bob.SliceTransformer[CustomerSalesRow, []CustomerSalesRow]

type customerSales struct {
	StartDate bob.Expression
	EndDate   bob.Expression
}

func (o customerSales) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "startDate",
			Start:      201,
			Stop:       202,
			Expression: o.StartDate,
		}) {
			return
		}

		if !yield(orm.ArgWithPosition{
			Name:       "endDate",
			Start:      228,
			Stop:       229,
			Expression: o.EndDate,
		}) {
			return
		}
	}
}

func (o customerSales) raw(from, to int) string {
	return customerSalesSQL[from:to]
}

func (o customerSales) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(customerSalesSQL, from, to, o.args())
}

func (o customerSales) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(customerSalesSQL)).WriteSQL(ctx, w, d, start)
}

var dailySoldItemsSQL = formattedQueries_queries[680:900]

type DailySoldItemsQuery = orm.ModQuery[*dialect.SelectQuery, dailySoldItems, DailySoldItemsRow, []DailySoldItemsRow, dailySoldItemsTransformer]

func DailySoldItems(Arg string) *DailySoldItemsQuery {
	var expressionTypArgs dailySoldItems

	expressionTypArgs.Arg = mysql.Arg(Arg)

	return &DailySoldItemsQuery{
		Query: orm.Query[dailySoldItems, DailySoldItemsRow, []DailySoldItemsRow, dailySoldItemsTransformer]{
			ExecQuery: orm.ExecQuery[dailySoldItems]{
				BaseQuery: bob.BaseQuery[dailySoldItems]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (DailySoldItemsRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t DailySoldItemsRow
						row.ScheduleScanByIndex(0, &t.ID)
						row.ScheduleScanByIndex(1, &t.Name)
						row.ScheduleScanByIndex(2, &t.Category)
						row.ScheduleScanByIndex(3, &t.TotalQuantity)
						row.ScheduleScanByIndex(4, &t.TotalSales)
						return &t, nil
					}, func(v any) (DailySoldItemsRow, error) {
						return *(v.(*DailySoldItemsRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(7, 111))
			q.SetTable(expressionTypArgs.subExpr(117, 133))
			q.AppendWhere(expressionTypArgs.subExpr(140, 162))
			q.AppendGroup(expressionTypArgs.subExpr(171, 194))
			q.CombinedOrder.AppendOrder(expressionTypArgs.subExpr(203, 220))
		}),
	}
}

type DailySoldItemsRow = struct {
	ID            null.Val[int64] `db:"id"`
	Name          string          `db:"name"`
	Category      string          `db:"category"`
	TotalQuantity string          `db:"total_quantity"`
	TotalSales    string          `db:"total_sales"`
}

type dailySoldItemsTransformer = bob.SliceTransformer[DailySoldItemsRow, []DailySoldItemsRow]

type dailySoldItems struct {
	Arg bob.Expression
}

func (o dailySoldItems) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "arg",
			Start:      161,
			Stop:       162,
			Expression: o.Arg,
		}) {
			return
		}
	}
}

func (o dailySoldItems) raw(from, to int) string {
	return dailySoldItemsSQL[from:to]
}

func (o dailySoldItems) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(dailySoldItemsSQL, from, to, o.args())
}

func (o dailySoldItems) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(dailySoldItemsSQL)).WriteSQL(ctx, w, d, start)
}

var generalSalesSQL = formattedQueries_queries[919:1379]

type GeneralSalesQuery = orm.ModQuery[*dialect.SelectQuery, generalSales, GeneralSalesRow, []GeneralSalesRow, generalSalesTransformer]

func GeneralSales(StartDate string, EndDate string) *GeneralSalesQuery {
	var expressionTypArgs generalSales

	expressionTypArgs.StartDate = mysql.Arg(StartDate)
	expressionTypArgs.EndDate = mysql.Arg(EndDate)

	return &GeneralSalesQuery{
		Query: orm.Query[generalSales, GeneralSalesRow, []GeneralSalesRow, generalSalesTransformer]{
			ExecQuery: orm.ExecQuery[generalSales]{
				BaseQuery: bob.BaseQuery[generalSales]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (GeneralSalesRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t GeneralSalesRow
						row.ScheduleScanByIndex(0, &t.Title)
						row.ScheduleScanByIndex(1, &t.ReportOrder)
						row.ScheduleScanByIndex(2, &t.Name)
						row.ScheduleScanByIndex(3, &t.OrderCount)
						row.ScheduleScanByIndex(4, &t.Quantity)
						row.ScheduleScanByIndex(5, &t.TotalSales)
						return &t, nil
					}, func(v any) (GeneralSalesRow, error) {
						return *(v.(*GeneralSalesRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(7, 176))
			q.SetTable(expressionTypArgs.subExpr(182, 307))
			q.AppendWhere(expressionTypArgs.subExpr(314, 362))
			q.AppendGroup(expressionTypArgs.subExpr(372, 418))
			q.CombinedOrder.AppendOrder(expressionTypArgs.subExpr(428, 460))
		}),
	}
}

type GeneralSalesRow = struct {
	Title       string `db:"title"`
	ReportOrder int32  `db:"report_order"`
	Name        string `db:"name"`
	OrderCount  string `db:"order_count"`
	Quantity    string `db:"quantity"`
	TotalSales  string `db:"total_sales"`
}

type generalSalesTransformer = bob.SliceTransformer[GeneralSalesRow, []GeneralSalesRow]

type generalSales struct {
	StartDate bob.Expression
	EndDate   bob.Expression
}

func (o generalSales) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "startDate",
			Start:      334,
			Stop:       335,
			Expression: o.StartDate,
		}) {
			return
		}

		if !yield(orm.ArgWithPosition{
			Name:       "endDate",
			Start:      361,
			Stop:       362,
			Expression: o.EndDate,
		}) {
			return
		}
	}
}

func (o generalSales) raw(from, to int) string {
	return generalSalesSQL[from:to]
}

func (o generalSales) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(generalSalesSQL, from, to, o.args())
}

func (o generalSales) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(generalSalesSQL)).WriteSQL(ctx, w, d, start)
}

var weeklyTypedSalesSQL = formattedQueries_queries[1402:2029]

type WeeklyTypedSalesQuery = orm.ModQuery[*dialect.SelectQuery, weeklyTypedSales, WeeklyTypedSalesRow, []WeeklyTypedSalesRow, weeklyTypedSalesTransformer]

func WeeklyTypedSales(StartDate string, EndDate string) *WeeklyTypedSalesQuery {
	var expressionTypArgs weeklyTypedSales

	expressionTypArgs.StartDate = mysql.Arg(StartDate)
	expressionTypArgs.EndDate = mysql.Arg(EndDate)

	return &WeeklyTypedSalesQuery{
		Query: orm.Query[weeklyTypedSales, WeeklyTypedSalesRow, []WeeklyTypedSalesRow, weeklyTypedSalesTransformer]{
			ExecQuery: orm.ExecQuery[weeklyTypedSales]{
				BaseQuery: bob.BaseQuery[weeklyTypedSales]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (WeeklyTypedSalesRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t WeeklyTypedSalesRow
						row.ScheduleScanByIndex(0, &t.Year)
						row.ScheduleScanByIndex(1, &t.Week)
						row.ScheduleScanByIndex(2, &t.Title)
						row.ScheduleScanByIndex(3, &t.ReportOrder)
						row.ScheduleScanByIndex(4, &t.Name)
						row.ScheduleScanByIndex(5, &t.Quantity)
						row.ScheduleScanByIndex(6, &t.TotalSales)
						return &t, nil
					}, func(v any) (WeeklyTypedSalesRow, error) {
						return *(v.(*WeeklyTypedSalesRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(7, 183))
			q.SetTable(expressionTypArgs.subExpr(189, 383))
			q.AppendWhere(expressionTypArgs.subExpr(390, 438))
			q.AppendGroup(expressionTypArgs.subExpr(448, 539))
			q.CombinedOrder.AppendOrder(expressionTypArgs.subExpr(549, 627))
		}),
	}
}

type WeeklyTypedSalesRow = struct {
	Year        int32  `db:"year"`
	Week        string `db:"WEEK_OF_YEAR"`
	Title       string `db:"title"`
	ReportOrder int32  `db:"report_order"`
	Name        string `db:"name"`
	Quantity    string `db:"quantity"`
	TotalSales  string `db:"total_sales"`
}

type weeklyTypedSalesTransformer = bob.SliceTransformer[WeeklyTypedSalesRow, []WeeklyTypedSalesRow]

type weeklyTypedSales struct {
	StartDate bob.Expression
	EndDate   bob.Expression
}

func (o weeklyTypedSales) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "startDate",
			Start:      410,
			Stop:       411,
			Expression: o.StartDate,
		}) {
			return
		}

		if !yield(orm.ArgWithPosition{
			Name:       "endDate",
			Start:      437,
			Stop:       438,
			Expression: o.EndDate,
		}) {
			return
		}
	}
}

func (o weeklyTypedSales) raw(from, to int) string {
	return weeklyTypedSalesSQL[from:to]
}

func (o weeklyTypedSales) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(weeklyTypedSalesSQL, from, to, o.args())
}

func (o weeklyTypedSales) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(weeklyTypedSalesSQL)).WriteSQL(ctx, w, d, start)
}
