// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"errors"
	"fmt"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/orm"
)

var Preload = getPreloaders()

type preloaders struct {
	Customer     customerPreloader
	Discount     discountPreloader
	OrderItem    orderItemPreloader
	OrderPayment orderPaymentPreloader
	Order        orderPreloader
	Product      productPreloader
}

func getPreloaders() preloaders {
	return preloaders{
		Customer:     buildCustomerPreloader(),
		Discount:     buildDiscountPreloader(),
		OrderItem:    buildOrderItemPreloader(),
		OrderPayment: buildOrderPaymentPreloader(),
		Order:        buildOrderPreloader(),
		Product:      buildProductPreloader(),
	}
}

var SelectThenLoad = getThenLoaders[*dialect.SelectQuery]()

type thenLoaders[Q orm.Loadable] struct {
	Customer     customerThenLoader[Q]
	Discount     discountThenLoader[Q]
	OrderItem    orderItemThenLoader[Q]
	OrderPayment orderPaymentThenLoader[Q]
	Order        orderThenLoader[Q]
	Product      productThenLoader[Q]
}

func getThenLoaders[Q orm.Loadable]() thenLoaders[Q] {
	return thenLoaders[Q]{
		Customer:     buildCustomerThenLoader[Q](),
		Discount:     buildDiscountThenLoader[Q](),
		OrderItem:    buildOrderItemThenLoader[Q](),
		OrderPayment: buildOrderPaymentThenLoader[Q](),
		Order:        buildOrderThenLoader[Q](),
		Product:      buildProductThenLoader[Q](),
	}
}

func thenLoadBuilder[Q orm.Loadable, T any](name string, f func(context.Context, bob.Executor, T, ...bob.Mod[*dialect.SelectQuery]) error) func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q] {
	return func(queryMods ...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q] {
		return func(ctx context.Context, exec bob.Executor, retrieved any) error {
			loader, isLoader := retrieved.(T)
			if !isLoader {
				return fmt.Errorf("object %T cannot load %q", retrieved, name)
			}

			err := f(ctx, exec, loader, queryMods...)

			// Don't cause an issue due to missing relationships
			if errors.Is(err, sql.ErrNoRows) {
				return nil
			}

			return err
		}
	}
}
