// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"hash/maphash"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
)

var (
	SelectJoins = getJoins[*dialect.SelectQuery]()
	UpdateJoins = getJoins[*dialect.UpdateQuery]()
	DeleteJoins = getJoins[*dialect.DeleteQuery]()
)

type joinSet[Q interface{ aliasedAs(string) Q }] struct {
	InnerJoin Q
	LeftJoin  Q
	RightJoin Q
}

func (j joinSet[Q]) AliasedAs(alias string) joinSet[Q] {
	return joinSet[Q]{
		InnerJoin: j.InnerJoin.aliasedAs(alias),
		LeftJoin:  j.LeftJoin.aliasedAs(alias),
		RightJoin: j.RightJoin.aliasedAs(alias),
	}
}

type joins[Q dialect.Joinable] struct {
	Customers     joinSet[customerJoins[Q]]
	Discounts     joinSet[discountJoins[Q]]
	OrderItems    joinSet[orderItemJoins[Q]]
	OrderPayments joinSet[orderPaymentJoins[Q]]
	Orders        joinSet[orderJoins[Q]]
	Products      joinSet[productJoins[Q]]
}

func buildJoinSet[Q interface{ aliasedAs(string) Q }, C any, F func(C, string) Q](c C, f F) joinSet[Q] {
	return joinSet[Q]{
		InnerJoin: f(c, clause.InnerJoin),
		LeftJoin:  f(c, clause.LeftJoin),
		RightJoin: f(c, clause.RightJoin),
	}
}

func getJoins[Q dialect.Joinable]() joins[Q] {
	return joins[Q]{
		Customers:     buildJoinSet[customerJoins[Q]](Customers.Columns, buildCustomerJoins),
		Discounts:     buildJoinSet[discountJoins[Q]](Discounts.Columns, buildDiscountJoins),
		OrderItems:    buildJoinSet[orderItemJoins[Q]](OrderItems.Columns, buildOrderItemJoins),
		OrderPayments: buildJoinSet[orderPaymentJoins[Q]](OrderPayments.Columns, buildOrderPaymentJoins),
		Orders:        buildJoinSet[orderJoins[Q]](Orders.Columns, buildOrderJoins),
		Products:      buildJoinSet[productJoins[Q]](Products.Columns, buildProductJoins),
	}
}

type modAs[Q any, C interface{ AliasedAs(string) C }] struct {
	c C
	f func(C) bob.Mod[Q]
}

func (m modAs[Q, C]) Apply(q Q) {
	m.f(m.c).Apply(q)
}

func (m modAs[Q, C]) AliasedAs(alias string) bob.Mod[Q] {
	m.c = m.c.AliasedAs(alias)
	return m
}

func randInt() int64 {
	out := int64(new(maphash.Hash).Sum64())

	if out < 0 {
		return -out % 10000
	}

	return out % 10000
}
