// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// Customer is an object representing the database table.
type Customer struct {
	ID             int64               `db:"id,pk,autoincr" `
	Name           string              `db:"name" `
	Phone          null.Val[string]    `db:"phone" `
	Email          null.Val[string]    `db:"email" `
	MarketingOptIn null.Val[bool]      `db:"marketing_opt_in" `
	CreatedAt      null.Val[time.Time] `db:"created_at" `
	UpdatedAt      null.Val[time.Time] `db:"updated_at" `

	R customerR `db:"-" `
}

// CustomerSlice is an alias for a slice of pointers to Customer.
// This should almost always be used instead of []*Customer.
type CustomerSlice []*Customer

// Customers contains methods to work with the customers table
var Customers = mysql.NewTablex[*Customer, CustomerSlice, *CustomerSetter]("customers", buildCustomerColumns("customers"), []string{"id"})

// CustomersQuery is a query on the customers table
type CustomersQuery = *mysql.ViewQuery[*Customer, CustomerSlice]

// customerR is where relationships are stored.
type customerR struct {
	Orders OrderSlice // orders_ibfk_1
}

func buildCustomerColumns(alias string) customerColumns {
	return customerColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "phone", "email", "marketing_opt_in", "created_at", "updated_at",
		).WithParent("customers"),
		tableAlias:     alias,
		ID:             mysql.Quote(alias, "id"),
		Name:           mysql.Quote(alias, "name"),
		Phone:          mysql.Quote(alias, "phone"),
		Email:          mysql.Quote(alias, "email"),
		MarketingOptIn: mysql.Quote(alias, "marketing_opt_in"),
		CreatedAt:      mysql.Quote(alias, "created_at"),
		UpdatedAt:      mysql.Quote(alias, "updated_at"),
	}
}

type customerColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             mysql.Expression
	Name           mysql.Expression
	Phone          mysql.Expression
	Email          mysql.Expression
	MarketingOptIn mysql.Expression
	CreatedAt      mysql.Expression
	UpdatedAt      mysql.Expression
}

func (c customerColumns) Alias() string {
	return c.tableAlias
}

func (customerColumns) AliasedAs(alias string) customerColumns {
	return buildCustomerColumns(alias)
}

// CustomerSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CustomerSetter struct {
	ID             omit.Val[int64]         `db:"id,pk,autoincr" `
	Name           omit.Val[string]        `db:"name" `
	Phone          omitnull.Val[string]    `db:"phone" `
	Email          omitnull.Val[string]    `db:"email" `
	MarketingOptIn omitnull.Val[bool]      `db:"marketing_opt_in" `
	CreatedAt      omitnull.Val[time.Time] `db:"created_at" `
	UpdatedAt      omitnull.Val[time.Time] `db:"updated_at" `
}

func (s CustomerSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if !s.Phone.IsUnset() {
		vals = append(vals, "phone")
	}
	if !s.Email.IsUnset() {
		vals = append(vals, "email")
	}
	if !s.MarketingOptIn.IsUnset() {
		vals = append(vals, "marketing_opt_in")
	}
	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}
	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s CustomerSetter) Overwrite(t *Customer) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if !s.Phone.IsUnset() {
		t.Phone = s.Phone.MustGetNull()
	}
	if !s.Email.IsUnset() {
		t.Email = s.Email.MustGetNull()
	}
	if !s.MarketingOptIn.IsUnset() {
		t.MarketingOptIn = s.MarketingOptIn.MustGetNull()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt = s.CreatedAt.MustGetNull()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt = s.UpdatedAt.MustGetNull()
	}
}

func (s *CustomerSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Customers.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Name.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.Phone.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Phone.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.Email.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Email.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.MarketingOptIn.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.MarketingOptIn.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.CreatedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.UpdatedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}))
}

func (s CustomerSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("customers")...)
}

func (s CustomerSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	if !s.Phone.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "phone")...),
			mysql.Arg(s.Phone),
		}})
	}

	if !s.Email.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "email")...),
			mysql.Arg(s.Email),
		}})
	}

	if !s.MarketingOptIn.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "marketing_opt_in")...),
			mysql.Arg(s.MarketingOptIn),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindCustomer retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCustomer(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Customer, error) {
	if len(cols) == 0 {
		return Customers.Query(
			sm.Where(Customers.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Customers.Query(
		sm.Where(Customers.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(Customers.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CustomerExists checks the presence of a single record by primary key
func CustomerExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Customers.Query(
		sm.Where(Customers.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Customer is retrieved from the database
func (o *Customer) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Customers.AfterSelectHooks.RunHooks(ctx, exec, CustomerSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Customers.AfterInsertHooks.RunHooks(ctx, exec, CustomerSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Customers.AfterUpdateHooks.RunHooks(ctx, exec, CustomerSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Customers.AfterDeleteHooks.RunHooks(ctx, exec, CustomerSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Customer
func (o *Customer) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *Customer) pkEQ() dialect.Expression {
	return mysql.Quote("customers", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Customer
func (o *Customer) Update(ctx context.Context, exec bob.Executor, s *CustomerSetter) error {
	_, err := Customers.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single Customer record with an executor
func (o *Customer) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Customers.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Customer using the executor
func (o *Customer) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Customers.Query(
		sm.Where(Customers.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after CustomerSlice is retrieved from the database
func (o CustomerSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Customers.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Customers.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Customers.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Customers.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CustomerSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("customers", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CustomerSlice) copyMatchingRows(from ...*Customer) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CustomerSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Customers.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Customer:
				o.copyMatchingRows(retrieved)
			case []*Customer:
				o.copyMatchingRows(retrieved...)
			case CustomerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Customer or a slice of Customer
				// then run the AfterUpdateHooks on the slice
				_, err = Customers.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CustomerSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Customers.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Customer:
				o.copyMatchingRows(retrieved)
			case []*Customer:
				o.copyMatchingRows(retrieved...)
			case CustomerSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Customer or a slice of Customer
				// then run the AfterDeleteHooks on the slice
				_, err = Customers.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CustomerSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CustomerSetter) error {
	_, err := Customers.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o CustomerSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Customers.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CustomerSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Customers.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Orders starts a query for related objects on orders
func (o *Customer) Orders(mods ...bob.Mod[*dialect.SelectQuery]) OrdersQuery {
	return Orders.Query(append(mods,
		sm.Where(Orders.Columns.CustomerID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os CustomerSlice) Orders(mods ...bob.Mod[*dialect.SelectQuery]) OrdersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Orders.Query(append(mods,
		sm.Where(mysql.Group(Orders.Columns.CustomerID).OP("IN", PKArgExpr)),
	)...)
}

func insertCustomerOrders0(ctx context.Context, exec bob.Executor, orders1 []*OrderSetter, customer0 *Customer) (OrderSlice, error) {
	for i := range orders1 {
		orders1[i].CustomerID = omitnull.From(customer0.ID)
	}

	ret, err := Orders.Insert(bob.ToMods(orders1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCustomerOrders0: %w", err)
	}

	return ret, nil
}

func attachCustomerOrders0(ctx context.Context, exec bob.Executor, count int, orders1 OrderSlice, customer0 *Customer) (OrderSlice, error) {
	setter := &OrderSetter{
		CustomerID: omitnull.From(customer0.ID),
	}

	err := orders1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCustomerOrders0: %w", err)
	}

	return orders1, nil
}

func (customer0 *Customer) InsertOrders(ctx context.Context, exec bob.Executor, related ...*OrderSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	orders1, err := insertCustomerOrders0(ctx, exec, related, customer0)
	if err != nil {
		return err
	}

	customer0.R.Orders = append(customer0.R.Orders, orders1...)

	for _, rel := range orders1 {
		rel.R.Customer = customer0
	}
	return nil
}

func (customer0 *Customer) AttachOrders(ctx context.Context, exec bob.Executor, related ...*Order) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	orders1 := OrderSlice(related)

	_, err = attachCustomerOrders0(ctx, exec, len(related), orders1, customer0)
	if err != nil {
		return err
	}

	customer0.R.Orders = append(customer0.R.Orders, orders1...)

	for _, rel := range related {
		rel.R.Customer = customer0
	}

	return nil
}

type customerWhere[Q mysql.Filterable] struct {
	ID             mysql.WhereMod[Q, int64]
	Name           mysql.WhereMod[Q, string]
	Phone          mysql.WhereNullMod[Q, string]
	Email          mysql.WhereNullMod[Q, string]
	MarketingOptIn mysql.WhereNullMod[Q, bool]
	CreatedAt      mysql.WhereNullMod[Q, time.Time]
	UpdatedAt      mysql.WhereNullMod[Q, time.Time]
}

func (customerWhere[Q]) AliasedAs(alias string) customerWhere[Q] {
	return buildCustomerWhere[Q](buildCustomerColumns(alias))
}

func buildCustomerWhere[Q mysql.Filterable](cols customerColumns) customerWhere[Q] {
	return customerWhere[Q]{
		ID:             mysql.Where[Q, int64](cols.ID),
		Name:           mysql.Where[Q, string](cols.Name),
		Phone:          mysql.WhereNull[Q, string](cols.Phone),
		Email:          mysql.WhereNull[Q, string](cols.Email),
		MarketingOptIn: mysql.WhereNull[Q, bool](cols.MarketingOptIn),
		CreatedAt:      mysql.WhereNull[Q, time.Time](cols.CreatedAt),
		UpdatedAt:      mysql.WhereNull[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Customer) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Orders":
		rels, ok := retrieved.(OrderSlice)
		if !ok {
			return fmt.Errorf("customer cannot load %T as %q", retrieved, name)
		}

		o.R.Orders = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Customer = o
			}
		}
		return nil
	default:
		return fmt.Errorf("customer has no relationship %q", name)
	}
}

type customerPreloader struct{}

func buildCustomerPreloader() customerPreloader {
	return customerPreloader{}
}

type customerThenLoader[Q orm.Loadable] struct {
	Orders func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildCustomerThenLoader[Q orm.Loadable]() customerThenLoader[Q] {
	type OrdersLoadInterface interface {
		LoadOrders(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return customerThenLoader[Q]{
		Orders: thenLoadBuilder[Q](
			"Orders",
			func(ctx context.Context, exec bob.Executor, retrieved OrdersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrders(ctx, exec, mods...)
			},
		),
	}
}

// LoadOrders loads the customer's Orders into the .R struct
func (o *Customer) LoadOrders(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Orders = nil

	related, err := o.Orders(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Customer = o
	}

	o.R.Orders = related
	return nil
}

// LoadOrders loads the customer's Orders into the .R struct
func (os CustomerSlice) LoadOrders(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	orders, err := os.Orders(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Orders = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range orders {

			if !rel.CustomerID.IsValue() {
				continue
			}
			if !(rel.CustomerID.IsValue() && o.ID == rel.CustomerID.MustGet()) {
				continue
			}

			rel.R.Customer = o

			o.R.Orders = append(o.R.Orders, rel)
		}
	}

	return nil
}

type customerJoins[Q dialect.Joinable] struct {
	typ    string
	Orders modAs[Q, orderColumns]
}

func (j customerJoins[Q]) aliasedAs(alias string) customerJoins[Q] {
	return buildCustomerJoins[Q](buildCustomerColumns(alias), j.typ)
}

func buildCustomerJoins[Q dialect.Joinable](cols customerColumns, typ string) customerJoins[Q] {
	return customerJoins[Q]{
		typ: typ,
		Orders: modAs[Q, orderColumns]{
			c: Orders.Columns,
			f: func(to orderColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Orders.Name().As(to.Alias())).On(
						to.CustomerID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
