// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
)

// DimDate is an object representing the database table.
type DimDate struct {
	Date        time.Time `db:"date,pk" `
	Month       int32     `db:"month" `
	Year        int32     `db:"year" `
	Quarter     int32     `db:"quarter" `
	DayOfWeek   int32     `db:"day_of_week" `
	DayOfMonth  int32     `db:"day_of_month" `
	DayOfYear   int32     `db:"day_of_year" `
	WeekOfYear  int32     `db:"week_of_year" `
	WeekOfMonth int32     `db:"week_of_month" `
}

// DimDateSlice is an alias for a slice of pointers to DimDate.
// This should almost always be used instead of []*DimDate.
type DimDateSlice []*DimDate

// DimDates contains methods to work with the dim_date table
var DimDates = mysql.NewTablex[*DimDate, DimDateSlice, *DimDateSetter]("dim_date", buildDimDateColumns("dim_date"), []string{"date"})

// DimDatesQuery is a query on the dim_date table
type DimDatesQuery = *mysql.ViewQuery[*DimDate, DimDateSlice]

func buildDimDateColumns(alias string) dimDateColumns {
	return dimDateColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"date", "month", "year", "quarter", "day_of_week", "day_of_month", "day_of_year", "week_of_year", "week_of_month",
		).WithParent("dim_date"),
		tableAlias:  alias,
		Date:        mysql.Quote(alias, "date"),
		Month:       mysql.Quote(alias, "month"),
		Year:        mysql.Quote(alias, "year"),
		Quarter:     mysql.Quote(alias, "quarter"),
		DayOfWeek:   mysql.Quote(alias, "day_of_week"),
		DayOfMonth:  mysql.Quote(alias, "day_of_month"),
		DayOfYear:   mysql.Quote(alias, "day_of_year"),
		WeekOfYear:  mysql.Quote(alias, "week_of_year"),
		WeekOfMonth: mysql.Quote(alias, "week_of_month"),
	}
}

type dimDateColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	Date        mysql.Expression
	Month       mysql.Expression
	Year        mysql.Expression
	Quarter     mysql.Expression
	DayOfWeek   mysql.Expression
	DayOfMonth  mysql.Expression
	DayOfYear   mysql.Expression
	WeekOfYear  mysql.Expression
	WeekOfMonth mysql.Expression
}

func (c dimDateColumns) Alias() string {
	return c.tableAlias
}

func (dimDateColumns) AliasedAs(alias string) dimDateColumns {
	return buildDimDateColumns(alias)
}

// DimDateSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type DimDateSetter struct {
	Date        omit.Val[time.Time] `db:"date,pk" `
	Month       omit.Val[int32]     `db:"month" `
	Year        omit.Val[int32]     `db:"year" `
	Quarter     omit.Val[int32]     `db:"quarter" `
	DayOfWeek   omit.Val[int32]     `db:"day_of_week" `
	DayOfMonth  omit.Val[int32]     `db:"day_of_month" `
	DayOfYear   omit.Val[int32]     `db:"day_of_year" `
	WeekOfYear  omit.Val[int32]     `db:"week_of_year" `
	WeekOfMonth omit.Val[int32]     `db:"week_of_month" `
}

func (s DimDateSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.Date.IsValue() {
		vals = append(vals, "date")
	}
	if s.Month.IsValue() {
		vals = append(vals, "month")
	}
	if s.Year.IsValue() {
		vals = append(vals, "year")
	}
	if s.Quarter.IsValue() {
		vals = append(vals, "quarter")
	}
	if s.DayOfWeek.IsValue() {
		vals = append(vals, "day_of_week")
	}
	if s.DayOfMonth.IsValue() {
		vals = append(vals, "day_of_month")
	}
	if s.DayOfYear.IsValue() {
		vals = append(vals, "day_of_year")
	}
	if s.WeekOfYear.IsValue() {
		vals = append(vals, "week_of_year")
	}
	if s.WeekOfMonth.IsValue() {
		vals = append(vals, "week_of_month")
	}
	return vals
}

func (s DimDateSetter) Overwrite(t *DimDate) {
	if s.Date.IsValue() {
		t.Date = s.Date.MustGet()
	}
	if s.Month.IsValue() {
		t.Month = s.Month.MustGet()
	}
	if s.Year.IsValue() {
		t.Year = s.Year.MustGet()
	}
	if s.Quarter.IsValue() {
		t.Quarter = s.Quarter.MustGet()
	}
	if s.DayOfWeek.IsValue() {
		t.DayOfWeek = s.DayOfWeek.MustGet()
	}
	if s.DayOfMonth.IsValue() {
		t.DayOfMonth = s.DayOfMonth.MustGet()
	}
	if s.DayOfYear.IsValue() {
		t.DayOfYear = s.DayOfYear.MustGet()
	}
	if s.WeekOfYear.IsValue() {
		t.WeekOfYear = s.WeekOfYear.MustGet()
	}
	if s.WeekOfMonth.IsValue() {
		t.WeekOfMonth = s.WeekOfMonth.MustGet()
	}
}

func (s *DimDateSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return DimDates.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Date.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Date.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Month.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Month.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Year.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Year.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Quarter.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Quarter.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.DayOfWeek.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.DayOfWeek.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.DayOfMonth.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.DayOfMonth.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.DayOfYear.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.DayOfYear.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.WeekOfYear.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.WeekOfYear.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.WeekOfMonth.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.WeekOfMonth.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s DimDateSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("dim_date")...)
}

func (s DimDateSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.Date.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "date")...),
			mysql.Arg(s.Date),
		}})
	}

	if s.Month.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "month")...),
			mysql.Arg(s.Month),
		}})
	}

	if s.Year.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "year")...),
			mysql.Arg(s.Year),
		}})
	}

	if s.Quarter.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "quarter")...),
			mysql.Arg(s.Quarter),
		}})
	}

	if s.DayOfWeek.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "day_of_week")...),
			mysql.Arg(s.DayOfWeek),
		}})
	}

	if s.DayOfMonth.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "day_of_month")...),
			mysql.Arg(s.DayOfMonth),
		}})
	}

	if s.DayOfYear.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "day_of_year")...),
			mysql.Arg(s.DayOfYear),
		}})
	}

	if s.WeekOfYear.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "week_of_year")...),
			mysql.Arg(s.WeekOfYear),
		}})
	}

	if s.WeekOfMonth.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "week_of_month")...),
			mysql.Arg(s.WeekOfMonth),
		}})
	}

	return exprs
}

// FindDimDate retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindDimDate(ctx context.Context, exec bob.Executor, DatePK time.Time, cols ...string) (*DimDate, error) {
	if len(cols) == 0 {
		return DimDates.Query(
			sm.Where(DimDates.Columns.Date.EQ(mysql.Arg(DatePK))),
		).One(ctx, exec)
	}

	return DimDates.Query(
		sm.Where(DimDates.Columns.Date.EQ(mysql.Arg(DatePK))),
		sm.Columns(DimDates.Columns.Only(cols...)),
	).One(ctx, exec)
}

// DimDateExists checks the presence of a single record by primary key
func DimDateExists(ctx context.Context, exec bob.Executor, DatePK time.Time) (bool, error) {
	return DimDates.Query(
		sm.Where(DimDates.Columns.Date.EQ(mysql.Arg(DatePK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after DimDate is retrieved from the database
func (o *DimDate) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = DimDates.AfterSelectHooks.RunHooks(ctx, exec, DimDateSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = DimDates.AfterInsertHooks.RunHooks(ctx, exec, DimDateSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = DimDates.AfterUpdateHooks.RunHooks(ctx, exec, DimDateSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = DimDates.AfterDeleteHooks.RunHooks(ctx, exec, DimDateSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the DimDate
func (o *DimDate) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.Date)
}

func (o *DimDate) pkEQ() dialect.Expression {
	return mysql.Quote("dim_date", "date").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the DimDate
func (o *DimDate) Update(ctx context.Context, exec bob.Executor, s *DimDateSetter) error {
	_, err := DimDates.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single DimDate record with an executor
func (o *DimDate) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := DimDates.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the DimDate using the executor
func (o *DimDate) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := DimDates.Query(
		sm.Where(DimDates.Columns.Date.EQ(mysql.Arg(o.Date))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after DimDateSlice is retrieved from the database
func (o DimDateSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = DimDates.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = DimDates.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = DimDates.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = DimDates.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o DimDateSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("dim_date", "date").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o DimDateSlice) copyMatchingRows(from ...*DimDate) {
	for i, old := range o {
		for _, new := range from {
			if new.Date.Equal(old.Date) {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o DimDateSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return DimDates.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *DimDate:
				o.copyMatchingRows(retrieved)
			case []*DimDate:
				o.copyMatchingRows(retrieved...)
			case DimDateSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a DimDate or a slice of DimDate
				// then run the AfterUpdateHooks on the slice
				_, err = DimDates.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o DimDateSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return DimDates.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *DimDate:
				o.copyMatchingRows(retrieved)
			case []*DimDate:
				o.copyMatchingRows(retrieved...)
			case DimDateSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a DimDate or a slice of DimDate
				// then run the AfterDeleteHooks on the slice
				_, err = DimDates.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o DimDateSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals DimDateSetter) error {
	_, err := DimDates.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o DimDateSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := DimDates.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o DimDateSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := DimDates.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type dimDateWhere[Q mysql.Filterable] struct {
	Date        mysql.WhereMod[Q, time.Time]
	Month       mysql.WhereMod[Q, int32]
	Year        mysql.WhereMod[Q, int32]
	Quarter     mysql.WhereMod[Q, int32]
	DayOfWeek   mysql.WhereMod[Q, int32]
	DayOfMonth  mysql.WhereMod[Q, int32]
	DayOfYear   mysql.WhereMod[Q, int32]
	WeekOfYear  mysql.WhereMod[Q, int32]
	WeekOfMonth mysql.WhereMod[Q, int32]
}

func (dimDateWhere[Q]) AliasedAs(alias string) dimDateWhere[Q] {
	return buildDimDateWhere[Q](buildDimDateColumns(alias))
}

func buildDimDateWhere[Q mysql.Filterable](cols dimDateColumns) dimDateWhere[Q] {
	return dimDateWhere[Q]{
		Date:        mysql.Where[Q, time.Time](cols.Date),
		Month:       mysql.Where[Q, int32](cols.Month),
		Year:        mysql.Where[Q, int32](cols.Year),
		Quarter:     mysql.Where[Q, int32](cols.Quarter),
		DayOfWeek:   mysql.Where[Q, int32](cols.DayOfWeek),
		DayOfMonth:  mysql.Where[Q, int32](cols.DayOfMonth),
		DayOfYear:   mysql.Where[Q, int32](cols.DayOfYear),
		WeekOfYear:  mysql.Where[Q, int32](cols.WeekOfYear),
		WeekOfMonth: mysql.Where[Q, int32](cols.WeekOfMonth),
	}
}
