// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/expr"
)

// ItemSummary is an object representing the database table.
type ItemSummary struct {
	ID             null.Val[int64]           `db:"id" `
	Name           string                    `db:"name" `
	Category       string                    `db:"category" `
	OrderType      string                    `db:"order_type" `
	DateOOrderDate null.Val[time.Time]       `db:"date(o.order_date)" `
	TotalQuantity  null.Val[decimal.Decimal] `db:"total_quantity" `
	TotalSales     null.Val[decimal.Decimal] `db:"total_sales" `
	OrderCount     int64                     `db:"order_count" `
	LocationID     null.Val[int64]           `db:"location_id" `
}

// ItemSummarySlice is an alias for a slice of pointers to ItemSummary.
// This should almost always be used instead of []*ItemSummary.
type ItemSummarySlice []*ItemSummary

// ItemSummaries contains methods to work with the item_summaries view
var ItemSummaries = mysql.NewViewx[*ItemSummary, ItemSummarySlice]("item_summaries", buildItemSummaryColumns("item_summaries"))

// ItemSummariesQuery is a query on the item_summaries view
type ItemSummariesQuery = *mysql.ViewQuery[*ItemSummary, ItemSummarySlice]

func buildItemSummaryColumns(alias string) itemSummaryColumns {
	return itemSummaryColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "category", "order_type", "date(o.order_date)", "total_quantity", "total_sales", "order_count", "location_id",
		).WithParent("item_summaries"),
		tableAlias:     alias,
		ID:             mysql.Quote(alias, "id"),
		Name:           mysql.Quote(alias, "name"),
		Category:       mysql.Quote(alias, "category"),
		OrderType:      mysql.Quote(alias, "order_type"),
		DateOOrderDate: mysql.Quote(alias, "date(o.order_date)"),
		TotalQuantity:  mysql.Quote(alias, "total_quantity"),
		TotalSales:     mysql.Quote(alias, "total_sales"),
		OrderCount:     mysql.Quote(alias, "order_count"),
		LocationID:     mysql.Quote(alias, "location_id"),
	}
}

type itemSummaryColumns struct {
	expr.ColumnsExpr
	tableAlias     string
	ID             mysql.Expression
	Name           mysql.Expression
	Category       mysql.Expression
	OrderType      mysql.Expression
	DateOOrderDate mysql.Expression
	TotalQuantity  mysql.Expression
	TotalSales     mysql.Expression
	OrderCount     mysql.Expression
	LocationID     mysql.Expression
}

func (c itemSummaryColumns) Alias() string {
	return c.tableAlias
}

func (itemSummaryColumns) AliasedAs(alias string) itemSummaryColumns {
	return buildItemSummaryColumns(alias)
}

// AfterQueryHook is called after ItemSummary is retrieved from the database
func (o *ItemSummary) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ItemSummaries.AfterSelectHooks.RunHooks(ctx, exec, ItemSummarySlice{o})
	}

	return err
}

// AfterQueryHook is called after ItemSummarySlice is retrieved from the database
func (o ItemSummarySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ItemSummaries.AfterSelectHooks.RunHooks(ctx, exec, o)
	}

	return err
}

type itemSummaryWhere[Q mysql.Filterable] struct {
	ID             mysql.WhereNullMod[Q, int64]
	Name           mysql.WhereMod[Q, string]
	Category       mysql.WhereMod[Q, string]
	OrderType      mysql.WhereMod[Q, string]
	DateOOrderDate mysql.WhereNullMod[Q, time.Time]
	TotalQuantity  mysql.WhereNullMod[Q, decimal.Decimal]
	TotalSales     mysql.WhereNullMod[Q, decimal.Decimal]
	OrderCount     mysql.WhereMod[Q, int64]
	LocationID     mysql.WhereNullMod[Q, int64]
}

func (itemSummaryWhere[Q]) AliasedAs(alias string) itemSummaryWhere[Q] {
	return buildItemSummaryWhere[Q](buildItemSummaryColumns(alias))
}

func buildItemSummaryWhere[Q mysql.Filterable](cols itemSummaryColumns) itemSummaryWhere[Q] {
	return itemSummaryWhere[Q]{
		ID:             mysql.WhereNull[Q, int64](cols.ID),
		Name:           mysql.Where[Q, string](cols.Name),
		Category:       mysql.Where[Q, string](cols.Category),
		OrderType:      mysql.Where[Q, string](cols.OrderType),
		DateOOrderDate: mysql.WhereNull[Q, time.Time](cols.DateOOrderDate),
		TotalQuantity:  mysql.WhereNull[Q, decimal.Decimal](cols.TotalQuantity),
		TotalSales:     mysql.WhereNull[Q, decimal.Decimal](cols.TotalSales),
		OrderCount:     mysql.Where[Q, int64](cols.OrderCount),
		LocationID:     mysql.WhereNull[Q, int64](cols.LocationID),
	}
}
