// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// Location is an object representing the database table.
type Location struct {
	ID        int64               `db:"id,pk,autoincr" `
	Name      string              `db:"name" `
	Address   string              `db:"address" `
	City      string              `db:"city" `
	State     string              `db:"state" `
	Zip       string              `db:"zip" `
	TaxRate   decimal.Decimal     `db:"tax_rate" `
	CreatedAt null.Val[time.Time] `db:"created_at" `
	UpdatedAt null.Val[time.Time] `db:"updated_at" `

	R locationR `db:"-" `
}

// LocationSlice is an alias for a slice of pointers to Location.
// This should almost always be used instead of []*Location.
type LocationSlice []*Location

// Locations contains methods to work with the locations table
var Locations = mysql.NewTablex[*Location, LocationSlice, *LocationSetter]("locations", buildLocationColumns("locations"), []string{"id"}, []string{"name"})

// LocationsQuery is a query on the locations table
type LocationsQuery = *mysql.ViewQuery[*Location, LocationSlice]

// locationR is where relationships are stored.
type locationR struct {
	JoinLocationCustomers CustomerSlice // customers_ibfk_1
	LastLocationCustomers CustomerSlice // customers_ibfk_2
	Orders                OrderSlice    // orders_ibfk_3
}

func buildLocationColumns(alias string) locationColumns {
	return locationColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "address", "city", "state", "zip", "tax_rate", "created_at", "updated_at",
		).WithParent("locations"),
		tableAlias: alias,
		ID:         mysql.Quote(alias, "id"),
		Name:       mysql.Quote(alias, "name"),
		Address:    mysql.Quote(alias, "address"),
		City:       mysql.Quote(alias, "city"),
		State:      mysql.Quote(alias, "state"),
		Zip:        mysql.Quote(alias, "zip"),
		TaxRate:    mysql.Quote(alias, "tax_rate"),
		CreatedAt:  mysql.Quote(alias, "created_at"),
		UpdatedAt:  mysql.Quote(alias, "updated_at"),
	}
}

type locationColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         mysql.Expression
	Name       mysql.Expression
	Address    mysql.Expression
	City       mysql.Expression
	State      mysql.Expression
	Zip        mysql.Expression
	TaxRate    mysql.Expression
	CreatedAt  mysql.Expression
	UpdatedAt  mysql.Expression
}

func (c locationColumns) Alias() string {
	return c.tableAlias
}

func (locationColumns) AliasedAs(alias string) locationColumns {
	return buildLocationColumns(alias)
}

// LocationSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type LocationSetter struct {
	ID        omit.Val[int64]           `db:"id,pk,autoincr" `
	Name      omit.Val[string]          `db:"name" `
	Address   omit.Val[string]          `db:"address" `
	City      omit.Val[string]          `db:"city" `
	State     omit.Val[string]          `db:"state" `
	Zip       omit.Val[string]          `db:"zip" `
	TaxRate   omit.Val[decimal.Decimal] `db:"tax_rate" `
	CreatedAt omitnull.Val[time.Time]   `db:"created_at" `
	UpdatedAt omitnull.Val[time.Time]   `db:"updated_at" `
}

func (s LocationSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Address.IsValue() {
		vals = append(vals, "address")
	}
	if s.City.IsValue() {
		vals = append(vals, "city")
	}
	if s.State.IsValue() {
		vals = append(vals, "state")
	}
	if s.Zip.IsValue() {
		vals = append(vals, "zip")
	}
	if s.TaxRate.IsValue() {
		vals = append(vals, "tax_rate")
	}
	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}
	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s LocationSetter) Overwrite(t *Location) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Address.IsValue() {
		t.Address = s.Address.MustGet()
	}
	if s.City.IsValue() {
		t.City = s.City.MustGet()
	}
	if s.State.IsValue() {
		t.State = s.State.MustGet()
	}
	if s.Zip.IsValue() {
		t.Zip = s.Zip.MustGet()
	}
	if s.TaxRate.IsValue() {
		t.TaxRate = s.TaxRate.MustGet()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt = s.CreatedAt.MustGetNull()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt = s.UpdatedAt.MustGetNull()
	}
}

func (s *LocationSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Locations.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Name.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Address.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Address.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.City.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.City.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.State.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.State.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Zip.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Zip.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.TaxRate.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.TaxRate.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.CreatedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.UpdatedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}))
}

func (s LocationSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("locations")...)
}

func (s LocationSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	if s.Address.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "address")...),
			mysql.Arg(s.Address),
		}})
	}

	if s.City.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "city")...),
			mysql.Arg(s.City),
		}})
	}

	if s.State.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "state")...),
			mysql.Arg(s.State),
		}})
	}

	if s.Zip.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "zip")...),
			mysql.Arg(s.Zip),
		}})
	}

	if s.TaxRate.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "tax_rate")...),
			mysql.Arg(s.TaxRate),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindLocation retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindLocation(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Location, error) {
	if len(cols) == 0 {
		return Locations.Query(
			sm.Where(Locations.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Locations.Query(
		sm.Where(Locations.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(Locations.Columns.Only(cols...)),
	).One(ctx, exec)
}

// LocationExists checks the presence of a single record by primary key
func LocationExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Locations.Query(
		sm.Where(Locations.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Location is retrieved from the database
func (o *Location) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Locations.AfterSelectHooks.RunHooks(ctx, exec, LocationSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Locations.AfterInsertHooks.RunHooks(ctx, exec, LocationSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Locations.AfterUpdateHooks.RunHooks(ctx, exec, LocationSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Locations.AfterDeleteHooks.RunHooks(ctx, exec, LocationSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Location
func (o *Location) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *Location) pkEQ() dialect.Expression {
	return mysql.Quote("locations", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Location
func (o *Location) Update(ctx context.Context, exec bob.Executor, s *LocationSetter) error {
	_, err := Locations.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single Location record with an executor
func (o *Location) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Locations.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Location using the executor
func (o *Location) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Locations.Query(
		sm.Where(Locations.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after LocationSlice is retrieved from the database
func (o LocationSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Locations.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Locations.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Locations.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Locations.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o LocationSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("locations", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o LocationSlice) copyMatchingRows(from ...*Location) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o LocationSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Locations.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Location:
				o.copyMatchingRows(retrieved)
			case []*Location:
				o.copyMatchingRows(retrieved...)
			case LocationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Location or a slice of Location
				// then run the AfterUpdateHooks on the slice
				_, err = Locations.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o LocationSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Locations.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Location:
				o.copyMatchingRows(retrieved)
			case []*Location:
				o.copyMatchingRows(retrieved...)
			case LocationSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Location or a slice of Location
				// then run the AfterDeleteHooks on the slice
				_, err = Locations.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o LocationSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals LocationSetter) error {
	_, err := Locations.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o LocationSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Locations.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o LocationSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Locations.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// JoinLocationCustomers starts a query for related objects on customers
func (o *Location) JoinLocationCustomers(mods ...bob.Mod[*dialect.SelectQuery]) CustomersQuery {
	return Customers.Query(append(mods,
		sm.Where(Customers.Columns.JoinLocationID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os LocationSlice) JoinLocationCustomers(mods ...bob.Mod[*dialect.SelectQuery]) CustomersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Customers.Query(append(mods,
		sm.Where(mysql.Group(Customers.Columns.JoinLocationID).OP("IN", PKArgExpr)),
	)...)
}

// LastLocationCustomers starts a query for related objects on customers
func (o *Location) LastLocationCustomers(mods ...bob.Mod[*dialect.SelectQuery]) CustomersQuery {
	return Customers.Query(append(mods,
		sm.Where(Customers.Columns.LastLocationID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os LocationSlice) LastLocationCustomers(mods ...bob.Mod[*dialect.SelectQuery]) CustomersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Customers.Query(append(mods,
		sm.Where(mysql.Group(Customers.Columns.LastLocationID).OP("IN", PKArgExpr)),
	)...)
}

// Orders starts a query for related objects on orders
func (o *Location) Orders(mods ...bob.Mod[*dialect.SelectQuery]) OrdersQuery {
	return Orders.Query(append(mods,
		sm.Where(Orders.Columns.LocationID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os LocationSlice) Orders(mods ...bob.Mod[*dialect.SelectQuery]) OrdersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Orders.Query(append(mods,
		sm.Where(mysql.Group(Orders.Columns.LocationID).OP("IN", PKArgExpr)),
	)...)
}

func insertLocationJoinLocationCustomers0(ctx context.Context, exec bob.Executor, customers1 []*CustomerSetter, location0 *Location) (CustomerSlice, error) {
	for i := range customers1 {
		customers1[i].JoinLocationID = omitnull.From(location0.ID)
	}

	ret, err := Customers.Insert(bob.ToMods(customers1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertLocationJoinLocationCustomers0: %w", err)
	}

	return ret, nil
}

func attachLocationJoinLocationCustomers0(ctx context.Context, exec bob.Executor, count int, customers1 CustomerSlice, location0 *Location) (CustomerSlice, error) {
	setter := &CustomerSetter{
		JoinLocationID: omitnull.From(location0.ID),
	}

	err := customers1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachLocationJoinLocationCustomers0: %w", err)
	}

	return customers1, nil
}

func (location0 *Location) InsertJoinLocationCustomers(ctx context.Context, exec bob.Executor, related ...*CustomerSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	customers1, err := insertLocationJoinLocationCustomers0(ctx, exec, related, location0)
	if err != nil {
		return err
	}

	location0.R.JoinLocationCustomers = append(location0.R.JoinLocationCustomers, customers1...)

	for _, rel := range customers1 {
		rel.R.JoinLocationLocation = location0
	}
	return nil
}

func (location0 *Location) AttachJoinLocationCustomers(ctx context.Context, exec bob.Executor, related ...*Customer) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	customers1 := CustomerSlice(related)

	_, err = attachLocationJoinLocationCustomers0(ctx, exec, len(related), customers1, location0)
	if err != nil {
		return err
	}

	location0.R.JoinLocationCustomers = append(location0.R.JoinLocationCustomers, customers1...)

	for _, rel := range related {
		rel.R.JoinLocationLocation = location0
	}

	return nil
}

func insertLocationLastLocationCustomers0(ctx context.Context, exec bob.Executor, customers1 []*CustomerSetter, location0 *Location) (CustomerSlice, error) {
	for i := range customers1 {
		customers1[i].LastLocationID = omitnull.From(location0.ID)
	}

	ret, err := Customers.Insert(bob.ToMods(customers1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertLocationLastLocationCustomers0: %w", err)
	}

	return ret, nil
}

func attachLocationLastLocationCustomers0(ctx context.Context, exec bob.Executor, count int, customers1 CustomerSlice, location0 *Location) (CustomerSlice, error) {
	setter := &CustomerSetter{
		LastLocationID: omitnull.From(location0.ID),
	}

	err := customers1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachLocationLastLocationCustomers0: %w", err)
	}

	return customers1, nil
}

func (location0 *Location) InsertLastLocationCustomers(ctx context.Context, exec bob.Executor, related ...*CustomerSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	customers1, err := insertLocationLastLocationCustomers0(ctx, exec, related, location0)
	if err != nil {
		return err
	}

	location0.R.LastLocationCustomers = append(location0.R.LastLocationCustomers, customers1...)

	for _, rel := range customers1 {
		rel.R.LastLocationLocation = location0
	}
	return nil
}

func (location0 *Location) AttachLastLocationCustomers(ctx context.Context, exec bob.Executor, related ...*Customer) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	customers1 := CustomerSlice(related)

	_, err = attachLocationLastLocationCustomers0(ctx, exec, len(related), customers1, location0)
	if err != nil {
		return err
	}

	location0.R.LastLocationCustomers = append(location0.R.LastLocationCustomers, customers1...)

	for _, rel := range related {
		rel.R.LastLocationLocation = location0
	}

	return nil
}

func insertLocationOrders0(ctx context.Context, exec bob.Executor, orders1 []*OrderSetter, location0 *Location) (OrderSlice, error) {
	for i := range orders1 {
		orders1[i].LocationID = omitnull.From(location0.ID)
	}

	ret, err := Orders.Insert(bob.ToMods(orders1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertLocationOrders0: %w", err)
	}

	return ret, nil
}

func attachLocationOrders0(ctx context.Context, exec bob.Executor, count int, orders1 OrderSlice, location0 *Location) (OrderSlice, error) {
	setter := &OrderSetter{
		LocationID: omitnull.From(location0.ID),
	}

	err := orders1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachLocationOrders0: %w", err)
	}

	return orders1, nil
}

func (location0 *Location) InsertOrders(ctx context.Context, exec bob.Executor, related ...*OrderSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	orders1, err := insertLocationOrders0(ctx, exec, related, location0)
	if err != nil {
		return err
	}

	location0.R.Orders = append(location0.R.Orders, orders1...)

	for _, rel := range orders1 {
		rel.R.Location = location0
	}
	return nil
}

func (location0 *Location) AttachOrders(ctx context.Context, exec bob.Executor, related ...*Order) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	orders1 := OrderSlice(related)

	_, err = attachLocationOrders0(ctx, exec, len(related), orders1, location0)
	if err != nil {
		return err
	}

	location0.R.Orders = append(location0.R.Orders, orders1...)

	for _, rel := range related {
		rel.R.Location = location0
	}

	return nil
}

type locationWhere[Q mysql.Filterable] struct {
	ID        mysql.WhereMod[Q, int64]
	Name      mysql.WhereMod[Q, string]
	Address   mysql.WhereMod[Q, string]
	City      mysql.WhereMod[Q, string]
	State     mysql.WhereMod[Q, string]
	Zip       mysql.WhereMod[Q, string]
	TaxRate   mysql.WhereMod[Q, decimal.Decimal]
	CreatedAt mysql.WhereNullMod[Q, time.Time]
	UpdatedAt mysql.WhereNullMod[Q, time.Time]
}

func (locationWhere[Q]) AliasedAs(alias string) locationWhere[Q] {
	return buildLocationWhere[Q](buildLocationColumns(alias))
}

func buildLocationWhere[Q mysql.Filterable](cols locationColumns) locationWhere[Q] {
	return locationWhere[Q]{
		ID:        mysql.Where[Q, int64](cols.ID),
		Name:      mysql.Where[Q, string](cols.Name),
		Address:   mysql.Where[Q, string](cols.Address),
		City:      mysql.Where[Q, string](cols.City),
		State:     mysql.Where[Q, string](cols.State),
		Zip:       mysql.Where[Q, string](cols.Zip),
		TaxRate:   mysql.Where[Q, decimal.Decimal](cols.TaxRate),
		CreatedAt: mysql.WhereNull[Q, time.Time](cols.CreatedAt),
		UpdatedAt: mysql.WhereNull[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Location) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "JoinLocationCustomers":
		rels, ok := retrieved.(CustomerSlice)
		if !ok {
			return fmt.Errorf("location cannot load %T as %q", retrieved, name)
		}

		o.R.JoinLocationCustomers = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.JoinLocationLocation = o
			}
		}
		return nil
	case "LastLocationCustomers":
		rels, ok := retrieved.(CustomerSlice)
		if !ok {
			return fmt.Errorf("location cannot load %T as %q", retrieved, name)
		}

		o.R.LastLocationCustomers = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.LastLocationLocation = o
			}
		}
		return nil
	case "Orders":
		rels, ok := retrieved.(OrderSlice)
		if !ok {
			return fmt.Errorf("location cannot load %T as %q", retrieved, name)
		}

		o.R.Orders = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Location = o
			}
		}
		return nil
	default:
		return fmt.Errorf("location has no relationship %q", name)
	}
}

type locationPreloader struct{}

func buildLocationPreloader() locationPreloader {
	return locationPreloader{}
}

type locationThenLoader[Q orm.Loadable] struct {
	JoinLocationCustomers func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	LastLocationCustomers func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Orders                func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildLocationThenLoader[Q orm.Loadable]() locationThenLoader[Q] {
	type JoinLocationCustomersLoadInterface interface {
		LoadJoinLocationCustomers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type LastLocationCustomersLoadInterface interface {
		LoadLastLocationCustomers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type OrdersLoadInterface interface {
		LoadOrders(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return locationThenLoader[Q]{
		JoinLocationCustomers: thenLoadBuilder[Q](
			"JoinLocationCustomers",
			func(ctx context.Context, exec bob.Executor, retrieved JoinLocationCustomersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadJoinLocationCustomers(ctx, exec, mods...)
			},
		),
		LastLocationCustomers: thenLoadBuilder[Q](
			"LastLocationCustomers",
			func(ctx context.Context, exec bob.Executor, retrieved LastLocationCustomersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadLastLocationCustomers(ctx, exec, mods...)
			},
		),
		Orders: thenLoadBuilder[Q](
			"Orders",
			func(ctx context.Context, exec bob.Executor, retrieved OrdersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrders(ctx, exec, mods...)
			},
		),
	}
}

// LoadJoinLocationCustomers loads the location's JoinLocationCustomers into the .R struct
func (o *Location) LoadJoinLocationCustomers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.JoinLocationCustomers = nil

	related, err := o.JoinLocationCustomers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.JoinLocationLocation = o
	}

	o.R.JoinLocationCustomers = related
	return nil
}

// LoadJoinLocationCustomers loads the location's JoinLocationCustomers into the .R struct
func (os LocationSlice) LoadJoinLocationCustomers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	customers, err := os.JoinLocationCustomers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.JoinLocationCustomers = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range customers {

			if !rel.JoinLocationID.IsValue() {
				continue
			}
			if !(rel.JoinLocationID.IsValue() && o.ID == rel.JoinLocationID.MustGet()) {
				continue
			}

			rel.R.JoinLocationLocation = o

			o.R.JoinLocationCustomers = append(o.R.JoinLocationCustomers, rel)
		}
	}

	return nil
}

// LoadLastLocationCustomers loads the location's LastLocationCustomers into the .R struct
func (o *Location) LoadLastLocationCustomers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.LastLocationCustomers = nil

	related, err := o.LastLocationCustomers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.LastLocationLocation = o
	}

	o.R.LastLocationCustomers = related
	return nil
}

// LoadLastLocationCustomers loads the location's LastLocationCustomers into the .R struct
func (os LocationSlice) LoadLastLocationCustomers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	customers, err := os.LastLocationCustomers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.LastLocationCustomers = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range customers {

			if !rel.LastLocationID.IsValue() {
				continue
			}
			if !(rel.LastLocationID.IsValue() && o.ID == rel.LastLocationID.MustGet()) {
				continue
			}

			rel.R.LastLocationLocation = o

			o.R.LastLocationCustomers = append(o.R.LastLocationCustomers, rel)
		}
	}

	return nil
}

// LoadOrders loads the location's Orders into the .R struct
func (o *Location) LoadOrders(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Orders = nil

	related, err := o.Orders(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Location = o
	}

	o.R.Orders = related
	return nil
}

// LoadOrders loads the location's Orders into the .R struct
func (os LocationSlice) LoadOrders(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	orders, err := os.Orders(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Orders = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range orders {

			if !rel.LocationID.IsValue() {
				continue
			}
			if !(rel.LocationID.IsValue() && o.ID == rel.LocationID.MustGet()) {
				continue
			}

			rel.R.Location = o

			o.R.Orders = append(o.R.Orders, rel)
		}
	}

	return nil
}

type locationJoins[Q dialect.Joinable] struct {
	typ                   string
	JoinLocationCustomers modAs[Q, customerColumns]
	LastLocationCustomers modAs[Q, customerColumns]
	Orders                modAs[Q, orderColumns]
}

func (j locationJoins[Q]) aliasedAs(alias string) locationJoins[Q] {
	return buildLocationJoins[Q](buildLocationColumns(alias), j.typ)
}

func buildLocationJoins[Q dialect.Joinable](cols locationColumns, typ string) locationJoins[Q] {
	return locationJoins[Q]{
		typ: typ,
		JoinLocationCustomers: modAs[Q, customerColumns]{
			c: Customers.Columns,
			f: func(to customerColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Customers.Name().As(to.Alias())).On(
						to.JoinLocationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		LastLocationCustomers: modAs[Q, customerColumns]{
			c: Customers.Columns,
			f: func(to customerColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Customers.Name().As(to.Alias())).On(
						to.LastLocationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Orders: modAs[Q, orderColumns]{
			c: Orders.Columns,
			f: func(to orderColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Orders.Name().As(to.Alias())).On(
						to.LocationID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
