// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types"
)

// OrderPayment is an object representing the database table.
type OrderPayment struct {
	ID          int64                                 `db:"id,pk,autoincr" `
	OrderID     int64                                 `db:"order_id" `
	PaymentType string                                `db:"payment_type" `
	Amount      decimal.Decimal                       `db:"amount" `
	PaymentInfo null.Val[types.JSON[json.RawMessage]] `db:"payment_info" `
	CreatedAt   null.Val[time.Time]                   `db:"created_at" `
	UpdatedAt   null.Val[time.Time]                   `db:"updated_at" `

	R orderPaymentR `db:"-" `
}

// OrderPaymentSlice is an alias for a slice of pointers to OrderPayment.
// This should almost always be used instead of []*OrderPayment.
type OrderPaymentSlice []*OrderPayment

// OrderPayments contains methods to work with the order_payments table
var OrderPayments = mysql.NewTablex[*OrderPayment, OrderPaymentSlice, *OrderPaymentSetter]("order_payments", buildOrderPaymentColumns("order_payments"), []string{"id"})

// OrderPaymentsQuery is a query on the order_payments table
type OrderPaymentsQuery = *mysql.ViewQuery[*OrderPayment, OrderPaymentSlice]

// orderPaymentR is where relationships are stored.
type orderPaymentR struct {
	Order *Order // order_payments_ibfk_1
}

func buildOrderPaymentColumns(alias string) orderPaymentColumns {
	return orderPaymentColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "order_id", "payment_type", "amount", "payment_info", "created_at", "updated_at",
		).WithParent("order_payments"),
		tableAlias:  alias,
		ID:          mysql.Quote(alias, "id"),
		OrderID:     mysql.Quote(alias, "order_id"),
		PaymentType: mysql.Quote(alias, "payment_type"),
		Amount:      mysql.Quote(alias, "amount"),
		PaymentInfo: mysql.Quote(alias, "payment_info"),
		CreatedAt:   mysql.Quote(alias, "created_at"),
		UpdatedAt:   mysql.Quote(alias, "updated_at"),
	}
}

type orderPaymentColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          mysql.Expression
	OrderID     mysql.Expression
	PaymentType mysql.Expression
	Amount      mysql.Expression
	PaymentInfo mysql.Expression
	CreatedAt   mysql.Expression
	UpdatedAt   mysql.Expression
}

func (c orderPaymentColumns) Alias() string {
	return c.tableAlias
}

func (orderPaymentColumns) AliasedAs(alias string) orderPaymentColumns {
	return buildOrderPaymentColumns(alias)
}

// OrderPaymentSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type OrderPaymentSetter struct {
	ID          omit.Val[int64]                           `db:"id,pk,autoincr" `
	OrderID     omit.Val[int64]                           `db:"order_id" `
	PaymentType omit.Val[string]                          `db:"payment_type" `
	Amount      omit.Val[decimal.Decimal]                 `db:"amount" `
	PaymentInfo omitnull.Val[types.JSON[json.RawMessage]] `db:"payment_info" `
	CreatedAt   omitnull.Val[time.Time]                   `db:"created_at" `
	UpdatedAt   omitnull.Val[time.Time]                   `db:"updated_at" `
}

func (s OrderPaymentSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.OrderID.IsValue() {
		vals = append(vals, "order_id")
	}
	if s.PaymentType.IsValue() {
		vals = append(vals, "payment_type")
	}
	if s.Amount.IsValue() {
		vals = append(vals, "amount")
	}
	if !s.PaymentInfo.IsUnset() {
		vals = append(vals, "payment_info")
	}
	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}
	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s OrderPaymentSetter) Overwrite(t *OrderPayment) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.OrderID.IsValue() {
		t.OrderID = s.OrderID.MustGet()
	}
	if s.PaymentType.IsValue() {
		t.PaymentType = s.PaymentType.MustGet()
	}
	if s.Amount.IsValue() {
		t.Amount = s.Amount.MustGet()
	}
	if !s.PaymentInfo.IsUnset() {
		t.PaymentInfo = s.PaymentInfo.MustGetNull()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt = s.CreatedAt.MustGetNull()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt = s.UpdatedAt.MustGetNull()
	}
}

func (s *OrderPaymentSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return OrderPayments.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.OrderID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.OrderID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.PaymentType.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.PaymentType.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Amount.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Amount.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.PaymentInfo.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.PaymentInfo.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.CreatedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.UpdatedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}))
}

func (s OrderPaymentSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("order_payments")...)
}

func (s OrderPaymentSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.OrderID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "order_id")...),
			mysql.Arg(s.OrderID),
		}})
	}

	if s.PaymentType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "payment_type")...),
			mysql.Arg(s.PaymentType),
		}})
	}

	if s.Amount.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "amount")...),
			mysql.Arg(s.Amount),
		}})
	}

	if !s.PaymentInfo.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "payment_info")...),
			mysql.Arg(s.PaymentInfo),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindOrderPayment retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindOrderPayment(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*OrderPayment, error) {
	if len(cols) == 0 {
		return OrderPayments.Query(
			sm.Where(OrderPayments.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return OrderPayments.Query(
		sm.Where(OrderPayments.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(OrderPayments.Columns.Only(cols...)),
	).One(ctx, exec)
}

// OrderPaymentExists checks the presence of a single record by primary key
func OrderPaymentExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return OrderPayments.Query(
		sm.Where(OrderPayments.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after OrderPayment is retrieved from the database
func (o *OrderPayment) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = OrderPayments.AfterSelectHooks.RunHooks(ctx, exec, OrderPaymentSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = OrderPayments.AfterInsertHooks.RunHooks(ctx, exec, OrderPaymentSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = OrderPayments.AfterUpdateHooks.RunHooks(ctx, exec, OrderPaymentSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = OrderPayments.AfterDeleteHooks.RunHooks(ctx, exec, OrderPaymentSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the OrderPayment
func (o *OrderPayment) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *OrderPayment) pkEQ() dialect.Expression {
	return mysql.Quote("order_payments", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the OrderPayment
func (o *OrderPayment) Update(ctx context.Context, exec bob.Executor, s *OrderPaymentSetter) error {
	_, err := OrderPayments.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single OrderPayment record with an executor
func (o *OrderPayment) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := OrderPayments.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the OrderPayment using the executor
func (o *OrderPayment) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := OrderPayments.Query(
		sm.Where(OrderPayments.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after OrderPaymentSlice is retrieved from the database
func (o OrderPaymentSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = OrderPayments.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = OrderPayments.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = OrderPayments.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = OrderPayments.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o OrderPaymentSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("order_payments", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o OrderPaymentSlice) copyMatchingRows(from ...*OrderPayment) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o OrderPaymentSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return OrderPayments.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *OrderPayment:
				o.copyMatchingRows(retrieved)
			case []*OrderPayment:
				o.copyMatchingRows(retrieved...)
			case OrderPaymentSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a OrderPayment or a slice of OrderPayment
				// then run the AfterUpdateHooks on the slice
				_, err = OrderPayments.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o OrderPaymentSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return OrderPayments.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *OrderPayment:
				o.copyMatchingRows(retrieved)
			case []*OrderPayment:
				o.copyMatchingRows(retrieved...)
			case OrderPaymentSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a OrderPayment or a slice of OrderPayment
				// then run the AfterDeleteHooks on the slice
				_, err = OrderPayments.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o OrderPaymentSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals OrderPaymentSetter) error {
	_, err := OrderPayments.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o OrderPaymentSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := OrderPayments.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o OrderPaymentSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := OrderPayments.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Order starts a query for related objects on orders
func (o *OrderPayment) Order(mods ...bob.Mod[*dialect.SelectQuery]) OrdersQuery {
	return Orders.Query(append(mods,
		sm.Where(Orders.Columns.ID.EQ(mysql.Arg(o.OrderID))),
	)...)
}

func (os OrderPaymentSlice) Order(mods ...bob.Mod[*dialect.SelectQuery]) OrdersQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.OrderID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return Orders.Query(append(mods,
		sm.Where(mysql.Group(Orders.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachOrderPaymentOrder0(ctx context.Context, exec bob.Executor, count int, orderPayment0 *OrderPayment, order1 *Order) (*OrderPayment, error) {
	setter := &OrderPaymentSetter{
		OrderID: omit.From(order1.ID),
	}

	err := orderPayment0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachOrderPaymentOrder0: %w", err)
	}

	return orderPayment0, nil
}

func (orderPayment0 *OrderPayment) InsertOrder(ctx context.Context, exec bob.Executor, related *OrderSetter) error {
	var err error

	order1, err := Orders.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachOrderPaymentOrder0(ctx, exec, 1, orderPayment0, order1)
	if err != nil {
		return err
	}

	orderPayment0.R.Order = order1

	order1.R.OrderPayments = append(order1.R.OrderPayments, orderPayment0)

	return nil
}

func (orderPayment0 *OrderPayment) AttachOrder(ctx context.Context, exec bob.Executor, order1 *Order) error {
	var err error

	_, err = attachOrderPaymentOrder0(ctx, exec, 1, orderPayment0, order1)
	if err != nil {
		return err
	}

	orderPayment0.R.Order = order1

	order1.R.OrderPayments = append(order1.R.OrderPayments, orderPayment0)

	return nil
}

type orderPaymentWhere[Q mysql.Filterable] struct {
	ID          mysql.WhereMod[Q, int64]
	OrderID     mysql.WhereMod[Q, int64]
	PaymentType mysql.WhereMod[Q, string]
	Amount      mysql.WhereMod[Q, decimal.Decimal]
	PaymentInfo mysql.WhereNullMod[Q, types.JSON[json.RawMessage]]
	CreatedAt   mysql.WhereNullMod[Q, time.Time]
	UpdatedAt   mysql.WhereNullMod[Q, time.Time]
}

func (orderPaymentWhere[Q]) AliasedAs(alias string) orderPaymentWhere[Q] {
	return buildOrderPaymentWhere[Q](buildOrderPaymentColumns(alias))
}

func buildOrderPaymentWhere[Q mysql.Filterable](cols orderPaymentColumns) orderPaymentWhere[Q] {
	return orderPaymentWhere[Q]{
		ID:          mysql.Where[Q, int64](cols.ID),
		OrderID:     mysql.Where[Q, int64](cols.OrderID),
		PaymentType: mysql.Where[Q, string](cols.PaymentType),
		Amount:      mysql.Where[Q, decimal.Decimal](cols.Amount),
		PaymentInfo: mysql.WhereNull[Q, types.JSON[json.RawMessage]](cols.PaymentInfo),
		CreatedAt:   mysql.WhereNull[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   mysql.WhereNull[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *OrderPayment) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Order":
		rel, ok := retrieved.(*Order)
		if !ok {
			return fmt.Errorf("orderPayment cannot load %T as %q", retrieved, name)
		}

		o.R.Order = rel

		if rel != nil {
			rel.R.OrderPayments = OrderPaymentSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("orderPayment has no relationship %q", name)
	}
}

type orderPaymentPreloader struct {
	Order func(...mysql.PreloadOption) mysql.Preloader
}

func buildOrderPaymentPreloader() orderPaymentPreloader {
	return orderPaymentPreloader{
		Order: func(opts ...mysql.PreloadOption) mysql.Preloader {
			return mysql.Preload[*Order, OrderSlice](mysql.PreloadRel{
				Name: "Order",
				Sides: []mysql.PreloadSide{
					{
						From:        OrderPayments,
						To:          Orders,
						FromColumns: []string{"order_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Orders.Columns.Names(), opts...)
		},
	}
}

type orderPaymentThenLoader[Q orm.Loadable] struct {
	Order func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildOrderPaymentThenLoader[Q orm.Loadable]() orderPaymentThenLoader[Q] {
	type OrderLoadInterface interface {
		LoadOrder(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return orderPaymentThenLoader[Q]{
		Order: thenLoadBuilder[Q](
			"Order",
			func(ctx context.Context, exec bob.Executor, retrieved OrderLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrder(ctx, exec, mods...)
			},
		),
	}
}

// LoadOrder loads the orderPayment's Order into the .R struct
func (o *OrderPayment) LoadOrder(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Order = nil

	related, err := o.Order(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.OrderPayments = OrderPaymentSlice{o}

	o.R.Order = related
	return nil
}

// LoadOrder loads the orderPayment's Order into the .R struct
func (os OrderPaymentSlice) LoadOrder(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	orders, err := os.Order(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range orders {

			if !(o.OrderID == rel.ID) {
				continue
			}

			rel.R.OrderPayments = append(rel.R.OrderPayments, o)

			o.R.Order = rel
			break
		}
	}

	return nil
}

type orderPaymentJoins[Q dialect.Joinable] struct {
	typ   string
	Order modAs[Q, orderColumns]
}

func (j orderPaymentJoins[Q]) aliasedAs(alias string) orderPaymentJoins[Q] {
	return buildOrderPaymentJoins[Q](buildOrderPaymentColumns(alias), j.typ)
}

func buildOrderPaymentJoins[Q dialect.Joinable](cols orderPaymentColumns, typ string) orderPaymentJoins[Q] {
	return orderPaymentJoins[Q]{
		typ: typ,
		Order: modAs[Q, orderColumns]{
			c: Orders.Columns,
			f: func(to orderColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Orders.Name().As(to.Alias())).On(
						to.ID.EQ(cols.OrderID),
					))
				}

				return mods
			},
		},
	}
}
