// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
)

// Product is an object representing the database table.
type Product struct {
	ID        int64               `db:"id,pk,autoincr" `
	Name      string              `db:"name" `
	Category  string              `db:"category" `
	Price     decimal.Decimal     `db:"price" `
	CreatedAt null.Val[time.Time] `db:"created_at" `
	UpdatedAt null.Val[time.Time] `db:"updated_at" `

	R productR `db:"-" `
}

// ProductSlice is an alias for a slice of pointers to Product.
// This should almost always be used instead of []*Product.
type ProductSlice []*Product

// Products contains methods to work with the products table
var Products = mysql.NewTablex[*Product, ProductSlice, *ProductSetter]("products", buildProductColumns("products"), []string{"id"})

// ProductsQuery is a query on the products table
type ProductsQuery = *mysql.ViewQuery[*Product, ProductSlice]

// productR is where relationships are stored.
type productR struct {
	OrderItems OrderItemSlice // order_items_ibfk_2
}

func buildProductColumns(alias string) productColumns {
	return productColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "category", "price", "created_at", "updated_at",
		).WithParent("products"),
		tableAlias: alias,
		ID:         mysql.Quote(alias, "id"),
		Name:       mysql.Quote(alias, "name"),
		Category:   mysql.Quote(alias, "category"),
		Price:      mysql.Quote(alias, "price"),
		CreatedAt:  mysql.Quote(alias, "created_at"),
		UpdatedAt:  mysql.Quote(alias, "updated_at"),
	}
}

type productColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         mysql.Expression
	Name       mysql.Expression
	Category   mysql.Expression
	Price      mysql.Expression
	CreatedAt  mysql.Expression
	UpdatedAt  mysql.Expression
}

func (c productColumns) Alias() string {
	return c.tableAlias
}

func (productColumns) AliasedAs(alias string) productColumns {
	return buildProductColumns(alias)
}

// ProductSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ProductSetter struct {
	ID        omit.Val[int64]           `db:"id,pk,autoincr" `
	Name      omit.Val[string]          `db:"name" `
	Category  omit.Val[string]          `db:"category" `
	Price     omit.Val[decimal.Decimal] `db:"price" `
	CreatedAt omitnull.Val[time.Time]   `db:"created_at" `
	UpdatedAt omitnull.Val[time.Time]   `db:"updated_at" `
}

func (s ProductSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Category.IsValue() {
		vals = append(vals, "category")
	}
	if s.Price.IsValue() {
		vals = append(vals, "price")
	}
	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}
	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ProductSetter) Overwrite(t *Product) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Category.IsValue() {
		t.Category = s.Category.MustGet()
	}
	if s.Price.IsValue() {
		t.Price = s.Price.MustGet()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt = s.CreatedAt.MustGetNull()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt = s.UpdatedAt.MustGetNull()
	}
}

func (s *ProductSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Products.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Name.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Category.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Category.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Price.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Price.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.CreatedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.UpdatedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}))
}

func (s ProductSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("products")...)
}

func (s ProductSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "name")...),
			mysql.Arg(s.Name),
		}})
	}

	if s.Category.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "category")...),
			mysql.Arg(s.Category),
		}})
	}

	if s.Price.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "price")...),
			mysql.Arg(s.Price),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindProduct retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindProduct(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*Product, error) {
	if len(cols) == 0 {
		return Products.Query(
			sm.Where(Products.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Products.Query(
		sm.Where(Products.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(Products.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ProductExists checks the presence of a single record by primary key
func ProductExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return Products.Query(
		sm.Where(Products.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Product is retrieved from the database
func (o *Product) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Products.AfterSelectHooks.RunHooks(ctx, exec, ProductSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Products.AfterInsertHooks.RunHooks(ctx, exec, ProductSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Products.AfterUpdateHooks.RunHooks(ctx, exec, ProductSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Products.AfterDeleteHooks.RunHooks(ctx, exec, ProductSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Product
func (o *Product) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *Product) pkEQ() dialect.Expression {
	return mysql.Quote("products", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Product
func (o *Product) Update(ctx context.Context, exec bob.Executor, s *ProductSetter) error {
	_, err := Products.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single Product record with an executor
func (o *Product) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Products.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Product using the executor
func (o *Product) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Products.Query(
		sm.Where(Products.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ProductSlice is retrieved from the database
func (o ProductSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Products.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Products.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Products.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Products.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ProductSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("products", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ProductSlice) copyMatchingRows(from ...*Product) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ProductSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Products.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Product:
				o.copyMatchingRows(retrieved)
			case []*Product:
				o.copyMatchingRows(retrieved...)
			case ProductSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Product or a slice of Product
				// then run the AfterUpdateHooks on the slice
				_, err = Products.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ProductSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Products.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Product:
				o.copyMatchingRows(retrieved)
			case []*Product:
				o.copyMatchingRows(retrieved...)
			case ProductSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Product or a slice of Product
				// then run the AfterDeleteHooks on the slice
				_, err = Products.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ProductSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ProductSetter) error {
	_, err := Products.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o ProductSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Products.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ProductSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Products.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// OrderItems starts a query for related objects on order_items
func (o *Product) OrderItems(mods ...bob.Mod[*dialect.SelectQuery]) OrderItemsQuery {
	return OrderItems.Query(append(mods,
		sm.Where(OrderItems.Columns.ProductID.EQ(mysql.Arg(o.ID))),
	)...)
}

func (os ProductSlice) OrderItems(mods ...bob.Mod[*dialect.SelectQuery]) OrderItemsQuery {
	PKArgSlice := make([]bob.Expression, len(os))
	for i, o := range os {
		PKArgSlice[i] = mysql.ArgGroup(o.ID)
	}
	PKArgExpr := mysql.Group(PKArgSlice...)

	return OrderItems.Query(append(mods,
		sm.Where(mysql.Group(OrderItems.Columns.ProductID).OP("IN", PKArgExpr)),
	)...)
}

func insertProductOrderItems0(ctx context.Context, exec bob.Executor, orderItems1 []*OrderItemSetter, product0 *Product) (OrderItemSlice, error) {
	for i := range orderItems1 {
		orderItems1[i].ProductID = omit.From(product0.ID)
	}

	ret, err := OrderItems.Insert(bob.ToMods(orderItems1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertProductOrderItems0: %w", err)
	}

	return ret, nil
}

func attachProductOrderItems0(ctx context.Context, exec bob.Executor, count int, orderItems1 OrderItemSlice, product0 *Product) (OrderItemSlice, error) {
	setter := &OrderItemSetter{
		ProductID: omit.From(product0.ID),
	}

	err := orderItems1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachProductOrderItems0: %w", err)
	}

	return orderItems1, nil
}

func (product0 *Product) InsertOrderItems(ctx context.Context, exec bob.Executor, related ...*OrderItemSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	orderItems1, err := insertProductOrderItems0(ctx, exec, related, product0)
	if err != nil {
		return err
	}

	product0.R.OrderItems = append(product0.R.OrderItems, orderItems1...)

	for _, rel := range orderItems1 {
		rel.R.Product = product0
	}
	return nil
}

func (product0 *Product) AttachOrderItems(ctx context.Context, exec bob.Executor, related ...*OrderItem) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	orderItems1 := OrderItemSlice(related)

	_, err = attachProductOrderItems0(ctx, exec, len(related), orderItems1, product0)
	if err != nil {
		return err
	}

	product0.R.OrderItems = append(product0.R.OrderItems, orderItems1...)

	for _, rel := range related {
		rel.R.Product = product0
	}

	return nil
}

type productWhere[Q mysql.Filterable] struct {
	ID        mysql.WhereMod[Q, int64]
	Name      mysql.WhereMod[Q, string]
	Category  mysql.WhereMod[Q, string]
	Price     mysql.WhereMod[Q, decimal.Decimal]
	CreatedAt mysql.WhereNullMod[Q, time.Time]
	UpdatedAt mysql.WhereNullMod[Q, time.Time]
}

func (productWhere[Q]) AliasedAs(alias string) productWhere[Q] {
	return buildProductWhere[Q](buildProductColumns(alias))
}

func buildProductWhere[Q mysql.Filterable](cols productColumns) productWhere[Q] {
	return productWhere[Q]{
		ID:        mysql.Where[Q, int64](cols.ID),
		Name:      mysql.Where[Q, string](cols.Name),
		Category:  mysql.Where[Q, string](cols.Category),
		Price:     mysql.Where[Q, decimal.Decimal](cols.Price),
		CreatedAt: mysql.WhereNull[Q, time.Time](cols.CreatedAt),
		UpdatedAt: mysql.WhereNull[Q, time.Time](cols.UpdatedAt),
	}
}

func (o *Product) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "OrderItems":
		rels, ok := retrieved.(OrderItemSlice)
		if !ok {
			return fmt.Errorf("product cannot load %T as %q", retrieved, name)
		}

		o.R.OrderItems = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Product = o
			}
		}
		return nil
	default:
		return fmt.Errorf("product has no relationship %q", name)
	}
}

type productPreloader struct{}

func buildProductPreloader() productPreloader {
	return productPreloader{}
}

type productThenLoader[Q orm.Loadable] struct {
	OrderItems func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildProductThenLoader[Q orm.Loadable]() productThenLoader[Q] {
	type OrderItemsLoadInterface interface {
		LoadOrderItems(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return productThenLoader[Q]{
		OrderItems: thenLoadBuilder[Q](
			"OrderItems",
			func(ctx context.Context, exec bob.Executor, retrieved OrderItemsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadOrderItems(ctx, exec, mods...)
			},
		),
	}
}

// LoadOrderItems loads the product's OrderItems into the .R struct
func (o *Product) LoadOrderItems(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.OrderItems = nil

	related, err := o.OrderItems(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Product = o
	}

	o.R.OrderItems = related
	return nil
}

// LoadOrderItems loads the product's OrderItems into the .R struct
func (os ProductSlice) LoadOrderItems(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	orderItems, err := os.OrderItems(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.OrderItems = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range orderItems {

			if !(o.ID == rel.ProductID) {
				continue
			}

			rel.R.Product = o

			o.R.OrderItems = append(o.R.OrderItems, rel)
		}
	}

	return nil
}

type productJoins[Q dialect.Joinable] struct {
	typ        string
	OrderItems modAs[Q, orderItemColumns]
}

func (j productJoins[Q]) aliasedAs(alias string) productJoins[Q] {
	return buildProductJoins[Q](buildProductColumns(alias), j.typ)
}

func buildProductJoins[Q dialect.Joinable](cols productColumns, typ string) productJoins[Q] {
	return productJoins[Q]{
		typ: typ,
		OrderItems: modAs[Q, orderItemColumns]{
			c: OrderItems.Columns,
			f: func(to orderItemColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, OrderItems.Name().As(to.Alias())).On(
						to.ProductID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
