// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/mysql"
	"github.com/stephenafamo/bob/dialect/mysql/dialect"
	"github.com/stephenafamo/bob/dialect/mysql/dm"
	"github.com/stephenafamo/bob/dialect/mysql/sm"
	"github.com/stephenafamo/bob/dialect/mysql/um"
	"github.com/stephenafamo/bob/expr"
)

// ReportingOrder is an object representing the database table.
type ReportingOrder struct {
	ID          int64               `db:"id,pk,autoincr" `
	Category    string              `db:"category" `
	OrderType   string              `db:"order_type" `
	ReportOrder int32               `db:"report_order" `
	Title       string              `db:"title" `
	CreatedAt   null.Val[time.Time] `db:"created_at" `
	UpdatedAt   null.Val[time.Time] `db:"updated_at" `
}

// ReportingOrderSlice is an alias for a slice of pointers to ReportingOrder.
// This should almost always be used instead of []*ReportingOrder.
type ReportingOrderSlice []*ReportingOrder

// ReportingOrders contains methods to work with the reporting_order table
var ReportingOrders = mysql.NewTablex[*ReportingOrder, ReportingOrderSlice, *ReportingOrderSetter]("reporting_order", buildReportingOrderColumns("reporting_order"), []string{"id"})

// ReportingOrdersQuery is a query on the reporting_order table
type ReportingOrdersQuery = *mysql.ViewQuery[*ReportingOrder, ReportingOrderSlice]

func buildReportingOrderColumns(alias string) reportingOrderColumns {
	return reportingOrderColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "category", "order_type", "report_order", "title", "created_at", "updated_at",
		).WithParent("reporting_order"),
		tableAlias:  alias,
		ID:          mysql.Quote(alias, "id"),
		Category:    mysql.Quote(alias, "category"),
		OrderType:   mysql.Quote(alias, "order_type"),
		ReportOrder: mysql.Quote(alias, "report_order"),
		Title:       mysql.Quote(alias, "title"),
		CreatedAt:   mysql.Quote(alias, "created_at"),
		UpdatedAt:   mysql.Quote(alias, "updated_at"),
	}
}

type reportingOrderColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          mysql.Expression
	Category    mysql.Expression
	OrderType   mysql.Expression
	ReportOrder mysql.Expression
	Title       mysql.Expression
	CreatedAt   mysql.Expression
	UpdatedAt   mysql.Expression
}

func (c reportingOrderColumns) Alias() string {
	return c.tableAlias
}

func (reportingOrderColumns) AliasedAs(alias string) reportingOrderColumns {
	return buildReportingOrderColumns(alias)
}

// ReportingOrderSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ReportingOrderSetter struct {
	ID          omit.Val[int64]         `db:"id,pk,autoincr" `
	Category    omit.Val[string]        `db:"category" `
	OrderType   omit.Val[string]        `db:"order_type" `
	ReportOrder omit.Val[int32]         `db:"report_order" `
	Title       omit.Val[string]        `db:"title" `
	CreatedAt   omitnull.Val[time.Time] `db:"created_at" `
	UpdatedAt   omitnull.Val[time.Time] `db:"updated_at" `
}

func (s ReportingOrderSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Category.IsValue() {
		vals = append(vals, "category")
	}
	if s.OrderType.IsValue() {
		vals = append(vals, "order_type")
	}
	if s.ReportOrder.IsValue() {
		vals = append(vals, "report_order")
	}
	if s.Title.IsValue() {
		vals = append(vals, "title")
	}
	if !s.CreatedAt.IsUnset() {
		vals = append(vals, "created_at")
	}
	if !s.UpdatedAt.IsUnset() {
		vals = append(vals, "updated_at")
	}
	return vals
}

func (s ReportingOrderSetter) Overwrite(t *ReportingOrder) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Category.IsValue() {
		t.Category = s.Category.MustGet()
	}
	if s.OrderType.IsValue() {
		t.OrderType = s.OrderType.MustGet()
	}
	if s.ReportOrder.IsValue() {
		t.ReportOrder = s.ReportOrder.MustGet()
	}
	if s.Title.IsValue() {
		t.Title = s.Title.MustGet()
	}
	if !s.CreatedAt.IsUnset() {
		t.CreatedAt = s.CreatedAt.MustGetNull()
	}
	if !s.UpdatedAt.IsUnset() {
		t.UpdatedAt = s.UpdatedAt.MustGetNull()
	}
}

func (s *ReportingOrderSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return ReportingOrders.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ID.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Category.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Category.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.OrderType.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.OrderType.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.ReportOrder.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.ReportOrder.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(s.Title.IsValue()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.Title.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.CreatedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.CreatedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if !(!s.UpdatedAt.IsUnset()) {
				return mysql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return mysql.Arg(s.UpdatedAt.MustGetNull()).WriteSQL(ctx, w, d, start)
		}))
}

func (s ReportingOrderSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions("reporting_order")...)
}

func (s ReportingOrderSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "id")...),
			mysql.Arg(s.ID),
		}})
	}

	if s.Category.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "category")...),
			mysql.Arg(s.Category),
		}})
	}

	if s.OrderType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "order_type")...),
			mysql.Arg(s.OrderType),
		}})
	}

	if s.ReportOrder.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "report_order")...),
			mysql.Arg(s.ReportOrder),
		}})
	}

	if s.Title.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "title")...),
			mysql.Arg(s.Title),
		}})
	}

	if !s.CreatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "created_at")...),
			mysql.Arg(s.CreatedAt),
		}})
	}

	if !s.UpdatedAt.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			mysql.Quote(append(prefix, "updated_at")...),
			mysql.Arg(s.UpdatedAt),
		}})
	}

	return exprs
}

// FindReportingOrder retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindReportingOrder(ctx context.Context, exec bob.Executor, IDPK int64, cols ...string) (*ReportingOrder, error) {
	if len(cols) == 0 {
		return ReportingOrders.Query(
			sm.Where(ReportingOrders.Columns.ID.EQ(mysql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return ReportingOrders.Query(
		sm.Where(ReportingOrders.Columns.ID.EQ(mysql.Arg(IDPK))),
		sm.Columns(ReportingOrders.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ReportingOrderExists checks the presence of a single record by primary key
func ReportingOrderExists(ctx context.Context, exec bob.Executor, IDPK int64) (bool, error) {
	return ReportingOrders.Query(
		sm.Where(ReportingOrders.Columns.ID.EQ(mysql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after ReportingOrder is retrieved from the database
func (o *ReportingOrder) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ReportingOrders.AfterSelectHooks.RunHooks(ctx, exec, ReportingOrderSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = ReportingOrders.AfterInsertHooks.RunHooks(ctx, exec, ReportingOrderSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = ReportingOrders.AfterUpdateHooks.RunHooks(ctx, exec, ReportingOrderSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = ReportingOrders.AfterDeleteHooks.RunHooks(ctx, exec, ReportingOrderSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the ReportingOrder
func (o *ReportingOrder) primaryKeyVals() bob.Expression {
	return mysql.Arg(o.ID)
}

func (o *ReportingOrder) pkEQ() dialect.Expression {
	return mysql.Quote("reporting_order", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the ReportingOrder
func (o *ReportingOrder) Update(ctx context.Context, exec bob.Executor, s *ReportingOrderSetter) error {
	_, err := ReportingOrders.Update(s.UpdateMod(), um.Where(o.pkEQ())).Exec(ctx, exec)
	if err != nil {
		return err
	}

	s.Overwrite(o)

	return nil
}

// Delete deletes a single ReportingOrder record with an executor
func (o *ReportingOrder) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := ReportingOrders.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the ReportingOrder using the executor
func (o *ReportingOrder) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := ReportingOrders.Query(
		sm.Where(ReportingOrders.Columns.ID.EQ(mysql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after ReportingOrderSlice is retrieved from the database
func (o ReportingOrderSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = ReportingOrders.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = ReportingOrders.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = ReportingOrders.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = ReportingOrders.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ReportingOrderSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return mysql.Raw("NULL")
	}

	return mysql.Quote("reporting_order", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ReportingOrderSlice) copyMatchingRows(from ...*ReportingOrder) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ReportingOrderSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ReportingOrders.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ReportingOrder:
				o.copyMatchingRows(retrieved)
			case []*ReportingOrder:
				o.copyMatchingRows(retrieved...)
			case ReportingOrderSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ReportingOrder or a slice of ReportingOrder
				// then run the AfterUpdateHooks on the slice
				_, err = ReportingOrders.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ReportingOrderSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return ReportingOrders.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *ReportingOrder:
				o.copyMatchingRows(retrieved)
			case []*ReportingOrder:
				o.copyMatchingRows(retrieved...)
			case ReportingOrderSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a ReportingOrder or a slice of ReportingOrder
				// then run the AfterDeleteHooks on the slice
				_, err = ReportingOrders.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ReportingOrderSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ReportingOrderSetter) error {
	_, err := ReportingOrders.Update(vals.UpdateMod(), o.UpdateMod()).Exec(ctx, exec)

	for i := range o {
		vals.Overwrite(o[i])
	}

	return err
}

func (o ReportingOrderSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := ReportingOrders.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ReportingOrderSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := ReportingOrders.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type reportingOrderWhere[Q mysql.Filterable] struct {
	ID          mysql.WhereMod[Q, int64]
	Category    mysql.WhereMod[Q, string]
	OrderType   mysql.WhereMod[Q, string]
	ReportOrder mysql.WhereMod[Q, int32]
	Title       mysql.WhereMod[Q, string]
	CreatedAt   mysql.WhereNullMod[Q, time.Time]
	UpdatedAt   mysql.WhereNullMod[Q, time.Time]
}

func (reportingOrderWhere[Q]) AliasedAs(alias string) reportingOrderWhere[Q] {
	return buildReportingOrderWhere[Q](buildReportingOrderColumns(alias))
}

func buildReportingOrderWhere[Q mysql.Filterable](cols reportingOrderColumns) reportingOrderWhere[Q] {
	return reportingOrderWhere[Q]{
		ID:          mysql.Where[Q, int64](cols.ID),
		Category:    mysql.Where[Q, string](cols.Category),
		OrderType:   mysql.Where[Q, string](cols.OrderType),
		ReportOrder: mysql.Where[Q, int32](cols.ReportOrder),
		Title:       mysql.Where[Q, string](cols.Title),
		CreatedAt:   mysql.WhereNull[Q, time.Time](cols.CreatedAt),
		UpdatedAt:   mysql.WhereNull[Q, time.Time](cols.UpdatedAt),
	}
}
