// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"encoding/json"
	"time"

	"github.com/aarondl/opt/null"
	models "github.com/acsellers/golang-db-compare/store/mysql/bob/models"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob/types"
)

type Factory struct {
	baseCustomerMods       CustomerModSlice
	baseDiscountMods       DiscountModSlice
	baseItemSummaryMods    ItemSummaryModSlice
	baseOrderItemMods      OrderItemModSlice
	baseOrderPaymentMods   OrderPaymentModSlice
	baseOrderMods          OrderModSlice
	basePaymentNameMods    PaymentNameModSlice
	baseProductMods        ProductModSlice
	baseReportingOrderMods ReportingOrderModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewCustomer(mods ...CustomerMod) *CustomerTemplate {
	return f.NewCustomerWithContext(context.Background(), mods...)
}

func (f *Factory) NewCustomerWithContext(ctx context.Context, mods ...CustomerMod) *CustomerTemplate {
	o := &CustomerTemplate{f: f}

	if f != nil {
		f.baseCustomerMods.Apply(ctx, o)
	}

	CustomerModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingCustomer(m *models.Customer) *CustomerTemplate {
	o := &CustomerTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Name = func() string { return m.Name }
	o.Phone = func() null.Val[string] { return m.Phone }
	o.Email = func() null.Val[string] { return m.Email }
	o.MarketingOptIn = func() null.Val[bool] { return m.MarketingOptIn }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }
	o.UpdatedAt = func() null.Val[time.Time] { return m.UpdatedAt }

	ctx := context.Background()
	if len(m.R.Orders) > 0 {
		CustomerMods.AddExistingOrders(m.R.Orders...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewDiscount(mods ...DiscountMod) *DiscountTemplate {
	return f.NewDiscountWithContext(context.Background(), mods...)
}

func (f *Factory) NewDiscountWithContext(ctx context.Context, mods ...DiscountMod) *DiscountTemplate {
	o := &DiscountTemplate{f: f}

	if f != nil {
		f.baseDiscountMods.Apply(ctx, o)
	}

	DiscountModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingDiscount(m *models.Discount) *DiscountTemplate {
	o := &DiscountTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Name = func() string { return m.Name }
	o.Category = func() string { return m.Category }
	o.DiscountType = func() string { return m.DiscountType }
	o.Discount = func() decimal.Decimal { return m.Discount }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }
	o.UpdatedAt = func() null.Val[time.Time] { return m.UpdatedAt }

	ctx := context.Background()
	if len(m.R.OrderItems) > 0 {
		DiscountMods.AddExistingOrderItems(m.R.OrderItems...).Apply(ctx, o)
	}
	if len(m.R.Orders) > 0 {
		DiscountMods.AddExistingOrders(m.R.Orders...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewItemSummary(mods ...ItemSummaryMod) *ItemSummaryTemplate {
	return f.NewItemSummaryWithContext(context.Background(), mods...)
}

func (f *Factory) NewItemSummaryWithContext(ctx context.Context, mods ...ItemSummaryMod) *ItemSummaryTemplate {
	o := &ItemSummaryTemplate{f: f}

	if f != nil {
		f.baseItemSummaryMods.Apply(ctx, o)
	}

	ItemSummaryModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingItemSummary(m *models.ItemSummary) *ItemSummaryTemplate {
	o := &ItemSummaryTemplate{f: f, alreadyPersisted: true}

	o.ID = func() null.Val[int64] { return m.ID }
	o.Name = func() string { return m.Name }
	o.Category = func() string { return m.Category }
	o.OrderType = func() string { return m.OrderType }
	o.OrderDate = func() time.Time { return m.OrderDate }
	o.TotalQuantity = func() null.Val[decimal.Decimal] { return m.TotalQuantity }
	o.TotalSales = func() null.Val[decimal.Decimal] { return m.TotalSales }
	o.OrderCount = func() int64 { return m.OrderCount }

	return o
}

func (f *Factory) NewOrderItem(mods ...OrderItemMod) *OrderItemTemplate {
	return f.NewOrderItemWithContext(context.Background(), mods...)
}

func (f *Factory) NewOrderItemWithContext(ctx context.Context, mods ...OrderItemMod) *OrderItemTemplate {
	o := &OrderItemTemplate{f: f}

	if f != nil {
		f.baseOrderItemMods.Apply(ctx, o)
	}

	OrderItemModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingOrderItem(m *models.OrderItem) *OrderItemTemplate {
	o := &OrderItemTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.OrderID = func() int64 { return m.OrderID }
	o.ProductID = func() int64 { return m.ProductID }
	o.DiscountID = func() null.Val[int64] { return m.DiscountID }
	o.Quantity = func() int32 { return m.Quantity }
	o.Price = func() decimal.Decimal { return m.Price }
	o.DiscountAmount = func() decimal.Decimal { return m.DiscountAmount }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }
	o.UpdatedAt = func() null.Val[time.Time] { return m.UpdatedAt }

	ctx := context.Background()
	if m.R.Order != nil {
		OrderItemMods.WithExistingOrder(m.R.Order).Apply(ctx, o)
	}
	if m.R.Product != nil {
		OrderItemMods.WithExistingProduct(m.R.Product).Apply(ctx, o)
	}
	if m.R.Discount != nil {
		OrderItemMods.WithExistingDiscount(m.R.Discount).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewOrderPayment(mods ...OrderPaymentMod) *OrderPaymentTemplate {
	return f.NewOrderPaymentWithContext(context.Background(), mods...)
}

func (f *Factory) NewOrderPaymentWithContext(ctx context.Context, mods ...OrderPaymentMod) *OrderPaymentTemplate {
	o := &OrderPaymentTemplate{f: f}

	if f != nil {
		f.baseOrderPaymentMods.Apply(ctx, o)
	}

	OrderPaymentModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingOrderPayment(m *models.OrderPayment) *OrderPaymentTemplate {
	o := &OrderPaymentTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.OrderID = func() int64 { return m.OrderID }
	o.PaymentType = func() string { return m.PaymentType }
	o.Amount = func() decimal.Decimal { return m.Amount }
	o.PaymentInfo = func() null.Val[types.JSON[json.RawMessage]] { return m.PaymentInfo }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }
	o.UpdatedAt = func() null.Val[time.Time] { return m.UpdatedAt }

	ctx := context.Background()
	if m.R.Order != nil {
		OrderPaymentMods.WithExistingOrder(m.R.Order).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewOrder(mods ...OrderMod) *OrderTemplate {
	return f.NewOrderWithContext(context.Background(), mods...)
}

func (f *Factory) NewOrderWithContext(ctx context.Context, mods ...OrderMod) *OrderTemplate {
	o := &OrderTemplate{f: f}

	if f != nil {
		f.baseOrderMods.Apply(ctx, o)
	}

	OrderModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingOrder(m *models.Order) *OrderTemplate {
	o := &OrderTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.OrderDate = func() time.Time { return m.OrderDate }
	o.CustomerID = func() null.Val[int64] { return m.CustomerID }
	o.DiscountID = func() null.Val[int64] { return m.DiscountID }
	o.OrderType = func() string { return m.OrderType }
	o.Subtotal = func() decimal.Decimal { return m.Subtotal }
	o.DiscountAmount = func() decimal.Decimal { return m.DiscountAmount }
	o.TaxAmount = func() decimal.Decimal { return m.TaxAmount }
	o.Total = func() decimal.Decimal { return m.Total }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }
	o.UpdatedAt = func() null.Val[time.Time] { return m.UpdatedAt }

	ctx := context.Background()
	if len(m.R.OrderItems) > 0 {
		OrderMods.AddExistingOrderItems(m.R.OrderItems...).Apply(ctx, o)
	}
	if len(m.R.OrderPayments) > 0 {
		OrderMods.AddExistingOrderPayments(m.R.OrderPayments...).Apply(ctx, o)
	}
	if m.R.Customer != nil {
		OrderMods.WithExistingCustomer(m.R.Customer).Apply(ctx, o)
	}
	if m.R.Discount != nil {
		OrderMods.WithExistingDiscount(m.R.Discount).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewPaymentName(mods ...PaymentNameMod) *PaymentNameTemplate {
	return f.NewPaymentNameWithContext(context.Background(), mods...)
}

func (f *Factory) NewPaymentNameWithContext(ctx context.Context, mods ...PaymentNameMod) *PaymentNameTemplate {
	o := &PaymentNameTemplate{f: f}

	if f != nil {
		f.basePaymentNameMods.Apply(ctx, o)
	}

	PaymentNameModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingPaymentName(m *models.PaymentName) *PaymentNameTemplate {
	o := &PaymentNameTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.PaymentType = func() string { return m.PaymentType }
	o.Name = func() string { return m.Name }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }
	o.UpdatedAt = func() null.Val[time.Time] { return m.UpdatedAt }

	return o
}

func (f *Factory) NewProduct(mods ...ProductMod) *ProductTemplate {
	return f.NewProductWithContext(context.Background(), mods...)
}

func (f *Factory) NewProductWithContext(ctx context.Context, mods ...ProductMod) *ProductTemplate {
	o := &ProductTemplate{f: f}

	if f != nil {
		f.baseProductMods.Apply(ctx, o)
	}

	ProductModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingProduct(m *models.Product) *ProductTemplate {
	o := &ProductTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Name = func() string { return m.Name }
	o.Category = func() string { return m.Category }
	o.Price = func() decimal.Decimal { return m.Price }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }
	o.UpdatedAt = func() null.Val[time.Time] { return m.UpdatedAt }

	ctx := context.Background()
	if len(m.R.OrderItems) > 0 {
		ProductMods.AddExistingOrderItems(m.R.OrderItems...).Apply(ctx, o)
	}

	return o
}

func (f *Factory) NewReportingOrder(mods ...ReportingOrderMod) *ReportingOrderTemplate {
	return f.NewReportingOrderWithContext(context.Background(), mods...)
}

func (f *Factory) NewReportingOrderWithContext(ctx context.Context, mods ...ReportingOrderMod) *ReportingOrderTemplate {
	o := &ReportingOrderTemplate{f: f}

	if f != nil {
		f.baseReportingOrderMods.Apply(ctx, o)
	}

	ReportingOrderModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) FromExistingReportingOrder(m *models.ReportingOrder) *ReportingOrderTemplate {
	o := &ReportingOrderTemplate{f: f, alreadyPersisted: true}

	o.ID = func() int64 { return m.ID }
	o.Category = func() string { return m.Category }
	o.OrderType = func() string { return m.OrderType }
	o.ReportOrder = func() int32 { return m.ReportOrder }
	o.Title = func() string { return m.Title }
	o.CreatedAt = func() null.Val[time.Time] { return m.CreatedAt }
	o.UpdatedAt = func() null.Val[time.Time] { return m.UpdatedAt }

	return o
}

func (f *Factory) ClearBaseCustomerMods() {
	f.baseCustomerMods = nil
}

func (f *Factory) AddBaseCustomerMod(mods ...CustomerMod) {
	f.baseCustomerMods = append(f.baseCustomerMods, mods...)
}

func (f *Factory) ClearBaseDiscountMods() {
	f.baseDiscountMods = nil
}

func (f *Factory) AddBaseDiscountMod(mods ...DiscountMod) {
	f.baseDiscountMods = append(f.baseDiscountMods, mods...)
}

func (f *Factory) ClearBaseItemSummaryMods() {
	f.baseItemSummaryMods = nil
}

func (f *Factory) AddBaseItemSummaryMod(mods ...ItemSummaryMod) {
	f.baseItemSummaryMods = append(f.baseItemSummaryMods, mods...)
}

func (f *Factory) ClearBaseOrderItemMods() {
	f.baseOrderItemMods = nil
}

func (f *Factory) AddBaseOrderItemMod(mods ...OrderItemMod) {
	f.baseOrderItemMods = append(f.baseOrderItemMods, mods...)
}

func (f *Factory) ClearBaseOrderPaymentMods() {
	f.baseOrderPaymentMods = nil
}

func (f *Factory) AddBaseOrderPaymentMod(mods ...OrderPaymentMod) {
	f.baseOrderPaymentMods = append(f.baseOrderPaymentMods, mods...)
}

func (f *Factory) ClearBaseOrderMods() {
	f.baseOrderMods = nil
}

func (f *Factory) AddBaseOrderMod(mods ...OrderMod) {
	f.baseOrderMods = append(f.baseOrderMods, mods...)
}

func (f *Factory) ClearBasePaymentNameMods() {
	f.basePaymentNameMods = nil
}

func (f *Factory) AddBasePaymentNameMod(mods ...PaymentNameMod) {
	f.basePaymentNameMods = append(f.basePaymentNameMods, mods...)
}

func (f *Factory) ClearBaseProductMods() {
	f.baseProductMods = nil
}

func (f *Factory) AddBaseProductMod(mods ...ProductMod) {
	f.baseProductMods = append(f.baseProductMods, mods...)
}

func (f *Factory) ClearBaseReportingOrderMods() {
	f.baseReportingOrderMods = nil
}

func (f *Factory) AddBaseReportingOrderMod(mods ...ReportingOrderMod) {
	f.baseReportingOrderMods = append(f.baseReportingOrderMods, mods...)
}
