// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	// Relationship Contexts for customers
	customerWithParentsCascadingCtx = newContextual[bool]("customerWithParentsCascading")
	customerRelOrdersCtx            = newContextual[bool]("customers.orders.orders_ibfk_1")

	// Relationship Contexts for dim_date
	dimDateWithParentsCascadingCtx = newContextual[bool]("dimDateWithParentsCascading")

	// Relationship Contexts for discounts
	discountWithParentsCascadingCtx = newContextual[bool]("discountWithParentsCascading")
	discountRelOrderItemsCtx        = newContextual[bool]("discounts.order_items.order_items_ibfk_3")
	discountRelOrdersCtx            = newContextual[bool]("discounts.orders.orders_ibfk_2")

	// Relationship Contexts for item_summaries
	itemSummaryWithParentsCascadingCtx = newContextual[bool]("itemSummaryWithParentsCascading")

	// Relationship Contexts for order_items
	orderItemWithParentsCascadingCtx = newContextual[bool]("orderItemWithParentsCascading")
	orderItemRelOrderCtx             = newContextual[bool]("order_items.orders.order_items_ibfk_1")
	orderItemRelProductCtx           = newContextual[bool]("order_items.products.order_items_ibfk_2")
	orderItemRelDiscountCtx          = newContextual[bool]("discounts.order_items.order_items_ibfk_3")

	// Relationship Contexts for order_payments
	orderPaymentWithParentsCascadingCtx = newContextual[bool]("orderPaymentWithParentsCascading")
	orderPaymentRelOrderCtx             = newContextual[bool]("order_payments.orders.order_payments_ibfk_1")

	// Relationship Contexts for orders
	orderWithParentsCascadingCtx = newContextual[bool]("orderWithParentsCascading")
	orderRelOrderItemsCtx        = newContextual[bool]("order_items.orders.order_items_ibfk_1")
	orderRelOrderPaymentsCtx     = newContextual[bool]("order_payments.orders.order_payments_ibfk_1")
	orderRelCustomerCtx          = newContextual[bool]("customers.orders.orders_ibfk_1")
	orderRelDiscountCtx          = newContextual[bool]("discounts.orders.orders_ibfk_2")

	// Relationship Contexts for payment_names
	paymentNameWithParentsCascadingCtx = newContextual[bool]("paymentNameWithParentsCascading")

	// Relationship Contexts for products
	productWithParentsCascadingCtx = newContextual[bool]("productWithParentsCascading")
	productRelOrderItemsCtx        = newContextual[bool]("order_items.products.order_items_ibfk_2")

	// Relationship Contexts for reporting_order
	reportingOrderWithParentsCascadingCtx = newContextual[bool]("reportingOrderWithParentsCascading")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
