// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/acsellers/golang-db-compare/store/mysql/bob/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type CustomerMod interface {
	Apply(context.Context, *CustomerTemplate)
}

type CustomerModFunc func(context.Context, *CustomerTemplate)

func (f CustomerModFunc) Apply(ctx context.Context, n *CustomerTemplate) {
	f(ctx, n)
}

type CustomerModSlice []CustomerMod

func (mods CustomerModSlice) Apply(ctx context.Context, n *CustomerTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// CustomerTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type CustomerTemplate struct {
	ID             func() int64
	Name           func() string
	Phone          func() null.Val[string]
	Email          func() null.Val[string]
	MarketingOptIn func() null.Val[bool]
	CreatedAt      func() null.Val[time.Time]
	UpdatedAt      func() null.Val[time.Time]

	r customerR
	f *Factory

	alreadyPersisted bool
}

type customerR struct {
	Orders []*customerROrdersR
}

type customerROrdersR struct {
	number int
	o      *OrderTemplate
}

// Apply mods to the CustomerTemplate
func (o *CustomerTemplate) Apply(ctx context.Context, mods ...CustomerMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Customer
// according to the relationships in the template. Nothing is inserted into the db
func (t CustomerTemplate) setModelRels(o *models.Customer) {
	if t.r.Orders != nil {
		rel := models.OrderSlice{}
		for _, r := range t.r.Orders {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.CustomerID = null.From(o.ID) // h2
				rel.R.Customer = o
			}
			rel = append(rel, related...)
		}
		o.R.Orders = rel
	}
}

// BuildSetter returns an *models.CustomerSetter
// this does nothing with the relationship templates
func (o CustomerTemplate) BuildSetter() *models.CustomerSetter {
	m := &models.CustomerSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.Phone != nil {
		val := o.Phone()
		m.Phone = omitnull.FromNull(val)
	}
	if o.Email != nil {
		val := o.Email()
		m.Email = omitnull.FromNull(val)
	}
	if o.MarketingOptIn != nil {
		val := o.MarketingOptIn()
		m.MarketingOptIn = omitnull.FromNull(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omitnull.FromNull(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.CustomerSetter
// this does nothing with the relationship templates
func (o CustomerTemplate) BuildManySetter(number int) []*models.CustomerSetter {
	m := make([]*models.CustomerSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Customer
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CustomerTemplate.Create
func (o CustomerTemplate) Build() *models.Customer {
	m := &models.Customer{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Phone != nil {
		m.Phone = o.Phone()
	}
	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.MarketingOptIn != nil {
		m.MarketingOptIn = o.MarketingOptIn()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.CustomerSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use CustomerTemplate.CreateMany
func (o CustomerTemplate) BuildMany(number int) models.CustomerSlice {
	m := make(models.CustomerSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableCustomer(m *models.CustomerSetter) {
	if !(m.Name.IsValue()) {
		val := random_string(nil, "255")
		m.Name = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Customer
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *CustomerTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Customer) error {
	var err error

	isOrdersDone, _ := customerRelOrdersCtx.Value(ctx)
	if !isOrdersDone && o.r.Orders != nil {
		ctx = customerRelOrdersCtx.WithValue(ctx, true)
		for _, r := range o.r.Orders {
			if r.o.alreadyPersisted {
				m.R.Orders = append(m.R.Orders, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOrders(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a customer and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *CustomerTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Customer, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableCustomer(opt)

	m, err := models.Customers.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a customer and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *CustomerTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Customer {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a customer and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *CustomerTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Customer {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple customers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o CustomerTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.CustomerSlice, error) {
	var err error
	m := make(models.CustomerSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple customers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o CustomerTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.CustomerSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple customers and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o CustomerTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.CustomerSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Customer has methods that act as mods for the CustomerTemplate
var CustomerMods customerMods

type customerMods struct{}

func (m customerMods) RandomizeAllColumns(f *faker.Faker) CustomerMod {
	return CustomerModSlice{
		CustomerMods.RandomID(f),
		CustomerMods.RandomName(f),
		CustomerMods.RandomPhone(f),
		CustomerMods.RandomEmail(f),
		CustomerMods.RandomMarketingOptIn(f),
		CustomerMods.RandomCreatedAt(f),
		CustomerMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m customerMods) ID(val int64) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m customerMods) IDFunc(f func() int64) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m customerMods) UnsetID() CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m customerMods) RandomID(f *faker.Faker) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m customerMods) Name(val string) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m customerMods) NameFunc(f func() string) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m customerMods) UnsetName() CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m customerMods) RandomName(f *faker.Faker) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Name = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m customerMods) Phone(val null.Val[string]) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Phone = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m customerMods) PhoneFunc(f func() null.Val[string]) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Phone = f
	})
}

// Clear any values for the column
func (m customerMods) UnsetPhone() CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Phone = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m customerMods) RandomPhone(f *faker.Faker) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Phone = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "24")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m customerMods) RandomPhoneNotNull(f *faker.Faker) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Phone = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "24")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m customerMods) Email(val null.Val[string]) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Email = func() null.Val[string] { return val }
	})
}

// Set the Column from the function
func (m customerMods) EmailFunc(f func() null.Val[string]) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m customerMods) UnsetEmail() CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m customerMods) RandomEmail(f *faker.Faker) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Email = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m customerMods) RandomEmailNotNull(f *faker.Faker) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.Email = func() null.Val[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f, "255")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m customerMods) MarketingOptIn(val null.Val[bool]) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.MarketingOptIn = func() null.Val[bool] { return val }
	})
}

// Set the Column from the function
func (m customerMods) MarketingOptInFunc(f func() null.Val[bool]) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.MarketingOptIn = f
	})
}

// Clear any values for the column
func (m customerMods) UnsetMarketingOptIn() CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.MarketingOptIn = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m customerMods) RandomMarketingOptIn(f *faker.Faker) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.MarketingOptIn = func() null.Val[bool] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_bool(f, "1")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m customerMods) RandomMarketingOptInNotNull(f *faker.Faker) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.MarketingOptIn = func() null.Val[bool] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_bool(f, "1")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m customerMods) CreatedAt(val null.Val[time.Time]) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.CreatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m customerMods) CreatedAtFunc(f func() null.Val[time.Time]) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m customerMods) UnsetCreatedAt() CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m customerMods) RandomCreatedAt(f *faker.Faker) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m customerMods) RandomCreatedAtNotNull(f *faker.Faker) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m customerMods) UpdatedAt(val null.Val[time.Time]) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m customerMods) UpdatedAtFunc(f func() null.Val[time.Time]) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m customerMods) UnsetUpdatedAt() CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m customerMods) RandomUpdatedAt(f *faker.Faker) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m customerMods) RandomUpdatedAtNotNull(f *faker.Faker) CustomerMod {
	return CustomerModFunc(func(_ context.Context, o *CustomerTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m customerMods) WithParentsCascading() CustomerMod {
	return CustomerModFunc(func(ctx context.Context, o *CustomerTemplate) {
		if isDone, _ := customerWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = customerWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m customerMods) WithOrders(number int, related *OrderTemplate) CustomerMod {
	return CustomerModFunc(func(ctx context.Context, o *CustomerTemplate) {
		o.r.Orders = []*customerROrdersR{{
			number: number,
			o:      related,
		}}
	})
}

func (m customerMods) WithNewOrders(number int, mods ...OrderMod) CustomerMod {
	return CustomerModFunc(func(ctx context.Context, o *CustomerTemplate) {
		related := o.f.NewOrderWithContext(ctx, mods...)
		m.WithOrders(number, related).Apply(ctx, o)
	})
}

func (m customerMods) AddOrders(number int, related *OrderTemplate) CustomerMod {
	return CustomerModFunc(func(ctx context.Context, o *CustomerTemplate) {
		o.r.Orders = append(o.r.Orders, &customerROrdersR{
			number: number,
			o:      related,
		})
	})
}

func (m customerMods) AddNewOrders(number int, mods ...OrderMod) CustomerMod {
	return CustomerModFunc(func(ctx context.Context, o *CustomerTemplate) {
		related := o.f.NewOrderWithContext(ctx, mods...)
		m.AddOrders(number, related).Apply(ctx, o)
	})
}

func (m customerMods) AddExistingOrders(existingModels ...*models.Order) CustomerMod {
	return CustomerModFunc(func(ctx context.Context, o *CustomerTemplate) {
		for _, em := range existingModels {
			o.r.Orders = append(o.r.Orders, &customerROrdersR{
				o: o.f.FromExistingOrder(em),
			})
		}
	})
}

func (m customerMods) WithoutOrders() CustomerMod {
	return CustomerModFunc(func(ctx context.Context, o *CustomerTemplate) {
		o.r.Orders = nil
	})
}
