// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/acsellers/golang-db-compare/store/mysql/bob/models"
	"github.com/jaswdr/faker/v2"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

type DiscountMod interface {
	Apply(context.Context, *DiscountTemplate)
}

type DiscountModFunc func(context.Context, *DiscountTemplate)

func (f DiscountModFunc) Apply(ctx context.Context, n *DiscountTemplate) {
	f(ctx, n)
}

type DiscountModSlice []DiscountMod

func (mods DiscountModSlice) Apply(ctx context.Context, n *DiscountTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// DiscountTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type DiscountTemplate struct {
	ID           func() int64
	Name         func() string
	Category     func() string
	DiscountType func() string
	Discount     func() decimal.Decimal
	CreatedAt    func() null.Val[time.Time]
	UpdatedAt    func() null.Val[time.Time]

	r discountR
	f *Factory

	alreadyPersisted bool
}

type discountR struct {
	OrderItems []*discountROrderItemsR
	Orders     []*discountROrdersR
}

type discountROrderItemsR struct {
	number int
	o      *OrderItemTemplate
}
type discountROrdersR struct {
	number int
	o      *OrderTemplate
}

// Apply mods to the DiscountTemplate
func (o *DiscountTemplate) Apply(ctx context.Context, mods ...DiscountMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Discount
// according to the relationships in the template. Nothing is inserted into the db
func (t DiscountTemplate) setModelRels(o *models.Discount) {
	if t.r.OrderItems != nil {
		rel := models.OrderItemSlice{}
		for _, r := range t.r.OrderItems {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.DiscountID = null.From(o.ID) // h2
				rel.R.Discount = o
			}
			rel = append(rel, related...)
		}
		o.R.OrderItems = rel
	}

	if t.r.Orders != nil {
		rel := models.OrderSlice{}
		for _, r := range t.r.Orders {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.DiscountID = null.From(o.ID) // h2
				rel.R.Discount = o
			}
			rel = append(rel, related...)
		}
		o.R.Orders = rel
	}
}

// BuildSetter returns an *models.DiscountSetter
// this does nothing with the relationship templates
func (o DiscountTemplate) BuildSetter() *models.DiscountSetter {
	m := &models.DiscountSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.Category != nil {
		val := o.Category()
		m.Category = omit.From(val)
	}
	if o.DiscountType != nil {
		val := o.DiscountType()
		m.DiscountType = omit.From(val)
	}
	if o.Discount != nil {
		val := o.Discount()
		m.Discount = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omitnull.FromNull(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.DiscountSetter
// this does nothing with the relationship templates
func (o DiscountTemplate) BuildManySetter(number int) []*models.DiscountSetter {
	m := make([]*models.DiscountSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Discount
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use DiscountTemplate.Create
func (o DiscountTemplate) Build() *models.Discount {
	m := &models.Discount{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Category != nil {
		m.Category = o.Category()
	}
	if o.DiscountType != nil {
		m.DiscountType = o.DiscountType()
	}
	if o.Discount != nil {
		m.Discount = o.Discount()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.DiscountSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use DiscountTemplate.CreateMany
func (o DiscountTemplate) BuildMany(number int) models.DiscountSlice {
	m := make(models.DiscountSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableDiscount(m *models.DiscountSetter) {
	if !(m.Name.IsValue()) {
		val := random_string(nil, "255")
		m.Name = omit.From(val)
	}
	if !(m.Category.IsValue()) {
		val := random_string(nil, "32")
		m.Category = omit.From(val)
	}
	if !(m.DiscountType.IsValue()) {
		val := random_string(nil, "12")
		m.DiscountType = omit.From(val)
	}
	if !(m.Discount.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "4")
		m.Discount = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Discount
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *DiscountTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Discount) error {
	var err error

	isOrderItemsDone, _ := discountRelOrderItemsCtx.Value(ctx)
	if !isOrderItemsDone && o.r.OrderItems != nil {
		ctx = discountRelOrderItemsCtx.WithValue(ctx, true)
		for _, r := range o.r.OrderItems {
			if r.o.alreadyPersisted {
				m.R.OrderItems = append(m.R.OrderItems, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOrderItems(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isOrdersDone, _ := discountRelOrdersCtx.Value(ctx)
	if !isOrdersDone && o.r.Orders != nil {
		ctx = discountRelOrdersCtx.WithValue(ctx, true)
		for _, r := range o.r.Orders {
			if r.o.alreadyPersisted {
				m.R.Orders = append(m.R.Orders, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOrders(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a discount and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *DiscountTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Discount, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableDiscount(opt)

	m, err := models.Discounts.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a discount and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *DiscountTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Discount {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a discount and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *DiscountTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Discount {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple discounts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o DiscountTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.DiscountSlice, error) {
	var err error
	m := make(models.DiscountSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple discounts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o DiscountTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.DiscountSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple discounts and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o DiscountTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.DiscountSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Discount has methods that act as mods for the DiscountTemplate
var DiscountMods discountMods

type discountMods struct{}

func (m discountMods) RandomizeAllColumns(f *faker.Faker) DiscountMod {
	return DiscountModSlice{
		DiscountMods.RandomID(f),
		DiscountMods.RandomName(f),
		DiscountMods.RandomCategory(f),
		DiscountMods.RandomDiscountType(f),
		DiscountMods.RandomDiscount(f),
		DiscountMods.RandomCreatedAt(f),
		DiscountMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m discountMods) ID(val int64) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m discountMods) IDFunc(f func() int64) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m discountMods) UnsetID() DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m discountMods) RandomID(f *faker.Faker) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m discountMods) Name(val string) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m discountMods) NameFunc(f func() string) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m discountMods) UnsetName() DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m discountMods) RandomName(f *faker.Faker) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.Name = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m discountMods) Category(val string) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.Category = func() string { return val }
	})
}

// Set the Column from the function
func (m discountMods) CategoryFunc(f func() string) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.Category = f
	})
}

// Clear any values for the column
func (m discountMods) UnsetCategory() DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.Category = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m discountMods) RandomCategory(f *faker.Faker) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.Category = func() string {
			return random_string(f, "32")
		}
	})
}

// Set the model columns to this value
func (m discountMods) DiscountType(val string) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.DiscountType = func() string { return val }
	})
}

// Set the Column from the function
func (m discountMods) DiscountTypeFunc(f func() string) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.DiscountType = f
	})
}

// Clear any values for the column
func (m discountMods) UnsetDiscountType() DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.DiscountType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m discountMods) RandomDiscountType(f *faker.Faker) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.DiscountType = func() string {
			return random_string(f, "12")
		}
	})
}

// Set the model columns to this value
func (m discountMods) Discount(val decimal.Decimal) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.Discount = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m discountMods) DiscountFunc(f func() decimal.Decimal) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.Discount = f
	})
}

// Clear any values for the column
func (m discountMods) UnsetDiscount() DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.Discount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m discountMods) RandomDiscount(f *faker.Faker) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.Discount = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "4")
		}
	})
}

// Set the model columns to this value
func (m discountMods) CreatedAt(val null.Val[time.Time]) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.CreatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m discountMods) CreatedAtFunc(f func() null.Val[time.Time]) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m discountMods) UnsetCreatedAt() DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m discountMods) RandomCreatedAt(f *faker.Faker) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m discountMods) RandomCreatedAtNotNull(f *faker.Faker) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m discountMods) UpdatedAt(val null.Val[time.Time]) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m discountMods) UpdatedAtFunc(f func() null.Val[time.Time]) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m discountMods) UnsetUpdatedAt() DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m discountMods) RandomUpdatedAt(f *faker.Faker) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m discountMods) RandomUpdatedAtNotNull(f *faker.Faker) DiscountMod {
	return DiscountModFunc(func(_ context.Context, o *DiscountTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m discountMods) WithParentsCascading() DiscountMod {
	return DiscountModFunc(func(ctx context.Context, o *DiscountTemplate) {
		if isDone, _ := discountWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = discountWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m discountMods) WithOrderItems(number int, related *OrderItemTemplate) DiscountMod {
	return DiscountModFunc(func(ctx context.Context, o *DiscountTemplate) {
		o.r.OrderItems = []*discountROrderItemsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m discountMods) WithNewOrderItems(number int, mods ...OrderItemMod) DiscountMod {
	return DiscountModFunc(func(ctx context.Context, o *DiscountTemplate) {
		related := o.f.NewOrderItemWithContext(ctx, mods...)
		m.WithOrderItems(number, related).Apply(ctx, o)
	})
}

func (m discountMods) AddOrderItems(number int, related *OrderItemTemplate) DiscountMod {
	return DiscountModFunc(func(ctx context.Context, o *DiscountTemplate) {
		o.r.OrderItems = append(o.r.OrderItems, &discountROrderItemsR{
			number: number,
			o:      related,
		})
	})
}

func (m discountMods) AddNewOrderItems(number int, mods ...OrderItemMod) DiscountMod {
	return DiscountModFunc(func(ctx context.Context, o *DiscountTemplate) {
		related := o.f.NewOrderItemWithContext(ctx, mods...)
		m.AddOrderItems(number, related).Apply(ctx, o)
	})
}

func (m discountMods) AddExistingOrderItems(existingModels ...*models.OrderItem) DiscountMod {
	return DiscountModFunc(func(ctx context.Context, o *DiscountTemplate) {
		for _, em := range existingModels {
			o.r.OrderItems = append(o.r.OrderItems, &discountROrderItemsR{
				o: o.f.FromExistingOrderItem(em),
			})
		}
	})
}

func (m discountMods) WithoutOrderItems() DiscountMod {
	return DiscountModFunc(func(ctx context.Context, o *DiscountTemplate) {
		o.r.OrderItems = nil
	})
}

func (m discountMods) WithOrders(number int, related *OrderTemplate) DiscountMod {
	return DiscountModFunc(func(ctx context.Context, o *DiscountTemplate) {
		o.r.Orders = []*discountROrdersR{{
			number: number,
			o:      related,
		}}
	})
}

func (m discountMods) WithNewOrders(number int, mods ...OrderMod) DiscountMod {
	return DiscountModFunc(func(ctx context.Context, o *DiscountTemplate) {
		related := o.f.NewOrderWithContext(ctx, mods...)
		m.WithOrders(number, related).Apply(ctx, o)
	})
}

func (m discountMods) AddOrders(number int, related *OrderTemplate) DiscountMod {
	return DiscountModFunc(func(ctx context.Context, o *DiscountTemplate) {
		o.r.Orders = append(o.r.Orders, &discountROrdersR{
			number: number,
			o:      related,
		})
	})
}

func (m discountMods) AddNewOrders(number int, mods ...OrderMod) DiscountMod {
	return DiscountModFunc(func(ctx context.Context, o *DiscountTemplate) {
		related := o.f.NewOrderWithContext(ctx, mods...)
		m.AddOrders(number, related).Apply(ctx, o)
	})
}

func (m discountMods) AddExistingOrders(existingModels ...*models.Order) DiscountMod {
	return DiscountModFunc(func(ctx context.Context, o *DiscountTemplate) {
		for _, em := range existingModels {
			o.r.Orders = append(o.r.Orders, &discountROrdersR{
				o: o.f.FromExistingOrder(em),
			})
		}
	})
}

func (m discountMods) WithoutOrders() DiscountMod {
	return DiscountModFunc(func(ctx context.Context, o *DiscountTemplate) {
		o.r.Orders = nil
	})
}
