// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"time"

	"github.com/aarondl/opt/null"
	models "github.com/acsellers/golang-db-compare/store/mysql/bob/models"
	"github.com/jaswdr/faker/v2"
	"github.com/shopspring/decimal"
)

type ItemSummaryMod interface {
	Apply(context.Context, *ItemSummaryTemplate)
}

type ItemSummaryModFunc func(context.Context, *ItemSummaryTemplate)

func (f ItemSummaryModFunc) Apply(ctx context.Context, n *ItemSummaryTemplate) {
	f(ctx, n)
}

type ItemSummaryModSlice []ItemSummaryMod

func (mods ItemSummaryModSlice) Apply(ctx context.Context, n *ItemSummaryTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ItemSummaryTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ItemSummaryTemplate struct {
	ID            func() null.Val[int64]
	Name          func() string
	Category      func() string
	OrderType     func() string
	OrderDate     func() time.Time
	TotalQuantity func() null.Val[decimal.Decimal]
	TotalSales    func() null.Val[decimal.Decimal]
	OrderCount    func() int64

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the ItemSummaryTemplate
func (o *ItemSummaryTemplate) Apply(ctx context.Context, mods ...ItemSummaryMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.ItemSummary
// according to the relationships in the template. Nothing is inserted into the db
func (t ItemSummaryTemplate) setModelRels(o *models.ItemSummary) {}

// Build returns an *models.ItemSummary
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ItemSummaryTemplate.Create
func (o ItemSummaryTemplate) Build() *models.ItemSummary {
	m := &models.ItemSummary{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Category != nil {
		m.Category = o.Category()
	}
	if o.OrderType != nil {
		m.OrderType = o.OrderType()
	}
	if o.OrderDate != nil {
		m.OrderDate = o.OrderDate()
	}
	if o.TotalQuantity != nil {
		m.TotalQuantity = o.TotalQuantity()
	}
	if o.TotalSales != nil {
		m.TotalSales = o.TotalSales()
	}
	if o.OrderCount != nil {
		m.OrderCount = o.OrderCount()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ItemSummarySlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ItemSummaryTemplate.CreateMany
func (o ItemSummaryTemplate) BuildMany(number int) models.ItemSummarySlice {
	m := make(models.ItemSummarySlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

// ItemSummary has methods that act as mods for the ItemSummaryTemplate
var ItemSummaryMods itemSummaryMods

type itemSummaryMods struct{}

func (m itemSummaryMods) RandomizeAllColumns(f *faker.Faker) ItemSummaryMod {
	return ItemSummaryModSlice{
		ItemSummaryMods.RandomID(f),
		ItemSummaryMods.RandomName(f),
		ItemSummaryMods.RandomCategory(f),
		ItemSummaryMods.RandomOrderType(f),
		ItemSummaryMods.RandomOrderDate(f),
		ItemSummaryMods.RandomTotalQuantity(f),
		ItemSummaryMods.RandomTotalSales(f),
		ItemSummaryMods.RandomOrderCount(f),
	}
}

// Set the model columns to this value
func (m itemSummaryMods) ID(val null.Val[int64]) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.ID = func() null.Val[int64] { return val }
	})
}

// Set the Column from the function
func (m itemSummaryMods) IDFunc(f func() null.Val[int64]) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m itemSummaryMods) UnsetID() ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m itemSummaryMods) RandomID(f *faker.Faker) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.ID = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m itemSummaryMods) RandomIDNotNull(f *faker.Faker) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.ID = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m itemSummaryMods) Name(val string) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m itemSummaryMods) NameFunc(f func() string) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m itemSummaryMods) UnsetName() ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m itemSummaryMods) RandomName(f *faker.Faker) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.Name = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m itemSummaryMods) Category(val string) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.Category = func() string { return val }
	})
}

// Set the Column from the function
func (m itemSummaryMods) CategoryFunc(f func() string) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.Category = f
	})
}

// Clear any values for the column
func (m itemSummaryMods) UnsetCategory() ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.Category = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m itemSummaryMods) RandomCategory(f *faker.Faker) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.Category = func() string {
			return random_string(f, "32")
		}
	})
}

// Set the model columns to this value
func (m itemSummaryMods) OrderType(val string) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.OrderType = func() string { return val }
	})
}

// Set the Column from the function
func (m itemSummaryMods) OrderTypeFunc(f func() string) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.OrderType = f
	})
}

// Clear any values for the column
func (m itemSummaryMods) UnsetOrderType() ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.OrderType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m itemSummaryMods) RandomOrderType(f *faker.Faker) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.OrderType = func() string {
			return random_string(f, "12")
		}
	})
}

// Set the model columns to this value
func (m itemSummaryMods) OrderDate(val time.Time) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.OrderDate = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m itemSummaryMods) OrderDateFunc(f func() time.Time) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.OrderDate = f
	})
}

// Clear any values for the column
func (m itemSummaryMods) UnsetOrderDate() ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.OrderDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m itemSummaryMods) RandomOrderDate(f *faker.Faker) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.OrderDate = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m itemSummaryMods) TotalQuantity(val null.Val[decimal.Decimal]) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.TotalQuantity = func() null.Val[decimal.Decimal] { return val }
	})
}

// Set the Column from the function
func (m itemSummaryMods) TotalQuantityFunc(f func() null.Val[decimal.Decimal]) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.TotalQuantity = f
	})
}

// Clear any values for the column
func (m itemSummaryMods) UnsetTotalQuantity() ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.TotalQuantity = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m itemSummaryMods) RandomTotalQuantity(f *faker.Faker) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.TotalQuantity = func() null.Val[decimal.Decimal] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_decimal_Decimal(f, "32", "0")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m itemSummaryMods) RandomTotalQuantityNotNull(f *faker.Faker) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.TotalQuantity = func() null.Val[decimal.Decimal] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_decimal_Decimal(f, "32", "0")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m itemSummaryMods) TotalSales(val null.Val[decimal.Decimal]) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.TotalSales = func() null.Val[decimal.Decimal] { return val }
	})
}

// Set the Column from the function
func (m itemSummaryMods) TotalSalesFunc(f func() null.Val[decimal.Decimal]) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.TotalSales = f
	})
}

// Clear any values for the column
func (m itemSummaryMods) UnsetTotalSales() ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.TotalSales = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m itemSummaryMods) RandomTotalSales(f *faker.Faker) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.TotalSales = func() null.Val[decimal.Decimal] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_decimal_Decimal(f, "42", "2")
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m itemSummaryMods) RandomTotalSalesNotNull(f *faker.Faker) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.TotalSales = func() null.Val[decimal.Decimal] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_decimal_Decimal(f, "42", "2")
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m itemSummaryMods) OrderCount(val int64) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.OrderCount = func() int64 { return val }
	})
}

// Set the Column from the function
func (m itemSummaryMods) OrderCountFunc(f func() int64) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.OrderCount = f
	})
}

// Clear any values for the column
func (m itemSummaryMods) UnsetOrderCount() ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.OrderCount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m itemSummaryMods) RandomOrderCount(f *faker.Faker) ItemSummaryMod {
	return ItemSummaryModFunc(func(_ context.Context, o *ItemSummaryTemplate) {
		o.OrderCount = func() int64 {
			return random_int64(f)
		}
	})
}

func (m itemSummaryMods) WithParentsCascading() ItemSummaryMod {
	return ItemSummaryModFunc(func(ctx context.Context, o *ItemSummaryTemplate) {
		if isDone, _ := itemSummaryWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = itemSummaryWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
