// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/acsellers/golang-db-compare/store/mysql/bob/models"
	"github.com/jaswdr/faker/v2"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

type LocationMod interface {
	Apply(context.Context, *LocationTemplate)
}

type LocationModFunc func(context.Context, *LocationTemplate)

func (f LocationModFunc) Apply(ctx context.Context, n *LocationTemplate) {
	f(ctx, n)
}

type LocationModSlice []LocationMod

func (mods LocationModSlice) Apply(ctx context.Context, n *LocationTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// LocationTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type LocationTemplate struct {
	ID        func() int64
	Name      func() string
	Address   func() string
	City      func() string
	State     func() string
	Zip       func() string
	TaxRate   func() decimal.Decimal
	CreatedAt func() null.Val[time.Time]
	UpdatedAt func() null.Val[time.Time]

	r locationR
	f *Factory

	alreadyPersisted bool
}

type locationR struct {
	JoinLocationCustomers []*locationRJoinLocationCustomersR
	LastLocationCustomers []*locationRLastLocationCustomersR
	Orders                []*locationROrdersR
}

type locationRJoinLocationCustomersR struct {
	number int
	o      *CustomerTemplate
}
type locationRLastLocationCustomersR struct {
	number int
	o      *CustomerTemplate
}
type locationROrdersR struct {
	number int
	o      *OrderTemplate
}

// Apply mods to the LocationTemplate
func (o *LocationTemplate) Apply(ctx context.Context, mods ...LocationMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Location
// according to the relationships in the template. Nothing is inserted into the db
func (t LocationTemplate) setModelRels(o *models.Location) {
	if t.r.JoinLocationCustomers != nil {
		rel := models.CustomerSlice{}
		for _, r := range t.r.JoinLocationCustomers {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.JoinLocationID = null.From(o.ID) // h2
				rel.R.JoinLocationLocation = o
			}
			rel = append(rel, related...)
		}
		o.R.JoinLocationCustomers = rel
	}

	if t.r.LastLocationCustomers != nil {
		rel := models.CustomerSlice{}
		for _, r := range t.r.LastLocationCustomers {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.LastLocationID = null.From(o.ID) // h2
				rel.R.LastLocationLocation = o
			}
			rel = append(rel, related...)
		}
		o.R.LastLocationCustomers = rel
	}

	if t.r.Orders != nil {
		rel := models.OrderSlice{}
		for _, r := range t.r.Orders {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.LocationID = null.From(o.ID) // h2
				rel.R.Location = o
			}
			rel = append(rel, related...)
		}
		o.R.Orders = rel
	}
}

// BuildSetter returns an *models.LocationSetter
// this does nothing with the relationship templates
func (o LocationTemplate) BuildSetter() *models.LocationSetter {
	m := &models.LocationSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.Address != nil {
		val := o.Address()
		m.Address = omit.From(val)
	}
	if o.City != nil {
		val := o.City()
		m.City = omit.From(val)
	}
	if o.State != nil {
		val := o.State()
		m.State = omit.From(val)
	}
	if o.Zip != nil {
		val := o.Zip()
		m.Zip = omit.From(val)
	}
	if o.TaxRate != nil {
		val := o.TaxRate()
		m.TaxRate = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omitnull.FromNull(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.LocationSetter
// this does nothing with the relationship templates
func (o LocationTemplate) BuildManySetter(number int) []*models.LocationSetter {
	m := make([]*models.LocationSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Location
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use LocationTemplate.Create
func (o LocationTemplate) Build() *models.Location {
	m := &models.Location{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Address != nil {
		m.Address = o.Address()
	}
	if o.City != nil {
		m.City = o.City()
	}
	if o.State != nil {
		m.State = o.State()
	}
	if o.Zip != nil {
		m.Zip = o.Zip()
	}
	if o.TaxRate != nil {
		m.TaxRate = o.TaxRate()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.LocationSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use LocationTemplate.CreateMany
func (o LocationTemplate) BuildMany(number int) models.LocationSlice {
	m := make(models.LocationSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableLocation(m *models.LocationSetter) {
	if !(m.Name.IsValue()) {
		val := random_string(nil, "255")
		m.Name = omit.From(val)
	}
	if !(m.Address.IsValue()) {
		val := random_string(nil, "255")
		m.Address = omit.From(val)
	}
	if !(m.City.IsValue()) {
		val := random_string(nil, "255")
		m.City = omit.From(val)
	}
	if !(m.State.IsValue()) {
		val := random_string(nil, "32")
		m.State = omit.From(val)
	}
	if !(m.Zip.IsValue()) {
		val := random_string(nil, "5")
		m.Zip = omit.From(val)
	}
	if !(m.TaxRate.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "4")
		m.TaxRate = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Location
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *LocationTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Location) error {
	var err error

	isJoinLocationCustomersDone, _ := locationRelJoinLocationCustomersCtx.Value(ctx)
	if !isJoinLocationCustomersDone && o.r.JoinLocationCustomers != nil {
		ctx = locationRelJoinLocationCustomersCtx.WithValue(ctx, true)
		for _, r := range o.r.JoinLocationCustomers {
			if r.o.alreadyPersisted {
				m.R.JoinLocationCustomers = append(m.R.JoinLocationCustomers, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachJoinLocationCustomers(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isLastLocationCustomersDone, _ := locationRelLastLocationCustomersCtx.Value(ctx)
	if !isLastLocationCustomersDone && o.r.LastLocationCustomers != nil {
		ctx = locationRelLastLocationCustomersCtx.WithValue(ctx, true)
		for _, r := range o.r.LastLocationCustomers {
			if r.o.alreadyPersisted {
				m.R.LastLocationCustomers = append(m.R.LastLocationCustomers, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachLastLocationCustomers(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isOrdersDone, _ := locationRelOrdersCtx.Value(ctx)
	if !isOrdersDone && o.r.Orders != nil {
		ctx = locationRelOrdersCtx.WithValue(ctx, true)
		for _, r := range o.r.Orders {
			if r.o.alreadyPersisted {
				m.R.Orders = append(m.R.Orders, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOrders(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a location and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *LocationTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Location, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableLocation(opt)

	m, err := models.Locations.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a location and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *LocationTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Location {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a location and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *LocationTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Location {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple locations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o LocationTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.LocationSlice, error) {
	var err error
	m := make(models.LocationSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple locations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o LocationTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.LocationSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple locations and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o LocationTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.LocationSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Location has methods that act as mods for the LocationTemplate
var LocationMods locationMods

type locationMods struct{}

func (m locationMods) RandomizeAllColumns(f *faker.Faker) LocationMod {
	return LocationModSlice{
		LocationMods.RandomID(f),
		LocationMods.RandomName(f),
		LocationMods.RandomAddress(f),
		LocationMods.RandomCity(f),
		LocationMods.RandomState(f),
		LocationMods.RandomZip(f),
		LocationMods.RandomTaxRate(f),
		LocationMods.RandomCreatedAt(f),
		LocationMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m locationMods) ID(val int64) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m locationMods) IDFunc(f func() int64) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m locationMods) UnsetID() LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m locationMods) RandomID(f *faker.Faker) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m locationMods) Name(val string) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m locationMods) NameFunc(f func() string) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m locationMods) UnsetName() LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m locationMods) RandomName(f *faker.Faker) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.Name = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m locationMods) Address(val string) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.Address = func() string { return val }
	})
}

// Set the Column from the function
func (m locationMods) AddressFunc(f func() string) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.Address = f
	})
}

// Clear any values for the column
func (m locationMods) UnsetAddress() LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.Address = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m locationMods) RandomAddress(f *faker.Faker) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.Address = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m locationMods) City(val string) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.City = func() string { return val }
	})
}

// Set the Column from the function
func (m locationMods) CityFunc(f func() string) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.City = f
	})
}

// Clear any values for the column
func (m locationMods) UnsetCity() LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.City = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m locationMods) RandomCity(f *faker.Faker) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.City = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m locationMods) State(val string) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.State = func() string { return val }
	})
}

// Set the Column from the function
func (m locationMods) StateFunc(f func() string) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.State = f
	})
}

// Clear any values for the column
func (m locationMods) UnsetState() LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.State = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m locationMods) RandomState(f *faker.Faker) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.State = func() string {
			return random_string(f, "32")
		}
	})
}

// Set the model columns to this value
func (m locationMods) Zip(val string) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.Zip = func() string { return val }
	})
}

// Set the Column from the function
func (m locationMods) ZipFunc(f func() string) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.Zip = f
	})
}

// Clear any values for the column
func (m locationMods) UnsetZip() LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.Zip = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m locationMods) RandomZip(f *faker.Faker) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.Zip = func() string {
			return random_string(f, "5")
		}
	})
}

// Set the model columns to this value
func (m locationMods) TaxRate(val decimal.Decimal) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.TaxRate = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m locationMods) TaxRateFunc(f func() decimal.Decimal) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.TaxRate = f
	})
}

// Clear any values for the column
func (m locationMods) UnsetTaxRate() LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.TaxRate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m locationMods) RandomTaxRate(f *faker.Faker) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.TaxRate = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "4")
		}
	})
}

// Set the model columns to this value
func (m locationMods) CreatedAt(val null.Val[time.Time]) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.CreatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m locationMods) CreatedAtFunc(f func() null.Val[time.Time]) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m locationMods) UnsetCreatedAt() LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m locationMods) RandomCreatedAt(f *faker.Faker) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m locationMods) RandomCreatedAtNotNull(f *faker.Faker) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m locationMods) UpdatedAt(val null.Val[time.Time]) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m locationMods) UpdatedAtFunc(f func() null.Val[time.Time]) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m locationMods) UnsetUpdatedAt() LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m locationMods) RandomUpdatedAt(f *faker.Faker) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m locationMods) RandomUpdatedAtNotNull(f *faker.Faker) LocationMod {
	return LocationModFunc(func(_ context.Context, o *LocationTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m locationMods) WithParentsCascading() LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		if isDone, _ := locationWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = locationWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m locationMods) WithJoinLocationCustomers(number int, related *CustomerTemplate) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		o.r.JoinLocationCustomers = []*locationRJoinLocationCustomersR{{
			number: number,
			o:      related,
		}}
	})
}

func (m locationMods) WithNewJoinLocationCustomers(number int, mods ...CustomerMod) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		related := o.f.NewCustomerWithContext(ctx, mods...)
		m.WithJoinLocationCustomers(number, related).Apply(ctx, o)
	})
}

func (m locationMods) AddJoinLocationCustomers(number int, related *CustomerTemplate) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		o.r.JoinLocationCustomers = append(o.r.JoinLocationCustomers, &locationRJoinLocationCustomersR{
			number: number,
			o:      related,
		})
	})
}

func (m locationMods) AddNewJoinLocationCustomers(number int, mods ...CustomerMod) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		related := o.f.NewCustomerWithContext(ctx, mods...)
		m.AddJoinLocationCustomers(number, related).Apply(ctx, o)
	})
}

func (m locationMods) AddExistingJoinLocationCustomers(existingModels ...*models.Customer) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		for _, em := range existingModels {
			o.r.JoinLocationCustomers = append(o.r.JoinLocationCustomers, &locationRJoinLocationCustomersR{
				o: o.f.FromExistingCustomer(em),
			})
		}
	})
}

func (m locationMods) WithoutJoinLocationCustomers() LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		o.r.JoinLocationCustomers = nil
	})
}

func (m locationMods) WithLastLocationCustomers(number int, related *CustomerTemplate) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		o.r.LastLocationCustomers = []*locationRLastLocationCustomersR{{
			number: number,
			o:      related,
		}}
	})
}

func (m locationMods) WithNewLastLocationCustomers(number int, mods ...CustomerMod) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		related := o.f.NewCustomerWithContext(ctx, mods...)
		m.WithLastLocationCustomers(number, related).Apply(ctx, o)
	})
}

func (m locationMods) AddLastLocationCustomers(number int, related *CustomerTemplate) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		o.r.LastLocationCustomers = append(o.r.LastLocationCustomers, &locationRLastLocationCustomersR{
			number: number,
			o:      related,
		})
	})
}

func (m locationMods) AddNewLastLocationCustomers(number int, mods ...CustomerMod) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		related := o.f.NewCustomerWithContext(ctx, mods...)
		m.AddLastLocationCustomers(number, related).Apply(ctx, o)
	})
}

func (m locationMods) AddExistingLastLocationCustomers(existingModels ...*models.Customer) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		for _, em := range existingModels {
			o.r.LastLocationCustomers = append(o.r.LastLocationCustomers, &locationRLastLocationCustomersR{
				o: o.f.FromExistingCustomer(em),
			})
		}
	})
}

func (m locationMods) WithoutLastLocationCustomers() LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		o.r.LastLocationCustomers = nil
	})
}

func (m locationMods) WithOrders(number int, related *OrderTemplate) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		o.r.Orders = []*locationROrdersR{{
			number: number,
			o:      related,
		}}
	})
}

func (m locationMods) WithNewOrders(number int, mods ...OrderMod) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		related := o.f.NewOrderWithContext(ctx, mods...)
		m.WithOrders(number, related).Apply(ctx, o)
	})
}

func (m locationMods) AddOrders(number int, related *OrderTemplate) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		o.r.Orders = append(o.r.Orders, &locationROrdersR{
			number: number,
			o:      related,
		})
	})
}

func (m locationMods) AddNewOrders(number int, mods ...OrderMod) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		related := o.f.NewOrderWithContext(ctx, mods...)
		m.AddOrders(number, related).Apply(ctx, o)
	})
}

func (m locationMods) AddExistingOrders(existingModels ...*models.Order) LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		for _, em := range existingModels {
			o.r.Orders = append(o.r.Orders, &locationROrdersR{
				o: o.f.FromExistingOrder(em),
			})
		}
	})
}

func (m locationMods) WithoutOrders() LocationMod {
	return LocationModFunc(func(ctx context.Context, o *LocationTemplate) {
		o.r.Orders = nil
	})
}
