// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/acsellers/golang-db-compare/store/mysql/bob/models"
	"github.com/jaswdr/faker/v2"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

type OrderMod interface {
	Apply(context.Context, *OrderTemplate)
}

type OrderModFunc func(context.Context, *OrderTemplate)

func (f OrderModFunc) Apply(ctx context.Context, n *OrderTemplate) {
	f(ctx, n)
}

type OrderModSlice []OrderMod

func (mods OrderModSlice) Apply(ctx context.Context, n *OrderTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// OrderTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type OrderTemplate struct {
	ID             func() int64
	OrderDate      func() time.Time
	CustomerID     func() null.Val[int64]
	DiscountID     func() null.Val[int64]
	OrderType      func() string
	Subtotal       func() decimal.Decimal
	DiscountAmount func() decimal.Decimal
	TaxAmount      func() decimal.Decimal
	Total          func() decimal.Decimal
	CreatedAt      func() null.Val[time.Time]
	UpdatedAt      func() null.Val[time.Time]

	r orderR
	f *Factory

	alreadyPersisted bool
}

type orderR struct {
	OrderItems    []*orderROrderItemsR
	OrderPayments []*orderROrderPaymentsR
	Customer      *orderRCustomerR
	Discount      *orderRDiscountR
}

type orderROrderItemsR struct {
	number int
	o      *OrderItemTemplate
}
type orderROrderPaymentsR struct {
	number int
	o      *OrderPaymentTemplate
}
type orderRCustomerR struct {
	o *CustomerTemplate
}
type orderRDiscountR struct {
	o *DiscountTemplate
}

// Apply mods to the OrderTemplate
func (o *OrderTemplate) Apply(ctx context.Context, mods ...OrderMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Order
// according to the relationships in the template. Nothing is inserted into the db
func (t OrderTemplate) setModelRels(o *models.Order) {
	if t.r.OrderItems != nil {
		rel := models.OrderItemSlice{}
		for _, r := range t.r.OrderItems {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.OrderID = o.ID // h2
				rel.R.Order = o
			}
			rel = append(rel, related...)
		}
		o.R.OrderItems = rel
	}

	if t.r.OrderPayments != nil {
		rel := models.OrderPaymentSlice{}
		for _, r := range t.r.OrderPayments {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.OrderID = o.ID // h2
				rel.R.Order = o
			}
			rel = append(rel, related...)
		}
		o.R.OrderPayments = rel
	}

	if t.r.Customer != nil {
		rel := t.r.Customer.o.Build()
		rel.R.Orders = append(rel.R.Orders, o)
		o.CustomerID = null.From(rel.ID) // h2
		o.R.Customer = rel
	}

	if t.r.Discount != nil {
		rel := t.r.Discount.o.Build()
		rel.R.Orders = append(rel.R.Orders, o)
		o.DiscountID = null.From(rel.ID) // h2
		o.R.Discount = rel
	}
}

// BuildSetter returns an *models.OrderSetter
// this does nothing with the relationship templates
func (o OrderTemplate) BuildSetter() *models.OrderSetter {
	m := &models.OrderSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.OrderDate != nil {
		val := o.OrderDate()
		m.OrderDate = omit.From(val)
	}
	if o.CustomerID != nil {
		val := o.CustomerID()
		m.CustomerID = omitnull.FromNull(val)
	}
	if o.DiscountID != nil {
		val := o.DiscountID()
		m.DiscountID = omitnull.FromNull(val)
	}
	if o.OrderType != nil {
		val := o.OrderType()
		m.OrderType = omit.From(val)
	}
	if o.Subtotal != nil {
		val := o.Subtotal()
		m.Subtotal = omit.From(val)
	}
	if o.DiscountAmount != nil {
		val := o.DiscountAmount()
		m.DiscountAmount = omit.From(val)
	}
	if o.TaxAmount != nil {
		val := o.TaxAmount()
		m.TaxAmount = omit.From(val)
	}
	if o.Total != nil {
		val := o.Total()
		m.Total = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omitnull.FromNull(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.OrderSetter
// this does nothing with the relationship templates
func (o OrderTemplate) BuildManySetter(number int) []*models.OrderSetter {
	m := make([]*models.OrderSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Order
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrderTemplate.Create
func (o OrderTemplate) Build() *models.Order {
	m := &models.Order{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.OrderDate != nil {
		m.OrderDate = o.OrderDate()
	}
	if o.CustomerID != nil {
		m.CustomerID = o.CustomerID()
	}
	if o.DiscountID != nil {
		m.DiscountID = o.DiscountID()
	}
	if o.OrderType != nil {
		m.OrderType = o.OrderType()
	}
	if o.Subtotal != nil {
		m.Subtotal = o.Subtotal()
	}
	if o.DiscountAmount != nil {
		m.DiscountAmount = o.DiscountAmount()
	}
	if o.TaxAmount != nil {
		m.TaxAmount = o.TaxAmount()
	}
	if o.Total != nil {
		m.Total = o.Total()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.OrderSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use OrderTemplate.CreateMany
func (o OrderTemplate) BuildMany(number int) models.OrderSlice {
	m := make(models.OrderSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableOrder(m *models.OrderSetter) {
	if !(m.OrderDate.IsValue()) {
		val := random_time_Time(nil)
		m.OrderDate = omit.From(val)
	}
	if !(m.OrderType.IsValue()) {
		val := random_string(nil, "12")
		m.OrderType = omit.From(val)
	}
	if !(m.Subtotal.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "2")
		m.Subtotal = omit.From(val)
	}
	if !(m.DiscountAmount.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "2")
		m.DiscountAmount = omit.From(val)
	}
	if !(m.TaxAmount.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "2")
		m.TaxAmount = omit.From(val)
	}
	if !(m.Total.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "2")
		m.Total = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Order
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *OrderTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Order) error {
	var err error

	isOrderItemsDone, _ := orderRelOrderItemsCtx.Value(ctx)
	if !isOrderItemsDone && o.r.OrderItems != nil {
		ctx = orderRelOrderItemsCtx.WithValue(ctx, true)
		for _, r := range o.r.OrderItems {
			if r.o.alreadyPersisted {
				m.R.OrderItems = append(m.R.OrderItems, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOrderItems(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isOrderPaymentsDone, _ := orderRelOrderPaymentsCtx.Value(ctx)
	if !isOrderPaymentsDone && o.r.OrderPayments != nil {
		ctx = orderRelOrderPaymentsCtx.WithValue(ctx, true)
		for _, r := range o.r.OrderPayments {
			if r.o.alreadyPersisted {
				m.R.OrderPayments = append(m.R.OrderPayments, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOrderPayments(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isCustomerDone, _ := orderRelCustomerCtx.Value(ctx)
	if !isCustomerDone && o.r.Customer != nil {
		ctx = orderRelCustomerCtx.WithValue(ctx, true)
		if o.r.Customer.o.alreadyPersisted {
			m.R.Customer = o.r.Customer.o.Build()
		} else {
			var rel2 *models.Customer
			rel2, err = o.r.Customer.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachCustomer(ctx, exec, rel2)
			if err != nil {
				return err
			}
		}

	}

	isDiscountDone, _ := orderRelDiscountCtx.Value(ctx)
	if !isDiscountDone && o.r.Discount != nil {
		ctx = orderRelDiscountCtx.WithValue(ctx, true)
		if o.r.Discount.o.alreadyPersisted {
			m.R.Discount = o.r.Discount.o.Build()
		} else {
			var rel3 *models.Discount
			rel3, err = o.r.Discount.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachDiscount(ctx, exec, rel3)
			if err != nil {
				return err
			}
		}

	}

	return err
}

// Create builds a order and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *OrderTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Order, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableOrder(opt)

	m, err := models.Orders.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a order and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *OrderTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Order {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a order and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *OrderTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Order {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple orders and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o OrderTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.OrderSlice, error) {
	var err error
	m := make(models.OrderSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple orders and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o OrderTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.OrderSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple orders and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o OrderTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.OrderSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Order has methods that act as mods for the OrderTemplate
var OrderMods orderMods

type orderMods struct{}

func (m orderMods) RandomizeAllColumns(f *faker.Faker) OrderMod {
	return OrderModSlice{
		OrderMods.RandomID(f),
		OrderMods.RandomOrderDate(f),
		OrderMods.RandomCustomerID(f),
		OrderMods.RandomDiscountID(f),
		OrderMods.RandomOrderType(f),
		OrderMods.RandomSubtotal(f),
		OrderMods.RandomDiscountAmount(f),
		OrderMods.RandomTaxAmount(f),
		OrderMods.RandomTotal(f),
		OrderMods.RandomCreatedAt(f),
		OrderMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m orderMods) ID(val int64) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m orderMods) IDFunc(f func() int64) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetID() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomID(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m orderMods) OrderDate(val time.Time) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.OrderDate = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m orderMods) OrderDateFunc(f func() time.Time) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.OrderDate = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetOrderDate() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.OrderDate = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomOrderDate(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.OrderDate = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m orderMods) CustomerID(val null.Val[int64]) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CustomerID = func() null.Val[int64] { return val }
	})
}

// Set the Column from the function
func (m orderMods) CustomerIDFunc(f func() null.Val[int64]) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CustomerID = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetCustomerID() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CustomerID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m orderMods) RandomCustomerID(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CustomerID = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m orderMods) RandomCustomerIDNotNull(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CustomerID = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m orderMods) DiscountID(val null.Val[int64]) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountID = func() null.Val[int64] { return val }
	})
}

// Set the Column from the function
func (m orderMods) DiscountIDFunc(f func() null.Val[int64]) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountID = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetDiscountID() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m orderMods) RandomDiscountID(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountID = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m orderMods) RandomDiscountIDNotNull(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountID = func() null.Val[int64] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_int64(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m orderMods) OrderType(val string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.OrderType = func() string { return val }
	})
}

// Set the Column from the function
func (m orderMods) OrderTypeFunc(f func() string) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.OrderType = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetOrderType() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.OrderType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomOrderType(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.OrderType = func() string {
			return random_string(f, "12")
		}
	})
}

// Set the model columns to this value
func (m orderMods) Subtotal(val decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Subtotal = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m orderMods) SubtotalFunc(f func() decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Subtotal = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetSubtotal() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Subtotal = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomSubtotal(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Subtotal = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "2")
		}
	})
}

// Set the model columns to this value
func (m orderMods) DiscountAmount(val decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountAmount = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m orderMods) DiscountAmountFunc(f func() decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountAmount = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetDiscountAmount() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountAmount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomDiscountAmount(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.DiscountAmount = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "2")
		}
	})
}

// Set the model columns to this value
func (m orderMods) TaxAmount(val decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.TaxAmount = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m orderMods) TaxAmountFunc(f func() decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.TaxAmount = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetTaxAmount() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.TaxAmount = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomTaxAmount(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.TaxAmount = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "2")
		}
	})
}

// Set the model columns to this value
func (m orderMods) Total(val decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Total = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m orderMods) TotalFunc(f func() decimal.Decimal) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Total = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetTotal() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Total = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m orderMods) RandomTotal(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.Total = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "2")
		}
	})
}

// Set the model columns to this value
func (m orderMods) CreatedAt(val null.Val[time.Time]) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CreatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m orderMods) CreatedAtFunc(f func() null.Val[time.Time]) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetCreatedAt() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m orderMods) RandomCreatedAt(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m orderMods) RandomCreatedAtNotNull(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m orderMods) UpdatedAt(val null.Val[time.Time]) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m orderMods) UpdatedAtFunc(f func() null.Val[time.Time]) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m orderMods) UnsetUpdatedAt() OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m orderMods) RandomUpdatedAt(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m orderMods) RandomUpdatedAtNotNull(f *faker.Faker) OrderMod {
	return OrderModFunc(func(_ context.Context, o *OrderTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m orderMods) WithParentsCascading() OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		if isDone, _ := orderWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = orderWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewCustomerWithContext(ctx, CustomerMods.WithParentsCascading())
			m.WithCustomer(related).Apply(ctx, o)
		}
		{

			related := o.f.NewDiscountWithContext(ctx, DiscountMods.WithParentsCascading())
			m.WithDiscount(related).Apply(ctx, o)
		}
	})
}

func (m orderMods) WithCustomer(rel *CustomerTemplate) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.Customer = &orderRCustomerR{
			o: rel,
		}
	})
}

func (m orderMods) WithNewCustomer(mods ...CustomerMod) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		related := o.f.NewCustomerWithContext(ctx, mods...)

		m.WithCustomer(related).Apply(ctx, o)
	})
}

func (m orderMods) WithExistingCustomer(em *models.Customer) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.Customer = &orderRCustomerR{
			o: o.f.FromExistingCustomer(em),
		}
	})
}

func (m orderMods) WithoutCustomer() OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.Customer = nil
	})
}

func (m orderMods) WithDiscount(rel *DiscountTemplate) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.Discount = &orderRDiscountR{
			o: rel,
		}
	})
}

func (m orderMods) WithNewDiscount(mods ...DiscountMod) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		related := o.f.NewDiscountWithContext(ctx, mods...)

		m.WithDiscount(related).Apply(ctx, o)
	})
}

func (m orderMods) WithExistingDiscount(em *models.Discount) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.Discount = &orderRDiscountR{
			o: o.f.FromExistingDiscount(em),
		}
	})
}

func (m orderMods) WithoutDiscount() OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.Discount = nil
	})
}

func (m orderMods) WithOrderItems(number int, related *OrderItemTemplate) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.OrderItems = []*orderROrderItemsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m orderMods) WithNewOrderItems(number int, mods ...OrderItemMod) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		related := o.f.NewOrderItemWithContext(ctx, mods...)
		m.WithOrderItems(number, related).Apply(ctx, o)
	})
}

func (m orderMods) AddOrderItems(number int, related *OrderItemTemplate) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.OrderItems = append(o.r.OrderItems, &orderROrderItemsR{
			number: number,
			o:      related,
		})
	})
}

func (m orderMods) AddNewOrderItems(number int, mods ...OrderItemMod) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		related := o.f.NewOrderItemWithContext(ctx, mods...)
		m.AddOrderItems(number, related).Apply(ctx, o)
	})
}

func (m orderMods) AddExistingOrderItems(existingModels ...*models.OrderItem) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		for _, em := range existingModels {
			o.r.OrderItems = append(o.r.OrderItems, &orderROrderItemsR{
				o: o.f.FromExistingOrderItem(em),
			})
		}
	})
}

func (m orderMods) WithoutOrderItems() OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.OrderItems = nil
	})
}

func (m orderMods) WithOrderPayments(number int, related *OrderPaymentTemplate) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.OrderPayments = []*orderROrderPaymentsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m orderMods) WithNewOrderPayments(number int, mods ...OrderPaymentMod) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		related := o.f.NewOrderPaymentWithContext(ctx, mods...)
		m.WithOrderPayments(number, related).Apply(ctx, o)
	})
}

func (m orderMods) AddOrderPayments(number int, related *OrderPaymentTemplate) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.OrderPayments = append(o.r.OrderPayments, &orderROrderPaymentsR{
			number: number,
			o:      related,
		})
	})
}

func (m orderMods) AddNewOrderPayments(number int, mods ...OrderPaymentMod) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		related := o.f.NewOrderPaymentWithContext(ctx, mods...)
		m.AddOrderPayments(number, related).Apply(ctx, o)
	})
}

func (m orderMods) AddExistingOrderPayments(existingModels ...*models.OrderPayment) OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		for _, em := range existingModels {
			o.r.OrderPayments = append(o.r.OrderPayments, &orderROrderPaymentsR{
				o: o.f.FromExistingOrderPayment(em),
			})
		}
	})
}

func (m orderMods) WithoutOrderPayments() OrderMod {
	return OrderModFunc(func(ctx context.Context, o *OrderTemplate) {
		o.r.OrderPayments = nil
	})
}
