// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/acsellers/golang-db-compare/store/mysql/bob/models"
	"github.com/jaswdr/faker/v2"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
)

type ProductMod interface {
	Apply(context.Context, *ProductTemplate)
}

type ProductModFunc func(context.Context, *ProductTemplate)

func (f ProductModFunc) Apply(ctx context.Context, n *ProductTemplate) {
	f(ctx, n)
}

type ProductModSlice []ProductMod

func (mods ProductModSlice) Apply(ctx context.Context, n *ProductTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ProductTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ProductTemplate struct {
	ID        func() int64
	Name      func() string
	Category  func() string
	Price     func() decimal.Decimal
	CreatedAt func() null.Val[time.Time]
	UpdatedAt func() null.Val[time.Time]

	r productR
	f *Factory

	alreadyPersisted bool
}

type productR struct {
	OrderItems []*productROrderItemsR
}

type productROrderItemsR struct {
	number int
	o      *OrderItemTemplate
}

// Apply mods to the ProductTemplate
func (o *ProductTemplate) Apply(ctx context.Context, mods ...ProductMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Product
// according to the relationships in the template. Nothing is inserted into the db
func (t ProductTemplate) setModelRels(o *models.Product) {
	if t.r.OrderItems != nil {
		rel := models.OrderItemSlice{}
		for _, r := range t.r.OrderItems {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ProductID = o.ID // h2
				rel.R.Product = o
			}
			rel = append(rel, related...)
		}
		o.R.OrderItems = rel
	}
}

// BuildSetter returns an *models.ProductSetter
// this does nothing with the relationship templates
func (o ProductTemplate) BuildSetter() *models.ProductSetter {
	m := &models.ProductSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.Category != nil {
		val := o.Category()
		m.Category = omit.From(val)
	}
	if o.Price != nil {
		val := o.Price()
		m.Price = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omitnull.FromNull(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.ProductSetter
// this does nothing with the relationship templates
func (o ProductTemplate) BuildManySetter(number int) []*models.ProductSetter {
	m := make([]*models.ProductSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Product
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ProductTemplate.Create
func (o ProductTemplate) Build() *models.Product {
	m := &models.Product{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Category != nil {
		m.Category = o.Category()
	}
	if o.Price != nil {
		m.Price = o.Price()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ProductSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ProductTemplate.CreateMany
func (o ProductTemplate) BuildMany(number int) models.ProductSlice {
	m := make(models.ProductSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableProduct(m *models.ProductSetter) {
	if !(m.Name.IsValue()) {
		val := random_string(nil, "255")
		m.Name = omit.From(val)
	}
	if !(m.Category.IsValue()) {
		val := random_string(nil, "32")
		m.Category = omit.From(val)
	}
	if !(m.Price.IsValue()) {
		val := random_decimal_Decimal(nil, "10", "2")
		m.Price = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Product
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ProductTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Product) error {
	var err error

	isOrderItemsDone, _ := productRelOrderItemsCtx.Value(ctx)
	if !isOrderItemsDone && o.r.OrderItems != nil {
		ctx = productRelOrderItemsCtx.WithValue(ctx, true)
		for _, r := range o.r.OrderItems {
			if r.o.alreadyPersisted {
				m.R.OrderItems = append(m.R.OrderItems, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachOrderItems(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a product and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ProductTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Product, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableProduct(opt)

	m, err := models.Products.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a product and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ProductTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Product {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a product and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ProductTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Product {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple products and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ProductTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ProductSlice, error) {
	var err error
	m := make(models.ProductSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple products and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ProductTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ProductSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple products and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ProductTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ProductSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Product has methods that act as mods for the ProductTemplate
var ProductMods productMods

type productMods struct{}

func (m productMods) RandomizeAllColumns(f *faker.Faker) ProductMod {
	return ProductModSlice{
		ProductMods.RandomID(f),
		ProductMods.RandomName(f),
		ProductMods.RandomCategory(f),
		ProductMods.RandomPrice(f),
		ProductMods.RandomCreatedAt(f),
		ProductMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m productMods) ID(val int64) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m productMods) IDFunc(f func() int64) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m productMods) UnsetID() ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m productMods) RandomID(f *faker.Faker) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m productMods) Name(val string) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m productMods) NameFunc(f func() string) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m productMods) UnsetName() ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m productMods) RandomName(f *faker.Faker) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.Name = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m productMods) Category(val string) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.Category = func() string { return val }
	})
}

// Set the Column from the function
func (m productMods) CategoryFunc(f func() string) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.Category = f
	})
}

// Clear any values for the column
func (m productMods) UnsetCategory() ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.Category = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m productMods) RandomCategory(f *faker.Faker) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.Category = func() string {
			return random_string(f, "32")
		}
	})
}

// Set the model columns to this value
func (m productMods) Price(val decimal.Decimal) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.Price = func() decimal.Decimal { return val }
	})
}

// Set the Column from the function
func (m productMods) PriceFunc(f func() decimal.Decimal) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.Price = f
	})
}

// Clear any values for the column
func (m productMods) UnsetPrice() ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.Price = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m productMods) RandomPrice(f *faker.Faker) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.Price = func() decimal.Decimal {
			return random_decimal_Decimal(f, "10", "2")
		}
	})
}

// Set the model columns to this value
func (m productMods) CreatedAt(val null.Val[time.Time]) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.CreatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m productMods) CreatedAtFunc(f func() null.Val[time.Time]) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m productMods) UnsetCreatedAt() ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m productMods) RandomCreatedAt(f *faker.Faker) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m productMods) RandomCreatedAtNotNull(f *faker.Faker) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m productMods) UpdatedAt(val null.Val[time.Time]) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m productMods) UpdatedAtFunc(f func() null.Val[time.Time]) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m productMods) UnsetUpdatedAt() ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m productMods) RandomUpdatedAt(f *faker.Faker) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m productMods) RandomUpdatedAtNotNull(f *faker.Faker) ProductMod {
	return ProductModFunc(func(_ context.Context, o *ProductTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m productMods) WithParentsCascading() ProductMod {
	return ProductModFunc(func(ctx context.Context, o *ProductTemplate) {
		if isDone, _ := productWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = productWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m productMods) WithOrderItems(number int, related *OrderItemTemplate) ProductMod {
	return ProductModFunc(func(ctx context.Context, o *ProductTemplate) {
		o.r.OrderItems = []*productROrderItemsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m productMods) WithNewOrderItems(number int, mods ...OrderItemMod) ProductMod {
	return ProductModFunc(func(ctx context.Context, o *ProductTemplate) {
		related := o.f.NewOrderItemWithContext(ctx, mods...)
		m.WithOrderItems(number, related).Apply(ctx, o)
	})
}

func (m productMods) AddOrderItems(number int, related *OrderItemTemplate) ProductMod {
	return ProductModFunc(func(ctx context.Context, o *ProductTemplate) {
		o.r.OrderItems = append(o.r.OrderItems, &productROrderItemsR{
			number: number,
			o:      related,
		})
	})
}

func (m productMods) AddNewOrderItems(number int, mods ...OrderItemMod) ProductMod {
	return ProductModFunc(func(ctx context.Context, o *ProductTemplate) {
		related := o.f.NewOrderItemWithContext(ctx, mods...)
		m.AddOrderItems(number, related).Apply(ctx, o)
	})
}

func (m productMods) AddExistingOrderItems(existingModels ...*models.OrderItem) ProductMod {
	return ProductModFunc(func(ctx context.Context, o *ProductTemplate) {
		for _, em := range existingModels {
			o.r.OrderItems = append(o.r.OrderItems, &productROrderItemsR{
				o: o.f.FromExistingOrderItem(em),
			})
		}
	})
}

func (m productMods) WithoutOrderItems() ProductMod {
	return ProductModFunc(func(ctx context.Context, o *ProductTemplate) {
		o.r.OrderItems = nil
	})
}
