// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	models "github.com/acsellers/golang-db-compare/store/mysql/bob/models"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
)

type ReportingOrderMod interface {
	Apply(context.Context, *ReportingOrderTemplate)
}

type ReportingOrderModFunc func(context.Context, *ReportingOrderTemplate)

func (f ReportingOrderModFunc) Apply(ctx context.Context, n *ReportingOrderTemplate) {
	f(ctx, n)
}

type ReportingOrderModSlice []ReportingOrderMod

func (mods ReportingOrderModSlice) Apply(ctx context.Context, n *ReportingOrderTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ReportingOrderTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ReportingOrderTemplate struct {
	ID          func() int64
	Category    func() string
	OrderType   func() string
	ReportOrder func() int32
	Title       func() string
	CreatedAt   func() null.Val[time.Time]
	UpdatedAt   func() null.Val[time.Time]

	f *Factory

	alreadyPersisted bool
}

// Apply mods to the ReportingOrderTemplate
func (o *ReportingOrderTemplate) Apply(ctx context.Context, mods ...ReportingOrderMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.ReportingOrder
// according to the relationships in the template. Nothing is inserted into the db
func (t ReportingOrderTemplate) setModelRels(o *models.ReportingOrder) {}

// BuildSetter returns an *models.ReportingOrderSetter
// this does nothing with the relationship templates
func (o ReportingOrderTemplate) BuildSetter() *models.ReportingOrderSetter {
	m := &models.ReportingOrderSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.Category != nil {
		val := o.Category()
		m.Category = omit.From(val)
	}
	if o.OrderType != nil {
		val := o.OrderType()
		m.OrderType = omit.From(val)
	}
	if o.ReportOrder != nil {
		val := o.ReportOrder()
		m.ReportOrder = omit.From(val)
	}
	if o.Title != nil {
		val := o.Title()
		m.Title = omit.From(val)
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = omitnull.FromNull(val)
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = omitnull.FromNull(val)
	}

	return m
}

// BuildManySetter returns an []*models.ReportingOrderSetter
// this does nothing with the relationship templates
func (o ReportingOrderTemplate) BuildManySetter(number int) []*models.ReportingOrderSetter {
	m := make([]*models.ReportingOrderSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.ReportingOrder
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ReportingOrderTemplate.Create
func (o ReportingOrderTemplate) Build() *models.ReportingOrder {
	m := &models.ReportingOrder{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Category != nil {
		m.Category = o.Category()
	}
	if o.OrderType != nil {
		m.OrderType = o.OrderType()
	}
	if o.ReportOrder != nil {
		m.ReportOrder = o.ReportOrder()
	}
	if o.Title != nil {
		m.Title = o.Title()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ReportingOrderSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ReportingOrderTemplate.CreateMany
func (o ReportingOrderTemplate) BuildMany(number int) models.ReportingOrderSlice {
	m := make(models.ReportingOrderSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableReportingOrder(m *models.ReportingOrderSetter) {
	if !(m.Category.IsValue()) {
		val := random_string(nil, "32")
		m.Category = omit.From(val)
	}
	if !(m.OrderType.IsValue()) {
		val := random_string(nil, "12")
		m.OrderType = omit.From(val)
	}
	if !(m.ReportOrder.IsValue()) {
		val := random_int32(nil)
		m.ReportOrder = omit.From(val)
	}
	if !(m.Title.IsValue()) {
		val := random_string(nil, "255")
		m.Title = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.ReportingOrder
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ReportingOrderTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.ReportingOrder) error {
	var err error

	return err
}

// Create builds a reportingOrder and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ReportingOrderTemplate) Create(ctx context.Context, exec bob.Executor) (*models.ReportingOrder, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableReportingOrder(opt)

	m, err := models.ReportingOrders.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a reportingOrder and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ReportingOrderTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.ReportingOrder {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a reportingOrder and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ReportingOrderTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.ReportingOrder {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple reportingOrders and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ReportingOrderTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ReportingOrderSlice, error) {
	var err error
	m := make(models.ReportingOrderSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple reportingOrders and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ReportingOrderTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ReportingOrderSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple reportingOrders and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ReportingOrderTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ReportingOrderSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// ReportingOrder has methods that act as mods for the ReportingOrderTemplate
var ReportingOrderMods reportingOrderMods

type reportingOrderMods struct{}

func (m reportingOrderMods) RandomizeAllColumns(f *faker.Faker) ReportingOrderMod {
	return ReportingOrderModSlice{
		ReportingOrderMods.RandomID(f),
		ReportingOrderMods.RandomCategory(f),
		ReportingOrderMods.RandomOrderType(f),
		ReportingOrderMods.RandomReportOrder(f),
		ReportingOrderMods.RandomTitle(f),
		ReportingOrderMods.RandomCreatedAt(f),
		ReportingOrderMods.RandomUpdatedAt(f),
	}
}

// Set the model columns to this value
func (m reportingOrderMods) ID(val int64) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.ID = func() int64 { return val }
	})
}

// Set the Column from the function
func (m reportingOrderMods) IDFunc(f func() int64) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m reportingOrderMods) UnsetID() ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m reportingOrderMods) RandomID(f *faker.Faker) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.ID = func() int64 {
			return random_int64(f)
		}
	})
}

// Set the model columns to this value
func (m reportingOrderMods) Category(val string) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.Category = func() string { return val }
	})
}

// Set the Column from the function
func (m reportingOrderMods) CategoryFunc(f func() string) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.Category = f
	})
}

// Clear any values for the column
func (m reportingOrderMods) UnsetCategory() ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.Category = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m reportingOrderMods) RandomCategory(f *faker.Faker) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.Category = func() string {
			return random_string(f, "32")
		}
	})
}

// Set the model columns to this value
func (m reportingOrderMods) OrderType(val string) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.OrderType = func() string { return val }
	})
}

// Set the Column from the function
func (m reportingOrderMods) OrderTypeFunc(f func() string) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.OrderType = f
	})
}

// Clear any values for the column
func (m reportingOrderMods) UnsetOrderType() ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.OrderType = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m reportingOrderMods) RandomOrderType(f *faker.Faker) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.OrderType = func() string {
			return random_string(f, "12")
		}
	})
}

// Set the model columns to this value
func (m reportingOrderMods) ReportOrder(val int32) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.ReportOrder = func() int32 { return val }
	})
}

// Set the Column from the function
func (m reportingOrderMods) ReportOrderFunc(f func() int32) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.ReportOrder = f
	})
}

// Clear any values for the column
func (m reportingOrderMods) UnsetReportOrder() ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.ReportOrder = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m reportingOrderMods) RandomReportOrder(f *faker.Faker) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.ReportOrder = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m reportingOrderMods) Title(val string) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.Title = func() string { return val }
	})
}

// Set the Column from the function
func (m reportingOrderMods) TitleFunc(f func() string) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.Title = f
	})
}

// Clear any values for the column
func (m reportingOrderMods) UnsetTitle() ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.Title = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m reportingOrderMods) RandomTitle(f *faker.Faker) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.Title = func() string {
			return random_string(f, "255")
		}
	})
}

// Set the model columns to this value
func (m reportingOrderMods) CreatedAt(val null.Val[time.Time]) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.CreatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m reportingOrderMods) CreatedAtFunc(f func() null.Val[time.Time]) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m reportingOrderMods) UnsetCreatedAt() ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m reportingOrderMods) RandomCreatedAt(f *faker.Faker) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m reportingOrderMods) RandomCreatedAtNotNull(f *faker.Faker) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.CreatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Set the model columns to this value
func (m reportingOrderMods) UpdatedAt(val null.Val[time.Time]) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] { return val }
	})
}

// Set the Column from the function
func (m reportingOrderMods) UpdatedAtFunc(f func() null.Val[time.Time]) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m reportingOrderMods) UnsetUpdatedAt() ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m reportingOrderMods) RandomUpdatedAt(f *faker.Faker) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m reportingOrderMods) RandomUpdatedAtNotNull(f *faker.Faker) ReportingOrderMod {
	return ReportingOrderModFunc(func(_ context.Context, o *ReportingOrderTemplate) {
		o.UpdatedAt = func() null.Val[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return null.From(val)
		}
	})
}

func (m reportingOrderMods) WithParentsCascading() ReportingOrderMod {
	return ReportingOrderModFunc(func(ctx context.Context, o *ReportingOrderTemplate) {
		if isDone, _ := reportingOrderWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = reportingOrderWithParentsCascadingCtx.WithValue(ctx, true)
	})
}
