// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Customer struct {
	ID             int64
	Name           string
	Phone          sql.NullString
	Email          sql.NullString
	MarketingOptIn sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type DimDate struct {
	Date        time.Time
	Month       int32
	Year        int32
	Quarter     int32
	DayOfWeek   int32
	DayOfMonth  int32
	DayOfYear   int32
	WeekOfYear  int32
	WeekOfMonth int32
}

type Discount struct {
	ID           int64
	Name         string
	Category     string
	DiscountType string
	Discount     string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type ItemSummary struct {
	ID            int64
	Name          string
	Category      string
	OrderType     string
	OrderDate     time.Time
	TotalQuantity interface{}
	TotalSales    interface{}
	OrderCount    int64
}

type Order struct {
	ID             int64
	OrderDate      time.Time
	CustomerID     sql.NullInt64
	DiscountID     sql.NullInt64
	OrderType      string
	Subtotal       string
	DiscountAmount string
	TaxAmount      string
	Total          string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type OrderItem struct {
	ID             int64
	OrderID        int64
	ProductID      int64
	DiscountID     sql.NullInt64
	Quantity       int32
	Price          string
	DiscountAmount string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type OrderPayment struct {
	ID          int64
	OrderID     int64
	PaymentType string
	Amount      string
	PaymentInfo json.RawMessage
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type PaymentName struct {
	ID          int64
	PaymentType string
	Name        string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Product struct {
	ID        int64
	Name      string
	Category  string
	Price     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ReportingOrder struct {
	ID          int64
	Category    string
	OrderType   string
	ReportOrder int32
	Title       string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
