// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CustomerErrors = &customerErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "customers",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type customerErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
