// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var DimDateErrors = &dimDateErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "dim_date",
		columns: []string{"date"},
		s:       "PRIMARY",
	},
}

type dimDateErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
