// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var DiscountErrors = &discountErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "discounts",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type discountErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
