// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var LocationErrors = &locationErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "locations",
		columns: []string{"id"},
		s:       "PRIMARY",
	},

	ErrUniqueName: &UniqueConstraintError{
		schema:  "",
		table:   "locations",
		columns: []string{"name"},
		s:       "name",
	},
}

type locationErrors struct {
	ErrUniquePrimary *UniqueConstraintError

	ErrUniqueName *UniqueConstraintError
}
