// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var OrderPaymentErrors = &orderPaymentErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "order_payments",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type orderPaymentErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
