// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var ProductErrors = &productErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "products",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type productErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
