// Code generated by BobGen mysql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var ReportingOrderErrors = &reportingOrderErrors{
	ErrUniquePrimary: &UniqueConstraintError{
		schema:  "",
		table:   "reporting_order",
		columns: []string{"id"},
		s:       "PRIMARY",
	},
}

type reportingOrderErrors struct {
	ErrUniquePrimary *UniqueConstraintError
}
